Unity-Technologies/com.unity.cinemachine

- Runtime/Behaviours/CinemachineConfiner.cs
This offers a small improvement in the check for the automatic invalidation of the path cache for CinemachineConfiner.  
Notably this allows a CinemachineConfiner to maintain proper functionality in all scenarios where a CompositeCollider2D has a new Collider2D added to it, without requiring the user to call InvalidatePathCache().  
Currently scenarios where an added Collider2D creates a new path are handled without the need to call InvalidatePathCache(), but scenarios where the number of paths stays the same cause improper behavior unless InvalidatePathCache() is called.  This discrepancy is what led to the creation of this pull request.
> Improvement of automatic invalidation of confiner path cache.

- Editor/Utility/EmbeddedAssetHelpers.cs
Fixed issue: [1179842](https://issuetracker.unity3d.com/issues/vcs-null-reference-when-setting-chinemachinebrain-custom-blend-via-script-when-using-perforce)
Replaced the conditional with a simple call to AssetDatabase.IsOpenForEdit since that's how asset editability should (ideally) be checked.
> Fix case [1179842]: Change the way asset editability is checked for components

- Runtime/Behaviours/CinemachinePixelPerfect.cs
- Runtime/Behaviours/CinemachinePixelPerfect.cs.meta
- Runtime/com.unity.cinemachine.asmdef
Now that the extension is moved to CM itself, it needs to support both the standalone pixel perfect package and URP. If both pixel perfect package and URP are installed in the same project (which should not happen as they don't work together), the Pixel Perfect Camera in URP will have the priority.
As this PR adds an optional dependency of Pixel Perfect package to CM, I'll update the PP package so that we don't run into the same circular dependency issue with URP.
> Updated the Pixel Perfect extension to also support the standalone package.

- Runtime/Core/CinemachineCore.cs
Forum post:
https://forum.unity.com/threads/possible-leak.772364/
Dictionary was not cleaned after a camera was deleted.
mRoundRobinVcamLastFrame was not set to null, when the camera it referenced was deleted.
Also, changed static dictionary to non-static. But this does not affect the leak, so if preferred, it can be set back to a static dictionary.
> Fixed leak reported on the forum

- Editor/Impulse/CinemachineImpulseChannels.cs
https://fogbugz.unity3d.com/f/cases/1213434
After hitting cancel, sInstance was null. So I added a null-check before accessing it.
> NullReferenceException on selecting Cancel while editing Impluse Channel in Cinemachine Impulse source

- CHANGELOG.md
- Editor/Editors/CinemachineStoryboardEditor.cs
- Extras~/ReleaseNotes.txt
- Runtime/Behaviours/CinemachineBrain.cs
Addressing this ticket: https://fogbugz.unity3d.com/f/cases/1213819
I added 
```
#if UNITY_EDITOR
UnityEditorInternal.InternalEditorUtility.RepaintAllViews();
#endif
```
where CMBrainEditor knows the editor value has changed.
**May not be a good solution**, but I could not find any problems caused by this fix, and it solved the problem.
I tested these example scenes: FollowCam, Composer and Timeline scene.
I also found an alternative solution instead of `UnityEditorInternal.InternalEditorUtility.RepaintAllViews()`, here:
https://answers.unity.com/questions/1421572/instantaneous-editorguilayoutcolorfield.html
It claims to be faster. 
Alternative solution:
```
System.Reflection.Assembly assembly = typeof(EditorWindow).Assembly;
System.Type type = assembly.GetType( "UnityEditor.GameView" ); …
```
> Game View update on Editor value change - bug 1213819

- CHANGELOG.md
- Editor/PropertyDrawers/NoiseSettingsPropertyDrawer.cs
- Editor/PropertyDrawers/VcamTargetPropertyDrawer.cs
- Editor/PropertyDrawers/VcamTargetPropertyDrawer.cs.meta
- Editor/Utility/InspectorUtility.cs
- Extras~/ReleaseNotes.txt
- Runtime/Behaviours/CinemachineBlendListCamera.cs
- Runtime/Behaviours/CinemachineClearShot.cs
- Runtime/Behaviours/CinemachineExternalCamera.cs
- Runtime/Behaviours/CinemachineFreeLook.cs
- Runtime/Behaviours/CinemachineStateDrivenCamera.cs
- Runtime/Behaviours/CinemachineVirtualCamera.cs
- Runtime/Core/CinemachinePropertyAttribute.cs
- Runtime/Experimental/CinemachineNewVirtualCamera.cs
It shows a little gear icon next to the Follow and LookAt fields in the vcam inspector.  When the field is populated you can click on the icon to create a TragetGroup, add the object to the group, and use the group as a target.  A useful shortcut.
> Add Convert to TargetGroup option on LookAt and Follow target fields

- CHANGELOG.md
- Editor/Editors/CinemachineConfinerEditor.cs
- Extras~/ReleaseNotes.txt
- Runtime/Behaviours/CinemachineConfiner.cs
When BoundingShape2D/BoundingVolume is changed, we need to invalidate the cache.
I created a getter/setter for these parameters. When they are set, the cache is invalidated.
However, when the property is changed in the editor, it is not changed through the setter, so we need to invalidate cache in the OnValidate method.
QUESTION:
Do we want to expose `InvalidatePathCache` function after this change?
```
/// <summary>Call this if the bounding shape's points change at runtime</summary>
public void InvalidatePathCache() { m_pathCache = null; }
```
> Confiner cache reset

- Runtime/Core/CinemachineVirtualCameraBase.cs
Because `enable = false` will call `OnDisable` function immediately, we need move sanity check statements to below normal enable statements.
> incorrect sanity check

- Runtime/Behaviours/CinemachineBrain.cs
- Runtime/Behaviours/CinemachineExternalCamera.cs
- Runtime/Core/CinemachineVirtualCameraBase.cs
- Runtime/Core/LensSettings.cs
- Runtime/PostProcessing/CinemachinePostProcessing.cs
Reported by customer.
Fixed for 2019.2 and up, using new TryGetComponent API
> Remove some GC allocs when in edit mode (reported by customer)

- Editor/Editors/CinemachineBlendListCameraEditor.cs
- Editor/Editors/CinemachineBrainEditor.cs
- Editor/Editors/CinemachineClearShotEditor.cs
- Editor/Editors/CinemachineColliderEditor.cs
- Editor/Editors/CinemachineConfinerEditor.cs
- Editor/Editors/CinemachineExternalCameraEditor.cs
- Editor/Editors/CinemachineFreeLookEditor.cs
- Editor/Editors/CinemachineStoryboardEditor.cs
- Editor/Editors/CinemachineVirtualCameraBaseEditor.cs
- Editor/Editors/CinemachineVirtualCameraEditor.cs
- Editor/Impulse/CinemachineImpulseChannelPropertyDrawer.cs
- Editor/Impulse/CinemachineImpulseListenerEditor.cs
- Editor/PropertyDrawers/CinemachineTagFieldPropertyDrawer.cs
- Editor/PropertyDrawers/NoiseSettingsPropertyDrawer.cs
- Runtime/Behaviours/CinemachineVirtualCamera.cs
- Runtime/Components/CinemachineComposer.cs
-----
Added multi-selection support to Cinemachine editors where it made sense, including:
- Virtual Camera
- Free Look Camera
- Blend List, Clear Shot Cameras (support is limited due to these pointing to child objects of the GO to which the camera component is attached, thus there is no multi-editing for that)
- All of the Extensions
------
Tested manually to work when handling multiple objects by myself and our internal team QA.
> [Editor] Enable multi-editing of Cinemachine components/extensions, where applicable

- Editor/Editors/CinemachinePathEditor.cs
- Editor/Editors/CinemachineSmoothPathEditor.cs
- Editor/Editors/CinemachineTrackedDollyEditor.cs
- Runtime/Behaviours/CinemachineSmoothPath.cs
- Runtime/Core/SplineHelpers.cs
- Only render full "railroad" track for currently active selection,
- Small micro-optimizations in path evaluation code.
On BoatAttack project, cuts down CM path gizmo rendering time (per camera - there's two cameras in that project) from 4.06ms down to 0.79ms on my machine.
> Optimize path gizmos

- Editor/Timeline/CinemachineShotEditor.cs
- Runtime/Behaviours/CinemachineConfiner.cs
- Runtime/Core/TargetPositionCache.cs
- Runtime/Timeline/CinemachineMixer.cs
Heavy files were failing because targets that were warped between shots got lerped if the timeline skipped frames.  Fixed it by tracking the camera cuts and not lerping target positions immediately before them.  
Also fixed a few other problems:
- all track vcams were getting scrubbed every frame, instead of just the active ones.  This was wasteful
- vcam parents were being updated instead of vcam children (this was just dumb)
- removed useless cache resolution setting.  Fixed it to 60 fps
> Refactor scrub bubble to track camera cuts

- CHANGELOG.md
- Extras~/ReleaseNotes.txt
- Runtime/Behaviours/CinemachineBlendListCamera.cs
- Runtime/Behaviours/CinemachineBrain.cs
- Runtime/Core/CinemachineBlend.cs
- Runtime/Core/CinemachineVirtualCameraBase.cs
Bugfix for issue reported here:
https://forum.unity.com/threads/unexpected-delay-in-blend-list-camera-cuts.970029/#post-6312258
> Bugfix: BlendList camera was incorrectly holding 0-length camera cuts

- CHANGELOG.md
- Editor/Windows/CinemachineSettings.cs
- Extras~/ReleaseNotes.txt
Fix for https://fogbugz.unity3d.com/f/cases/1174993/.
The bug was caused by 
```
AssetDatabase.LoadAssetAtPath<Texture2D>( ScriptableObjectUtility.CinemachineRealativeInstallPath + "/Editor/EditorResources/cm_logo_sm.png"); 
```
Because AssetDatabase does not find the Texture after the package is added. We need to wait one update cycle.
> Bugfix for 1174993 + release notes

- CHANGELOG.md
- Editor/Editors/CinemachineStoryboardEditor.cs
- Editor/Windows/CinemachineSettings.cs
Move global mute option to preferences as first entry. Removed Cinemachine top menu.
Storyboard component has access to global mute too.
CMCL-162
> Moved Storyboard Global Mute to preferences

- Editor/Editors/CinemachineConfiner2DEditor.cs
- Runtime/Behaviours/CinemachineConfiner2D.cs
- Runtime/Core/UnityVectorExtensions.cs
- Confiner is baked using its current transform - translation included.
- A delta matrix is computed to account for confiner offset and transform changes since baking.
- ConfinePoint() returns the confined point, not the displacement vector.  This is important because it has to be transformed back to world space **before** the displacement is calculated.
- Gizmo drawer sets Gizmos.matrix before drawing.  This is much more efficient than matrix-multiplying every point.
> Cleanup matrix code

- CHANGELOG.md
- Runtime/Core/CinemachineCore.cs
Bug reported here:
https://forum.unity.com/threads/mathf-perlinnoise-breaks-when-reactivating-vcams-too-often-for-too-long.999729/
> make sure newly activated vcams don't get a huge frame delta

- Runtime/Behaviours/CinemachineConfiner2D.cs
- Runtime/Core/ShrinkablePolygon.cs
- Runtime/Core/UnityVectorExtensions.cs
- Tests/Runtime/UnityVectorExtensionTests.cs
Fixed FindIntersection to handle overlapping and zero-length segments.
After implementing this, I noticed that a confiner unity test is failing. It's possible that the old behaviour of FindIntersection was hiding a bug.
> Fix FindIntersection to handle parallel segments

- Runtime/Behaviours/CinemachineBrain.cs
- Runtime/Core/CinemachineCore.cs
- Runtime/Core/CinemachineVirtualCameraBase.cs
https://fogbugz.unity3d.com/f/cases/1293429/
The problem is that we start with three vcams: A, B, C.
A priority = 30
B priority = 20
C priority = 10
From script we change the priorities to A=0, B=0, C=10. Still, brain selects camera A, because that is at the top of the priority list (because it was not resorted).
> Vcam priority set from script did not trigger resort of active vcams.

- CHANGELOG.md
- Runtime/Behaviours/CinemachineStoryboard.cs
The bug was caused because the viewport size was one pixel shorter.
The bug is only present with not-pixel-perfect setups.
> Storyboard 1 pixel border bug

- CHANGELOG.md
- Runtime/Behaviours/CinemachineStoryboard.cs
Bug was caused by GetComponentInChildren. This returned mCanvas, instead of Viewport.
> storyboard hotreload bug

- Runtime/Components/CinemachineFramingTransposer.cs
The fix is tiny, but was not easy to find :). 
!= is not precise enough (it's overloaded with a dot equal)
```
private static bool IsEqualUsingDot(float dot)
{
return (double) dot > 0.9999989867210388;
}
```
> Removed condition which caused the flick.

- CHANGELOG.md
- Runtime/Helpers/CinemachineInputProvider.cs
https://forum.unity.com/threads/input-action-reference-wont-disable-on-cinemachine.1052192/
We don't check whether Player Input is enabled, before using it.
> Input system enabled/disabled

- Runtime/Core/Predictor.cs
bug reported here: https://forum.unity.com/threads/framingtransposer-has-residual-prediction-velocity-after-being-snapped.1037950/
> CMCL-202: fix broken reset in PositionPredictor

- Editor/Utility/ScriptableObjectUtility.cs
- Tests/Editor/ScriptableObjectUtilityTests.cs
- Tests/Editor/ScriptableObjectUtilityTests.cs.meta
Just assume we're in a package and use straightforward relative path resolution. Drops the non-upm package support based on substring manipulation.
Also added unit tests.
Fixes CMCL-223.
> Don't use scriptable object mono path to get CM install path

- .yamato/package-test.yml
Recommended by the Yamato team. This becomes the default behaviour March 1st anyway.
> set cancel_old_ci to true to reduce yamato load

- .github/pull_request_template.md
Floating this default PR template for discussion (grabbed this from the Live Production team and tweaked it a bit).
What's the problem I'm trying to solve?
1. forgetting to update the changelog or readme
2. forgetting to include the JIRA issue 
3. forgetting to update the docs
4. forgetting to add unit tests
5. above all, consistency 
View the rendered template [here](https://github.com/Unity-Technologies/upm-package-cinemachine/blob/process/add-pull-request-template/.github/pull_request_template.md).
> added proposed pull request template

- Documentation~/cinemachine.md
- Runtime/Core/CinemachineCore.cs
- package.json
Bumped cinemachine version to 2.8.0 
Minor version bump due to adding new functionality and APIs.
> bumped Cinemachine version to 2.8.0

- CHANGELOG.md
- Runtime/Components/Cinemachine3rdPersonFollow.cs
CMCL-233: 3rdPerson damping should be in camera space not worldspace
Backport for #184 
low
- Open AimingRig sample, give the vcam body a high z damping
- Play the game and observe damping is in world space
- Should be in camera space
Note: this fix is needed for starter assets project, so it needs to be backported for 2020 LTS verified version
> [2.7 backport] CMCL-233: 3rdPerson damping in camera space not worldspace

- CHANGELOG.md
- Runtime/Components/Cinemachine3rdPersonFollow.cs
CMCL-233: 3rdPerson damping should be in camera space not worldspace
This is the same as PR #183, plus some local name changes for consistency.  Re-done for the main brnch, which has other changes in that file
low
- Open AimingRig sample, give the vcam body a high z damping
- Play the game and observe damping is in world space
- Should be in camera space
> CMCL-233: 3rdPerson damping should be in camera space not worldspace

- CHANGELOG.md
- Runtime/Core/CinemachineCore.cs
Make it easier for clients to call OnTargetObjectWarped - one call instead of iterating over vcams
0
Just look at the code
> CMCL-244: Add CinemachineCore.OnTargetObjectWarped

- .yamato/package-test.yml
Developer services advised that Ubuntu is the cheapest/fastest platform for testing. Switches our triggered tests & validation to Ubuntu.
> [skip ci] switch to Ubuntu for trigger tests and validation

- CHANGELOG.md
- Runtime/Components/Cinemachine3rdPersonFollow.cs
CMCL-236: 3rdPersonFollow was stuttering when z damping was high
**Note** This PR should be packported to 2.6 and 2.7
low
See jira issue
> Fix CMCL-236: 3rdPersonFollow was stuttering when z damping was high

- CHANGELOG.md
- Documentation~/Cinemachine3rdPersonFollow.md
- Runtime/Behaviours/Cinemachine3rdPersonAim.cs
- Runtime/Components/Cinemachine3rdPersonFollow.cs
CMCL-241.  Expanded CollisionDamping into DampingIntoCollision and DampingFromCollision, for greater control.  Customers expect it, since it's available in CinemachineCollider.
0
Open AimingRig sample, see these sliders, play with the values.  Go near a wall and occlude.
> Fix CMCL-241 - add Damping Into Collision to 3rdPerson

- CHANGELOG.md
- Editor/Editors/CinemachineBrainEditor.cs
- Runtime/Core/LensSettings.cs
Fixes CMCL-238: If I have an orthographic camera, the CinemachineBrain component prevents me from giving it a negative near clip plane (which should be fine for an orthographic camera). 
low
> Fixes CMCL-238: Added ability for vcam to have a negative clip plane

- CHANGELOG.md
- Runtime/Behaviours/CinemachineBrain.cs
- Runtime/Behaviours/CinemachineFreeLook.cs
- Runtime/Behaviours/CinemachineVirtualCamera.cs
- Runtime/Components/CinemachineFramingTransposer.cs
- Runtime/Components/CinemachineOrbitalTransposer.cs
- Runtime/Components/CinemachinePOV.cs
- Runtime/Core/CinemachineCore.cs
- Runtime/Experimental/CinemachineNewFreeLook.cs
- Runtime/Experimental/CinemachineNewVirtualCamera.cs
fixes CMCL-228: Interrupting a transition with InheritPosition enabled is broken
low
Install the unitypackage included with CMCL-228 for a repro
> Fix CMCL-228: Add IsLiveInBlend

- CHANGELOG.md
- Runtime/Components/CinemachineFramingTransposer.cs
CMCL-269: Framing transposer does not handle empty groups
low
> CMCL-269: Framing transposer now handles empty groups

- CHANGELOG.md
- Runtime/Behaviours/CinemachineFreeLook.cs
- Runtime/Behaviours/CinemachineVirtualCamera.cs
- Runtime/Components/CinemachineComposer.cs
- Runtime/Components/CinemachineFramingTransposer.cs
- Runtime/Components/CinemachineTransposer.cs
- Runtime/Core/CinemachineComponentBase.cs
- Runtime/Core/CinemachineVirtualCameraBase.cs
- Runtime/Experimental/CinemachineNewFreeLook.cs
- Runtime/Experimental/CinemachineNewVirtualCamera.cs
CMCL-237: vcam does not respond correctly when target is programmatically changed on a live vcam.
It seems like a big change, but much of it was to set up for upcoming change (allow smooth transitions when target changes on live vcam).
low
Can test with sample project included in Jira issue.
> CMCL-237: Invalidate previous state on target change

- Runtime/Behaviours/CinemachineBlendListCamera.cs
https://jira.unity3d.com/browse/CMCL-143
When using a CM BlendListCamera, if you add Virtual Camera Children and you do a Reset on the CinemachineBlendListCamera, they will disapear.
Fix blend list camera children inspector UI after Reset.
Do we need to update changelog for this?
[Justification for updating either the patch, minor, or major version according to the [semantic …
> Blendlist reset works correctly now

- CHANGELOG.md
- Runtime/Components/Cinemachine3rdPersonFollow.cs
https://jira.unity3d.com/browse/CMCL-282
By default collision handling should be off.
Change the default value of 3rdPersonFollow's collision detection to Nothing. This way, collision detection is off by default. Also added a check if the collision filter is nothing, we can just return tip in CollisionHandling.
0
[Justification for updating either the patch, minor, or major version according to the [semantic …
> Collision handling off by default on 3rdPersonFollow.

- Editor/Utility/SaveDuringPlay.cs
Made SaveDuringPlay string with equality instead of contains.
[Justification for updating either the patch, minor, or major version according to the [semantic …
> SaveDuringPlay - Test type string equality instead of contains

- CHANGELOG.md
- Runtime/Behaviours/CinemachineBrain.cs
https://jira.unity3d.com/browse/CMCL-286
Basically, the user is saying that if we have a fast blend in (from A to B), and a slow blend out (from B to A), then: * if Blend In is interrupted by Blend Out, then Blend Out is going to be fast.
The reason is that in we set the Time without normalizing in CinemachineBrain
if (frame.blend.CamA == activeCamera
&& frame.blend.CamB == outGoingCamera
&& frame.blend.Duration <= blendDef.BlendTime)
{ blendDef.m_Time = frame.blend.TimeInBlend; // <--- here }
I think, instead we should normalize the time like this:
blendDef.m_Time = (frame.blend.TimeInBlend / frame.blend.Duration) * blendDef.BlendTime;
[Explanation of what’s tested, how tested and existing or new automation tests. Can include manual testing by self and/or QA. Specify test plans. Rarely …
> Normalized Blend Time

- CHANGELOG.md
- Runtime/Components/Cinemachine3rdPersonFollow.cs
CMCL-292: 3rdPersonFollow keeps player in view when Z damping high
low
See forum post and test with AimingRig sample
> CMCL-292: 3rdPersonFollow keeps player in view when Z damping high

- CHANGELOG.md
- Runtime/PostProcessing/CinemachinePostProcessing.cs
- Runtime/PostProcessing/CinemachineVolumeSettings.cs
https://jira.unity3d.com/browse/CMCL-290
https://forum.unity.com/threads/depth-of-field-effect-is-broken-when-using-cinemachine-2-6-0-and-above.1088446/
Fix a regression in CMPostProcessing.
The problem is only with Framing Transposer, because the state is incorrect in the post aim stage.
Applying PostProcessing post Finalize (or Noise) stage fixes this. …
> CMPostprocessing state bug

- CHANGELOG.md
- Documentation~/cinemachine.md
- Runtime/Core/CinemachineCore.cs
- package.json
Updates package.json, CHANGELOG, and internal versioning to 2.9.
Removes reference to version number from docs.
> bumped version to 2.9

- .yamato/package-test.yml
They fail with [unreleased] so are useless unless we're tagging a version.
> Update package-test.yml to remove validation tests

- Runtime/Behaviours/Cinemachine3rdPersonAim.cs
- Runtime/Components/Cinemachine3rdPersonFollow.cs
https://jira.unity3d.com/browse/CMCL-307
3rdPersonFollow should not set the rotation of the camera to align with CM pipeline. 3rdPersonAim can deduce rotation from Follow target's transform. This also enables other vcam types to emerge (3rdPersonFollow + any Aim component).
Relates to:
https://jira.unity3d.com/browse/CMDO-209
Tests:
Tested manually with all aim components.
1 and 2 are great rigs!
1. Aim: Same As Follow Target -> This works like 3rd Person Aim (without the hit marker)!
2. Aim: HardLookAt -> If looking at the Follow Target, then we have a simpler version of Freelook!
3. Aim: POV -> Feels weird in the example, because player rotates with POV rotations. But, otherwise it is a useful setup. Use case example: submarine periscope (POV looks around, Follow part sets itself so it …
> 3rdPerson refactor

- CHANGELOG.md
- Editor/Utility/EmbeddedAssetHelpers.cs
- Editor/Utility/SaveDuringPlay.cs
- Runtime/Behaviours/Cinemachine3rdPersonAim.cs
- Runtime/Behaviours/CinemachineBlendListCamera.cs
- Runtime/Behaviours/CinemachineBrain.cs
- Runtime/Behaviours/CinemachineCameraOffset.cs
- Runtime/Behaviours/CinemachineCollider.cs
- Runtime/Behaviours/CinemachineRecomposer.cs
- Runtime/Components/Cinemachine3rdPersonFollow.cs
- Runtime/Components/CinemachineFramingTransposer.cs
- Runtime/Components/CinemachineOrbitalTransposer.cs
- Runtime/Components/CinemachineTrackedDolly.cs
- Runtime/PostProcessing/CinemachinePostProcessing.cs
- Runtime/PostProcessing/CinemachineVolumeSettings.cs
Backports of bugfixes from 2.8
- Bugfix: TrackedDolly sometimes introduced spurious rotations if Default Up and no Aim behaviour.
- Bugfix: CinemachineCollider's displacement damping was being calculated in world space instead of camera space.
- Regression fix: CmPostProcessing and CmVolumeSettings components setting Depth of Field now works correctly with Framing Transposer. 
- Regression fix: 3rdPersonFollow kept player in view when Z damping was high.
- Bugfix: Reversing a blend in progress respects asymmetric blend times.
- Bugfix: SaveDuringPlay saved some components that did not have the SaveDuringPlay attribute.
- Regression fix: Entries in the custom blends editor in CM Brain inspector were not selectable.
- Bugfix: Cinemachine3rdPersonFollow handled collisions by default, now it …
> [2.6.x] Backport bugfixes

- CHANGELOG.md
- Editor/Utility/EmbeddedAssetHelpers.cs
- Editor/Utility/SaveDuringPlay.cs
- Runtime/Behaviours/Cinemachine3rdPersonAim.cs
- Runtime/Behaviours/CinemachineBlendListCamera.cs
- Runtime/Behaviours/CinemachineBrain.cs
- Runtime/Behaviours/CinemachineCameraOffset.cs
- Runtime/Behaviours/CinemachineCollider.cs
- Runtime/Behaviours/CinemachineRecomposer.cs
- Runtime/Components/Cinemachine3rdPersonFollow.cs
- Runtime/Components/CinemachineFramingTransposer.cs
- Runtime/Components/CinemachineOrbitalTransposer.cs
- Runtime/Components/CinemachineTrackedDolly.cs
- Runtime/Core/LensSettings.cs
- Runtime/PostProcessing/CinemachinePostProcessing.cs
- Runtime/PostProcessing/CinemachineVolumeSettings.cs
Backport of bugfixes from 2.8:
- Bugfix: TrackedDolly sometimes introduced spurious rotations if Default Up and no Aim behaviour.
- Bugfix: CinemachineCollider's displacement damping was being calculated in world space instead of camera space.
- Regression fix: CmPostProcessing and CmVolumeSettings components setting Depth of Field now works correctly with Framing Transposer. 
- Regression fix: 3rdPersonFollow kept player in view when Z damping was high.
- Bugfix: Reversing a blend in progress respects asymmetric blend times.
- Bugfix: SaveDuringPlay saved some components that did not have the SaveDuringPlay attribute.
- Regression fix: Entries in the custom blends editor in CM Brain inspector were not selectable.
- Bugfix: Cinemachine3rdPersonFollow handled collisions by default, now it …
> [2.7.x] Backport bugfixes 

- .yamato/package-publish.yml
Attempting to fix this error:
[14:49:14.611 Information] [UPM-CI-UTILS] ERROR - It doesn't look like any tests were run on Unity editor version 2018.4 that's currently defined in the package manifest.
> added all editors to publish validation

- CHANGELOG.md
- Runtime/Behaviours/CinemachineFreeLook.cs
User reported some problems with freelook prefabs, when applying prefab modifications (Override -> Apply All).
1. The children can become visible. 
2. Data is lost.
I could reproduce #1, but not #2. 
I think #2 is a user error. I think this is what happens:
They modify parameter X on prefab instance A, then they modify parameter X on prefab instance B, and then they try to override all prefabs with Override -> Apply All from prefab instance B.
Instance A is not modified in this case, but this is the expected behaviour.
#1 is fixed by adding the HideChildren functionality to the prefab override callback.
https://forum.unity.com/threads/cinemachine-freelook-prefabs-seem-to-become-corrupted.532989/#post-7079488
Low
I deleted SetChildrenFlag from UpdateRigCache. The reason is that I don't see …
> Freelook prefab children are no longer visible.

- CHANGELOG.md
- Runtime/Components/CinemachinePOV.cs
Useful notes on how to reproduce the issue in the JIRA ticket:
https://jira.unity3d.com/browse/CMCL-311
Low
@glabute 
I added the change (MapAngleTo180) to CinemachinePOV.cs to localize the fix. I did not see the bug arise for other classes using AxisState.ClampValue. However, it may be better to put this mapping function to AxisState.ClampValue call.
> CMCL-311 POV recentering bug

- CHANGELOG.md
- Runtime/Core/CameraState.cs
https://jira.unity3d.com/browse/CMCL-315
I am not sure about the fix. I am a bit afraid that somewhere something expects the Lerp result to have a ReferenceUp that is the same as Brain World up. 
The State Lerp code clearly expects the reference up to be dependent on the orientation of the vcam.
`state.ReferenceUp = Vector3.Slerp(stateA.RawOrientation * Vector3.up, stateB.RawOrientation * Vector3.up, t);`
Low, but see Purpose of PR
I am not sure about the fix. I am a bit afraid that somewhere something expects the Lerp result to have a ReferenceUp that is the same as Brain World up. 
The State Lerp code clearly expects the reference up to be dependent on the orientation of the vcam.
`state.ReferenceUp = Vector3.Slerp(stateA.RawOrientation * Vector3.up, stateB.RawOrientation * Vector3.up, …
> ReferenceUp is not correct in CameraState Lerp

- CHANGELOG.md
- Documentation~/CinemachineVirtualCamera.md
- Editor/Editors/CinemachineVirtualCameraBaseEditor.cs
- Runtime/Behaviours/CinemachineBrain.cs
- Runtime/Core/LensSettings.cs
Fix regression bug. Physical property overwrites only work in overwrite mode.
The bug was introduced by me here: https://github.com/Unity-Technologies/com.unity.cinemachine/pull/224/files
Also: move override mode to Advanced section in UX, with a helpbox describing the gotcha.
Updated documentation.
low
> CMCL-332-VCam control of physical camera properties

- Tests/Runtime/CamerasBlendingTests.cs
Yamato failing on Ubuntu. Seems to be a timing issue, Gregory reported same failure on Windows and fix was to pad the timing.
> increased wait time on BlendingBetweenCameras to fix failing test on Linux

- .github/CODEOWNERS
- .yamato/package-promotion.yml
- .yamato/package-publish.yml
- .yamato/package-test.yml
- CHANGELOG.md
- Editor/PostProcessing/CinemachineVolumeSettingsEditor.cs
- Runtime/Behaviours/Cinemachine3rdPersonAim.cs
- Runtime/Behaviours/CinemachineBrain.cs
- Runtime/Behaviours/CinemachineFreeLook.cs
- Runtime/Components/Cinemachine3rdPersonFollow.cs
- Runtime/Components/CinemachinePOV.cs
- Runtime/Core/CameraState.cs
- Runtime/Core/CinemachinePathBase.cs
- Samples~/Cinemachine Example Scenes/Scenes/AimingRig/AimReticle.cs
- Samples~/Cinemachine Example Scenes/Scenes/AimingRig/AimReticle.cs.meta
- Samples~/Cinemachine Example Scenes/Scenes/AimingRig/AimingRig.unity
- Tests/Runtime/CamerasBlendingTests.cs
- Tests/Runtime/CamerasBlendingTests.cs.meta
- ValidationExceptions.json
- package.json
Backports these commits:
* cbe689c Bugfix: Virtual Cameras were not updating in Edit mode when Brain's BlendUpdateMode was FixedUpdate. (#272)
* 6592fd5 increased wait time to fix failing test on Linux (#273)
* 8eaf7d2 changed docs owner to Seb
* b190d76 XML doc typos
* 94a5ed6 Nicer AimingRig scene (#264)
* 30a71c4 Blend condition bug (#263)
* d13297a Bugfix: CinemachineVolumeSettings inspector was making the game view flicker, and warning msg (#261)
* e808cef ReferenceUp is not correct in CameraState Lerp (#256)
* 6f53ae3 CMCL-311 POV recentering bug (#254)
* 9f7c8ee Dev/3rdperson heading fix (#247)
* 3a0a4c4 Freelook prefab children are no longer visible. (#241)
* 2fdff67 fixed yamato bug (#251)
* 4888deb added all editors to publish validation test (#248)
* bc2f6e6 PR236 changelog …
> Backports for 2.6.6

- Tests/Editor/AxisStateTests.cs
- Tests/Editor/DampingTests.cs
- Tests/Editor/ScriptableObjectUtilityTests.cs
- Tests/Editor/UnityVectorExtensionTests.cs
* use Assert.That instead of boolean expressions
* use parameterized tests where possible to avoid copypasta
* enclose in Tests.Editor namespace
"Why the f did you do make all of these changes"
Assert.That gives better messages when tests fail. I was also able to remove some vector comparison code that already exists in the test framework.
Parameterized tests make each test case show up individually in NUnit (and fail independently) and better shows the number of tests. At some point we'll be "graded" on how many tests we have so this is a cheap way to boost our score. It also removed a lot of code duplication.
Namespaces because good practices. Enable the "ignore whitespace" option in Github's diff to hide the noise.
> Cleaned up editor tests

- Tests/Runtime/CameraPositionTests.cs
- Tests/Runtime/CamerasBlendingTests.cs
- Tests/Runtime/CinemachineFixtureBase.cs
- Tests/Runtime/CinemachineFixtureBase.cs.meta
- Tests/Runtime/Confiner2DUnitTests.cs
- Tests/Runtime/FreeLookTests.cs
- Tests/Runtime/FreeLookTests.cs.meta
- Tests/Runtime/StateDrivenCameraTests.cs
CMCL-346
Added tests for CinemachineFreeLook
"why the f did you make all of these changes?!?!"
Cinemachine depends on the global state of the scene, so tests were unstable depending on which order they ran in. To fix this I added a base class with a method for creating gameobjects that cleans them up in a Teardown. I also force a constant deltatime in this class's setup (and clear it in the teardown).
While I was at it, I switched the Asserts to use modern NUnit practices (Assert.That gives better messages when tests fail).
I also moved the tests to their own namespace as a general good practice.
> Added tests for FreeLook

- Tests/Runtime/Cinemachine.RuntimeTests.asmdef
- Tests/Runtime/ClearShotTests.cs
- Tests/Runtime/Confiner2DUnitTests.cs
- Tests/Runtime/StateDrivenCameraTests.cs
Guards tests that require functionality in modules so tests pass in isolation mode (no other packages loaded).
> add versionDefines to runtime test assembly and guard tests 

- CHANGELOG.md
- Runtime/Components/CinemachinePOV.cs
CMCL-375: Bugfix: POV did not properly handle overridden up.
low
Repro scene included in Jira issue
> Bugfix: POV did not properly handle overridden up

- Tests/Runtime/CamerasBlendingTests.cs
CMCL-373
Pads wait time in test as it's unstable on Katana macOS agents (but only there).
> fixes CMCL-373 instability in InterruptedBlendingBetweenCameras test

- CHANGELOG.md
- Runtime/Behaviours/CinemachineBrain.cs
> CMCL-366 async scene load/unload causes jitter

- CHANGELOG.md
- Runtime/Core/CinemachineCore.cs
- Tests/Runtime/CamerasBlendingTests.cs
- ValidationExceptions.json
- package.json
* disable InterruptedBlendingBetweenCameras test on macOS
* update version to 2.6.8
> updates for 2.6.8

- Runtime/Components/CinemachinePOV.cs
- Runtime/Core/CinemachineCore.cs
CMCL-375: custom reference up needs to apply even if vcam has a parent.  Previous fix was imcomplete.
I don't think it's necessary to update the changelog again, there is already an entry for this issue.
low
Uploaded new test project to the Jira ticket to show the issue
> bugfix CMCL-375 redux: POV custom up works even if vcam parent

- Tests/Runtime/CamerasBlendingTests.cs
CMCL-373
Force uniform deltaTime to fix test instability.
> [CMCL-373] force uniform deltatime to fix test instability

- CHANGELOG.md
- QAReport.md
- Tests/Editor/UnityVectorExtensionTests.cs
- Tests/Runtime/StateDrivenCameraTests.cs.meta
Sync master with release/2.8
* updates CHANGELOG
* removes BOM from `Tests/Editor/UnityVectorExtensionTests.cs` and `Tests/Runtime/StateDrivenCameraTests.cs.meta`
> Merge release/2.8 into master

- Tests/Runtime/CamerasBlendingTests.cs
Still failing on 2021.1 in package isolation tests. My theory is that when all of the package isolation tests run, time suffers from inaccuracies due to floating point.
> added extra wait time to account for floating point inaccuracy

- CHANGELOG.md
- Editor/PostProcessing/CinemachineVolumeSettingsEditor.cs
- Runtime/Core/CinemachineCore.cs
- ValidationExceptions.json
- package.json
CMCL-399
Somehow an opening brace moved up one line, above an #ifdef, resulting in a compile error when using LWRP/HDRP. We don't have any tests that explicitly test SRPs and those lines aren't compiled when no SRP is installed.
Also, an #ifdef for HDRP was referencing the wrong version, resulting in an additional error.
TBD: have automated tests run against SRPs
> [CMCL-399] fixes bad merge in Runtime/CinemachineVolumeSettingsEditor.cs

- CHANGELOG.md
- Runtime/Core/CinemachineCore.cs
- Tests/Runtime/CamerasBlendingTests.cs
- package.json
Disables CamerasBlendingTests due to failure on Katana.
> disabled CamerasBlendingTests as they consistently fail on Katana

- CHANGELOG.md
- Runtime/Core/CameraState.cs
- Runtime/Core/UnityVectorExtensions.cs
Fix CMCL-406 - bad blends if looking along world up
low
> Fix CMCL-406 bad blends if looking along world up

- CHANGELOG.md
- Runtime/Components/Cinemachine3rdPersonFollow.cs
CMCL-372: OnTargetObjectWarped did not work properly for 3rdPersonFolow
low
Use this script to test:
[code]using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cinemachine;
public class CameraTPTest : MonoBehaviour
{
public CinemachineVirtualCamera VCam;
public float Speed = 10f;
private void LateUpdate()
{
transform.position = transform.position + (Vector3.forward * Speed * Time.deltaTime);
if (transform.position.magnitude > 20f)
{
Vector3 delta = -transform.position;
transform.position = Vector3.zero;
VCam.OnTargetObjectWarped(transform, delta);
}
}
}[/code]
> CMCL-372: OnTargetObjectWarped did not work properly for 3rdPersonFolow

- CHANGELOG.md
- Runtime/Core/AxisState.cs
CMCL-402 Input system should be read only once per render frame
low
> CMCL-402 Input system should be read only once per render frame

- CHANGELOG.md
- Editor/Editors/CinemachineTargetGroupEditor.cs
- Runtime/Behaviours/CinemachineTargetGroup.cs
- Runtime/Components/CinemachineFramingTransposer.cs
- Runtime/Components/CinemachineGroupComposer.cs
- Runtime/Core/CinemachineVirtualCameraBase.cs
Fix CMCL-433 - Group Framing was inaccurate.  Visible in Framing transposer when target is a Group, and in GroupComposer.  Most visible when camera is angled.  Jira issue has sample scene and repro instructions.
low
> Fix CMCL-433 - Group Framing accuracy

- .github/workflows/validate-pr.yml
Hey devs, part of doing backports is finding the connected JIRA issue so I can add the backport to the Fix Version/s field (or find the appropriate backport and add it there). We've gotten pretty good at putting the JIRA issue in the PR (thank you!) but I'd like to go one step further and put it in the PR title.
Right now, I have to:
find the PR # in merge commit
open the PR
find the JIRA in the description and click it
If we put the JIRA issue right in the title, it will be in the commit message for the merge and I'll be able to just click it directly.
I figured out how to add a Github Action that checks the PR title and fails if it doesn't match a regex (actual regex: `(^CMCL-){1}(\\d)+(:)?(\\s)+(.)+ `). Basically you need your PR title to look like this:  
`CMCL-1000: Effectively …
> CMCL-489: Use off-the-shelf Github action to enforce PR titles start with CMCL-\d+

- Runtime/Behaviours/CinemachineBrain.cs
- Runtime/Timeline/CinemachineMixer.cs
Requested by James Bouckley to support his timeline mixer project.  And just a good idea in any case.  Add an interface class so that the CM Mixer does not need to have any specific knowledge of CM Brain and can thus drive other objects that implement this interface.  This change is fully back-compatible.
low
> CMCL-0000: Add interface class for CM timeline interaction

- CHANGELOG.md
- package.json
Prep for 2.9.0-pre.1: bumps version and updates changelog.
Low.
> CMCL-589: bumped version to 2.9.0-pre.1 and updated changelog

- Editor/Windows/CinemachineSettings.cs
This PR moves initialization code using assets from InitializeOnLoad to OnPostprocessAllAssets. This is done to prepare for an upcoming change in trunk, which will make unity report errors, when asset operations are done in InitializeOnLoad.
A new variant of OnPostprocessAllAssets has been introduced in 2021.2 and is used in this PR.
- [x ] Passed all automated tests
Changes where initialization is done - no need for doc update.
Low risk - minor change. This PR should not change any behaviour.
> EAD-312: Moved initialization code using assets to OnPostprocessAllAssets callback

- CHANGELOG.md
- Runtime/Behaviours/CinemachineBrain.cs
dev/CMCL-608: cannot change camera projection if vcam present
low
> CMCL-608: cannot change camera projection

- CHANGELOG.md
- Editor/Editors/CinemachineVirtualCameraBaseEditor.cs
- Runtime/Core/LensSettings.cs
Fix for https://jira.unity3d.com/browse/CMCL-339
Fix:
- Validate near clip plane when pulling values from camera.
> CMCL-339: Near Clip Plane negative value not kept if override not set to Orthographic

- .npmignore
Hide .gitattributes and .github from npm so they don't end up in the package.
Also remove old license.txt file (replaced by LICENSE.md)
> CMCL-616: added .github and .gitattributes to .npmignore

- CHANGELOG.md
- Runtime/Core/AxisState.cs
CMCL-622: Axis input shouldn't ignore IgnoreTimeScale
low
> CMCL-622: Axis input shouldn't ignore IgnoreTimeScale

- CHANGELOG.md
- Runtime/Core/AxisState.cs
- Runtime/Core/CinemachineCore.cs
- Samples~/Cinemachine Example Scenes.meta
- Samples~/Cinemachine Example Scenes/Scenes/2D/MouseScrollZoom2D.cs
- Samples~/Cinemachine Example Scenes/Scenes/3rdPersonWithAimMode/ActivateOnKeypress.cs
- Samples~/Cinemachine Example Scenes/Scenes/AimingRig/AimingRig.unity
- Samples~/Cinemachine Example Scenes/Scenes/Anywhere Door/PlayerLookAt.cs
- Samples~/Cinemachine Example Scenes/Scenes/Anywhere Door/PlayerMovement.cs
- Samples~/Cinemachine Example Scenes/Shared/Models/UnityCharacter/Scripts/CharacterMovement.cs
- Samples~/Cinemachine Example Scenes/Shared/Models/UnityCharacter/Scripts/CharacterMovement2D.cs
- Samples~/Cinemachine Example Scenes/Shared/Models/UnityCharacter/Scripts/CharacterMovementNoCamera.cs
- Samples~/Cinemachine Example Scenes/Shared/Scripts/InputSystemHelper.cs
- Samples~/Cinemachine Example Scenes/Shared/Scripts/InputSystemHelper.cs.meta
- Samples~/Cinemachine Example Scenes/Shared/Scripts/PlayerMove.cs
- Samples~/Cinemachine Example Scenes/Shared/Scripts/PlayerMoveOnSphere.cs
- Samples~/Cinemachine Example Scenes/Shared/Scripts/PlayerMovePhysics.cs
https://jira.unity3d.com/browse/CMCL-517
When Input System is added to Cinemachine, the Cinemachine examples are throwing a lot of errors, because they are trying to read from the old backends (UnityEngine.Input). 
There is a guard that checks if the old backends are disabled (ENABLE_LEGACY_INPUT_MANAGER). I added this to all example scripts that use Input, and a Debug.Log that tells users how they can fix it.
I added a guard to AxisState too, but I think it is better if that error is actually displayed as it was before. See my review comment for more details.
> CMCL-517: Support for input system in the samples

- Editor/Editors/CinemachineFreeLookEditor.cs
- Editor/Editors/CinemachineVirtualCameraEditor.cs
- Editor/Menus/CinemachineMenu.cs
- Editor/PropertyDrawers/VcamTargetPropertyDrawer.cs
- Editor/Timeline/CinemachineShotClipEditor.cs
- Editor/Timeline/CinemachineShotEditor.cs
- Editor/Utility/InspectorUtility.cs
- Runtime/Core/CinemachineCore.cs
The current implementation used to create Cinemachine Cameras in the Hierarchy is inconsistent with the rest of Unity. This leads to Cinemachine feeling lower quality and some things to not produce the expected result.
Main changes
- Names of created objects are now consistent with the rest of Unity. Example being "Vcam" is now "Virtual Camera".
- Duplicate names of created objects is now consistent with the rest of Unity. Example being "Vcam1" is now "Virtual Camera (1)". This will also support the "Game Object Naming" scheme setting option that is present in newer versions of Unity.
- It is now easier to add more options to the menu later with less boilerplate and places for failure.
Manually used each menu item and ensured that the resulting GameObjects and components are the same as …
> CMCL-570: Refactored menu based creation to be consistent with the rest of Unity

- CHANGELOG.md
- Runtime/Behaviours/CinemachineBrain.cs
- Tests/Runtime/BrainTargetOverrideTests.cs
- Tests/Runtime/BrainTargetOverrideTests.cs.meta
- Tests/Runtime/CameraPositionTests.cs
Add option for user to override CinemachineBrain's targetted gameobject.
https://jira.unity3d.com/browse/CMCL-513
> CMCL-513: Target Override for Brain

- .yamato/package-test.yml
- Editor/Editors/Cinemachine3rdPersonFollowEditor.cs
- Editor/Menus/CinemachineMenu.cs
- Runtime/Components/Cinemachine3rdPersonFollow.cs
https://unity-ci.cds.internal.unity3d.com/job/10143816 is failing when using CM as a dependency.
The only apparent difference is that they're passing --extra-create-project-arg=-upmNoDefaultPackages in both upm-ci package test calls
> CMCL-656: make tests pass without default upm packages

- Runtime/Behaviours/CinemachineConfiner2D.cs
https://jira.unity3d.com/browse/CMCL-664
Calculated confiner is shown for not live vcams.
0
> CMCL-667: Show calculated confiner for not live vcams.

- CHANGELOG.md
- Runtime/Core/CinemachineVirtualCameraBase.cs
CMCL-686: On domain reload vcams were forgetting that they were targeting groups
low
> CMCL-686: targets forget that they are groups

- CHANGELOG.md
- Editor/Editors/Cinemachine3rdPersonFollowEditor.cs
- Runtime/Components/Cinemachine3rdPersonFollow.cs
CMCL-710: gimbal lock console spam when looking straight up or down in 3rdPersonFollow
low
See the repro project included in the fogbugz issue
> CMCL-710: 3rd person gimbal lock fix

- CHANGELOG.md
- Runtime/Helpers/CinemachineInputProvider.cs
https://jira.unity3d.com/browse/CMCL-771
Cinemachine 2.8.4 does not compile on Unity versions that does not support C# 8 and when the Input system package is installed.
> CMCL-771: Cinemachine 2.8.4 produce compiler errors if Input System package is installed.

- CHANGELOG.md
- Runtime/PostProcessing/CinemachinePostProcessing.cs
CMCL-768: memory leak when PostProcessing package installed and no PP Layer on the Brain
low
> CMCL-768: PP memleak

- CHANGELOG.md
- Editor/PropertyDrawers/EmbeddedAssetPropertyDrawer.cs
Fix for https://jira.unity3d.com/browse/CMCL-779.
The fix is relevant in CM 2.7, because in later version this is legacy and not used. But for completeness sake, I added the fix to master, because it may come up with something else too. I'll backport to each version.
The bug was caused because when ImpulseDefintion was part of a list, the reflection got null fields for Array. Then null.FieldType is invalid.
> CMCL-779: ImpulseDefinition property not displayed correctly in the editor.

- Editor/Impulse/CinemachineImpulseDefinitionPropertyDrawer.cs
This fixes https://jira.unity3d.com/browse/CMCL-779 for some other cases for which https://github.com/Unity-Technologies/com.unity.cinemachine/pull/394 was not enough.
So these two PRs fix https://jira.unity3d.com/browse/CMCL-779 together.
No need to add new changelog, because https://github.com/Unity-Technologies/com.unity.cinemachine/pull/394's changelog is valid for this one too.
> CMCL-779: ImpulseDefinition property not displayed correctly in the editor 2

- CHANGELOG.md
- Editor/Helpers/CinemachineTriggerActionEditor.cs
- Editor/Impulse/CinemachineImpulseDefinitionPropertyDrawer.cs
- Editor/PropertyDrawers/EmbeddedAssetPropertyDrawer.cs
- Editor/Windows/CinemachineSettings.cs
- Runtime/Core/AxisState.cs
- Runtime/Core/CinemachineCore.cs
- Runtime/Helpers/CinemachineTriggerAction.cs
- Samples~/Cinemachine Example Scenes/Scenes/Trigger volumes/GenericTrigger.cs
- package.json
Backports:
https://jira.unity3d.com/browse/CMCL-757 -> https://github.com/Unity-Technologies/com.unity.cinemachine/pull/385
https://jira.unity3d.com/browse/CMCL-779 -> https://github.com/Unity-Technologies/com.unity.cinemachine/pull/394 and https://github.com/Unity-Technologies/com.unity.cinemachine/pull/397
https://jira.unity3d.com/browse/CMCL-783 -> https://github.com/Unity-Technologies/com.unity.cinemachine/pull/398
https://jira.unity3d.com/browse/CMCL-622
JIRA:
https://jira.unity3d.com/browse/CMCL-809
[Overview of how documentation is affected by this …
> CMCL-809: Backports for 2.6.12

- CHANGELOG.md
- Runtime/Components/CinemachinePOV.cs
CMCL-862 
https://forum.unity.com/threads/initial-viewing-direction-of-pov-camera.621202/#post-7979415
POV orientation is wrong when there is a WorldUp override
low
> CMCL-862: POV orientation was incorrect with world up override set

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Behaviours/CinemachineConfiner2D.cs
- com.unity.cinemachine/Runtime/Core/ConfinerOven.cs
https://jira.unity3d.com/browse/CMCL-876
Confiner2D confines to midpoint when camera window is bigger than the axis aligned bounding box of the input confiner.
This case was not cover, and was reported by a user. + code cleanup
[Info per person for what to focus on, or historical info to understand who have previously reviewed and coverage. Help them get …
> CMCL-876: Confiner2D confines to midpoint when camera window is bigger than the axis aligned bounding box of the input confiner

- com.unity.cinemachine/Editor/Editors/CinemachineFramingTransposerEditor.cs
- com.unity.cinemachine/Editor/Editors/CinemachineFreeLookEditor.cs
- com.unity.cinemachine/Editor/Editors/CinemachineOrbitalFollowEditor.cs
- com.unity.cinemachine/Editor/Overlays/CinemachineToolbarOverlay.cs
- com.unity.cinemachine/Editor/Utility/CinemachineSceneTools.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineFreeLook.cs
Overlays fix for old freelook.
New overlays for Orbital Follow. Control and select orbits. Orbit selection works only for 3 ring, but could work for sphere too if we want it. The orbit selection directly affects the Vertical Axis value based on the Range and Center values (so it works for sphere too).
> CMCL-881: overlays for cm3

- com.unity.cinemachine/Editor/Editors/Cinemachine3rdPersonFollowEditor.cs
Swap noted that we should remove the 3rdPersonFollow gizmos when using the handles as their are confusing/overlapping with the rig handles.
> CMCL-883: No gizmos while using handles 3rdPersonFollow

- com.unity.cinemachine/Editor/Editors/CinemachineOrbitalFollowEditor.cs
https://jira.unity3d.com/browse/CMCL-884
OnDrag the correct rig is activated, so the user gets visual feedback in the GameView.
> CMCL-884: OrbitalFollow handles: OnDrag select rig

- com.unity.cinemachine/Runtime/Behaviours/CinemachineBrain.cs
https://jira.unity3d.com/browse/CMCL-891:
Fix bug on unreleased branches. Output camera is null on first frame.
Bug introduced by cfb93754283449a99b24d0119c0359c975e68c4a.
> CMCL-891: Fix null output camera on first frame

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Editor/Editors/Cinemachine3rdPersonFollowEditor.cs
https://jira.unity3d.com/browse/CMCL-906
Fixed: ThirdPersonFollow does not display a warning message like the rest of the components when no follow target is assigned.
- [x[ Manually tested
> CMCL-906: 3rdPersonFollow does not warn user when no Follow Target

- com.unity.cinemachine/Editor/Editors/Cinemachine3rdPersonFollowEditor.cs
- com.unity.cinemachine/Editor/Utility/CinemachineSceneTools.cs
https://jira.unity3d.com/browse/CMCL-514
We checked for ids with a hack. Now the ids can be tracked correctly for each handle (unity version 2022.2.0a9 and above), so we use that instead.
******************
EDIT: EXPLANATION
Handles have an id with which we can check if the handle is picked or hovered.
The "hack" version was needed, because there was no exposed API for some of the handles to get the handle's id, or to set the handle's id on creation. The "hack" version checked the last used id with this call: `GUIUtility.GetControlID(FocusType.Passive)`, before creating the handle, and after creating the handle. This way, I knew that the created handle should be between beforeID and afterID. The reason why I needed a range, because handles are created on threads (so I had cases when …
> CMCL-514: Hovering and knowing which handles are picked/dragged

- com.unity.cinemachine/Editor/Editors/CinemachineComposerEditor.cs
- com.unity.cinemachine/Editor/Editors/CinemachineFramingTransposerEditor.cs
- com.unity.cinemachine/Editor/PropertyDrawers/LensSettingsPropertyDrawer.cs
- com.unity.cinemachine/Editor/Utility/CmCameraInspectorUtility.cs
- Screen guides were not being drawn for CmCameras.  Fixed.
- Greyed out lens collapsed label to make it less weird.
- Added warning icons to CmCamera inspector when components are disabled or invalid:
> CMCL-0000: fixed screenguides drawing, added warning icons to CmCamera inspector

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Editor/Experimental/CmCameraEditor.cs
- com.unity.cinemachine/Editor/PostProcessing/CinemachineAutoFocusEditor.cs
- com.unity.cinemachine/Editor/PostProcessing/CinemachineAutoFocusEditor.cs.meta
- com.unity.cinemachine/Editor/PostProcessing/CinemachinePostProcessingEditor.cs
- com.unity.cinemachine/Editor/PostProcessing/CinemachineVolumeSettingsEditor.cs
- com.unity.cinemachine/Editor/PropertyDrawers/CameraPriorityPropertyDrawer.cs
- com.unity.cinemachine/Editor/PropertyDrawers/LensSettingsPropertyDrawer.cs
- com.unity.cinemachine/Editor/Upgrader/CinemachineUpgrader.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineBrain.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachinePixelPerfect.cs
- com.unity.cinemachine/Runtime/Core/LensSettings.cs
- com.unity.cinemachine/Runtime/PostProcessing/CinemachineAutoFocus.cs
- com.unity.cinemachine/Runtime/PostProcessing/CinemachineAutoFocus.cs.meta
- com.unity.cinemachine/Runtime/PostProcessing/CinemachineVolumeSettings.cs
- com.unity.cinemachine/Runtime/PostProcessing/FocusDistance.compute
- com.unity.cinemachine/Runtime/PostProcessing/FocusDistance.compute.meta
- com.unity.cinemachine/Runtime/PostProcessing/FocusDistance.cs
- com.unity.cinemachine/Runtime/PostProcessing/FocusDistance.cs.meta
CMCL-1000: AutoFocus extension and move focusDistance to camera (HDRP-only)
- Added FocusDistance setting to lens
- New AutoFocus extension.  Use instead of VolumeSettings for Focus Tracking.  Includes Automatic mode that queries depth buffer instead of tracking a specific target.
Low
HDRP is required for this.
Should test also with non-HDRP to make sure nothing has broken.
Implementation of Automatic focus is a little tricky: it requires a Custom Pass in rendering that runs a compute shader.  This pass is installed in a dynamically-created DontSave component on the main camera, and is enabled/disabled according to how many …
> CMCL-1000: Focus Distance and AutoFocus

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Behaviours/CinemachineFreeLook.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineVirtualCamera.cs
- com.unity.cinemachine/Runtime/Experimental/CinemachineNewFreeLook.cs
- com.unity.cinemachine/Runtime/Experimental/CinemachineNewVirtualCamera.cs
https://jira.unity3d.com/browse/CMCL-1003
- When not physical camera, sensor size is 0,0. We achieve with before serialize callback.
> CMCL-1003: Sensor size does not affect source control when not using physical camera

- com.unity.cinemachine/Editor/Upgrader/CinemachineUpgrader.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachinePixelPerfect.cs
https://jira.unity3d.com/browse/CMCL-1004
Code clean up, and
Bug fixes/features found by upgrading Gigaya project:
- Disabled components and gameobjects were not found in all cases.
- Prefabs are only searched for inside the Assets folder.
- Option for user to add scenes to ignore - this will come handy in UI. Scenes with corrupted prefab instances (e.g. prefab instance with a missing prefab source,  prefab instance with a missing script...) cannot be opened, and thus cannot be upgraded.
TODO:
- Gracefully handle scenes, prefabs and prefabs instances that are corrupted (e.g. missing scripts). For example, in the initialization phase, when caching scenes and prefab sources, list corrupted data for the user telling upgrader can't proceed until they are done.
> CMCL-1004: test upgrader on Gigaya 

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Documentation~/CinemachineBrainProperties.md
- com.unity.cinemachine/Editor/PropertyDrawers/LensSettingsPropertyDrawer.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineBrain.cs
CMCL-270: Lens mode override is confusing
Problem: when a vcam implements a lens mode override, it changes the main camera lens, so that subsequent vcams without a mode override will use the prior overridden mode, so the lens a vcam gets will depend on vcam activation order.  That's bad.
The PR adds a default lens mode to the CM brain, so that vcams without a mode override will get that default lens. 
low
> CMCL-270: Added Lens Mode Override enable/disable to Brain, with default mode

- com.unity.cinemachine/Editor/Utility/InspectorUtility.cs
Quick fix for laggy editor described here: https://github.com/Unity-Technologies/com.unity.cinemachine/issues/486 …
> Reduce amount of redundant calls to RepaintAllViews

- com.unity.cinemachine/CHANGELOG.md
Missing changelog added for https://github.com/Unity-Technologies/com.unity.cinemachine/pull/487
> CMCL-0000: added changelog for redundant view repaints

- com.unity.cinemachine/Editor/Editors/CinemachineRotationComposerEditor.cs
- com.unity.cinemachine/Editor/PropertyDrawers/LensSettingsPropertyDrawer.cs
- com.unity.cinemachine/Editor/Upgrader/UpgradeObjectForCm3.cs
- com.unity.cinemachine/Editor/Utility/ReflectionHelpers.cs
- com.unity.cinemachine/Editor/Utility/SerializedPropertyHelper.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineFreeLookModifier.cs
- com.unity.cinemachine/Runtime/Core/CinemachinePropertyAttribute.cs
- com.unity.cinemachine/Runtime/Core/LensSettings.cs
- Lens property drawer: take override mode out of advanced foldout.  Display warning only when necessary
- Rotation composer editor: remove evil refresh hack
- Bugfix: Lens FreeLook modifier was not observing lens override mode of vcam
> CMCL-0000: Remove advanced foldout from lens

- com.unity.cinemachine/Editor/Editors/CinemachineBasicMultiChannelPerlinEditor.cs
- com.unity.cinemachine/Editor/Upgrader/UpgradeObjectForCm3.cs
- com.unity.cinemachine/Runtime/Components/CinemachineBasicMultiChannelPerlin.cs
- com.unity.cinemachine/Runtime/Components/CinemachineHardLockToTarget.cs
- com.unity.cinemachine/Runtime/Components/CinemachineSameAsFollowTarget.cs
CMCL-896 part of API clenup.  Remove m_  from public members of remaining CM component classes
> CMCL-896: remove m_ from public component members

- com.unity.cinemachine/Editor/Editors/CinemachineBlenderSettingsEditor.cs
- com.unity.cinemachine/Editor/Editors/CinemachineBrainEditor.cs
- com.unity.cinemachine/Editor/Editors/CinemachineColliderEditor.cs
- com.unity.cinemachine/Editor/Editors/CinemachinePositionComposerEditor.cs
- com.unity.cinemachine/Editor/Helpers/CinemachineTriggerActionEditor.cs
- com.unity.cinemachine/Editor/PostProcessing/CinemachinePostProcessingEditor.cs
- com.unity.cinemachine/Editor/PostProcessing/CinemachineVolumeSettingsEditor.cs
- com.unity.cinemachine/Editor/Timeline/CinemachineShotClipEditor.cs
- com.unity.cinemachine/Editor/Timeline/CinemachineShotEditor.cs
- com.unity.cinemachine/Editor/Upgrader/CinemachineUpgrader.cs
- com.unity.cinemachine/Runtime/Behaviours/Cinemachine3rdPersonAim.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineBrain.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineClearShot.cs
- com.unity.cinemachine/Runtime/Core/CinemachineBlend.cs
- com.unity.cinemachine/Runtime/Core/ICinemachineCamera.cs
- com.unity.cinemachine/Runtime/Core/TargetPositionCache.cs
- com.unity.cinemachine/Runtime/PostProcessing/CinemachinePostProcessing.cs
- com.unity.cinemachine/Runtime/PostProcessing/CinemachineVolumeSettings.cs
- com.unity.cinemachine/Runtime/Timeline/CinemachineMixer.cs
- com.unity.cinemachine/Runtime/Timeline/CinemachineShot.cs
- com.unity.cinemachine/Runtime/Timeline/CinemachineShotPlayable.cs
- com.unity.cinemachine/Runtime/Timeline/CinemachineTrack.cs
CMCL-1066: Cleanup more API
- Remove ICinemachineCamera.Priority accessor
- Remove ICinemachineCamera.VirtualCameraGameObject accessor
- CinemachinePostProcessing m_ fixup members
- CinemachineVolumeSettings m_ fixup members
- All CM Timeline code moved into Cinemachine and Cinemachine.Editor namespaces
This PR was also meant to include the 9611dc84 commit, which was accidentally pushed to master
> CMCL-1066: Cleanup ICinemachineCamera API

- CHANGELOG.md
- Editor/Utility/InspectorUtility.cs
- Editor/Utility/SaveDuringPlay.cs
- Runtime/Behaviours/CinemachineBrain.cs
- Runtime/Behaviours/CinemachineConfiner.cs
- Runtime/Behaviours/CinemachineFreeLook.cs
- Runtime/Behaviours/CinemachineVirtualCamera.cs
- Runtime/Components/CinemachinePOV.cs
- Runtime/Core/CinemachineCore.cs
- Runtime/Core/CinemachineVirtualCameraBase.cs
- Runtime/Experimental/CinemachineNewFreeLook.cs
- Runtime/Experimental/CinemachineNewVirtualCamera.cs
- Runtime/PostProcessing/CinemachineVolumeSettings.cs
- Samples~/Cinemachine Example Scenes/Scenes/FadeOutNearbyObjects/FadeOut.shader
- ValidationExceptions.json
- package.json
> CMCL-969: Release 2.8.7

- com.unity.cinemachine/Editor/Upgrader/UpgradeObjectForCm3.cs
CMCL-1083 - ReplaceComponent only replaces exact type matches
> CMCL-1083: ReplaceComponent only replaces exact type matches

- com.unity.cinemachine/Runtime/Components/CinemachineOrbitalFollow.cs
- com.unity.cinemachine/Runtime/Components/CinemachinePanTilt.cs
https://jira.unity3d.com/browse/CMCL-1086
InputAxis needed [SerializeReference], because it's a class, for recording to work on AnimationTracks
> CMCL-1086: InputAxis is not recordable

- com.unity.cinemachine/Editor/Upgrader/CinemachineUpgrader.cs
CMCL-1080
Timeline references were not updated correctly, because ExposedReferences values could be the same for different PlayableDirectors. ExposedReferences are only unique when paired with their PlayableDirector. 
I am thinking about using the strategy used here for ConversionLink:
`manager.MakeTimelineNamesUnique(out var renames);  ` 
--> Make all vcams, prefabs, prefabInstances unique at start -> then we can just use their name -> Then restore names at the end.
> CMCL-1080: Update timeline references

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Editor/Editors/CinemachineBrainEditor.cs
- com.unity.cinemachine/Editor/Editors/CinemachineClearShotEditor.cs
- com.unity.cinemachine/Editor/Utility/InspectorUtility.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineClearShot.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineCollider.cs
- com.unity.cinemachine/Runtime/Core/IShotQualityEvaluator.cs
- com.unity.cinemachine/Runtime/Core/IShotQualityEvaluator.cs.meta
CMCL-582: Add IShotQualityEvaluator.
- Implemented by CinemachineCollider
- ClearShot no longer depends on UNITY_PHYSICS
- Possibility for alternate shot quality evaluation oimplementations (make a custom extension that implements IShotQualityEvaluator)
low
> CMCL-582: Add IShotQualityEvaluator

- com.unity.cinemachine/package.json
https://jira.unity3d.com/browse/CMCL-1120
- Forward-port from [2.9.0-prep](https://github.com/Unity-Technologies/com.unity.cinemachine/pull/511) branch. 
- This dependency is needed for isolation tests to not fail in editor versions 2022 and above, when promoting releases (just like https://github.com/Unity-Technologies/com.unity.cinemachine/pull/523).
We could also make `com.unity.test-framework` an optional dependency  by adding #if CINEMACHINE_TESTFRAMEWORK to all our tests. Consequently disabling tests in isolation tests.
> CMCL-1120: NUnit dependency - testframework

- com.unity.cinemachine/Runtime/Components/CinemachineSameAsFollowTarget.cs
- com.unity.cinemachine/Runtime/Core/CameraState.cs
CMCL-1146: Revisit cases CMCL-315 and CMCL-406.  
Original fixes introduced a regression and were reverted.
Please see the 4 repro cases in the jira ticket.
low
> CMCL-1146: re-implement blending fixes for CMCL-315 and CMCL-406

- .yamato/metadata.metafile
- CHANGELOG.md
- Editor/Editors/CinemachineStateDrivenCameraEditor.cs
- Editor/Menus/CinemachineMenu.cs
- Editor/com.unity.cinemachine.Editor.asmdef
- Runtime/Behaviours/CinemachineStateDrivenCamera.cs
- Runtime/Components/CinemachineSameAsFollowTarget.cs
- Runtime/Core/CameraState.cs
- Runtime/Core/CinemachineCore.cs
- Runtime/com.unity.cinemachine.asmdef
- Samples~/Cinemachine Example Scenes/Scenes/AimingRig/AimReticle.cs
- Samples~/Cinemachine Example Scenes/Scenes/AimingRig/AimingRig.asmdef
- Samples~/Cinemachine Example Scenes/Scenes/AimingRig/AimingRig.asmdef.meta
- package.json
The rest of the issues in the changelog where verified in the [2.6.16 PR](https://github.com/Unity-Technologies/com.unity.cinemachine/pull/477).
> CMCL-1131: release prep for 2.6.17

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Behaviours/CinemachineCollider.cs
- com.unity.cinemachine/Runtime/Components/CinemachinePOV.cs
CMCL-1057 (has repro project)
When the FreeLook rigs were extreme the collider damping was not handled correctly, causing the camera to move incorrectly in depth, sometimes overshooting the character.
Solution was to redesign collider damping to use the previous camera position, and to set state.DampingBypass to account for its displacement, eliminating spurious rotation damping in the composer.
The new solution works with all collider strategies.
This fix should be backported to 2.6, 2.8, and 3.0
low
> CMCL-1057: collider damping was not robust

- .yamato/metadata.metafile
- .yamato/package-publish.yml
Unity 2018.4 doesn't support soft dependencies, therefore isolation tests cannot pass and block the package's publishing. This runs only the vetting tests, which are sufficient to publish the package. This also adds an handy dry-run variable. 
I tried a publishing dry-run on my branch and it works. 
0
This is not the cleanest way of doing things, but support of 2.6 will soon end.
> CMCL-1131: Publish 2.6 release without running isolation tests

- com.unity.cinemachine/Runtime/Core/ConfinerOven.cs
- com.unity.cinemachine/Runtime/ThirdParty/clipper.cs
CMCL-1170 CLipperLib was accidentally added to the public API, enlarging the footprint.  Should be internal.  This is a release blocker.
** Needs to be backported to 2.6, 2.8, and 2.9 **
> CMCL-1170: make ClipperLib internal

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Behaviours/CinemachineBlendListCamera.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineClearShot.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineExternalCamera.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineStateDrivenCamera.cs
- com.unity.cinemachine/Runtime/Behaviours/CmCamera.cs
- com.unity.cinemachine/Runtime/Core/CinemachineCameraManagerBase.cs
- com.unity.cinemachine/Runtime/Core/CinemachineVirtualCameraBase.cs
- com.unity.cinemachine/Runtime/Deprecated/CinemachineFreeLook.cs
- com.unity.cinemachine/Runtime/Deprecated/CinemachineVirtualCamera.cs
CMCL-651: backport to CM3, remove hack
low
> CMCL-651: state driven camera transition glitch 

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Behaviours/CinemachineFreeLook.cs
CMCL-1165
low
Needs to be backported to 2.6 and 2.8
> CMCL-1165: 1 frame freelook transition glitch

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Core/CinemachineVirtualCameraBase.cs
CMCL-651
Low
Actual fix involves a hack to avoid changing the API.
Needs to be ported to 3.0, 2.8, and (optionally) 2.6.
The 3.0 fix should get rid of the hack.
> CMCL-651: state driven camera transition glitch when the camera is changed during the transition

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Behaviours/CinemachineBrain.cs
- com.unity.cinemachine/Runtime/Core/LensSettings.cs
- com.unity.cinemachine/Runtime/com.unity.cinemachine.asmdef
CMCL-1175: In HDRP 14, physical settings were moved from HDAdditionalCameraData to Camera class.
L:ow
> CMCL-1175: support hdrp 14 (unity 2022.2)

- com.unity.cinemachine/Editor/Upgrader/CinemachineUpgradeManager.cs
- com.unity.cinemachine/Editor/Utility/ReflectionHelpers.cs
- Prefab instance modification for manager cameras need to be recorded (otherwise the instructions for StateDriveCamera are lost).
- When an old vcam is added to a Prefab instance, it was not upgraded.
- rootObjects may contain nulls, because converted copies are now deleted.
TODO: Statedrivecamera loses references if they are changed in prefab instance.
> CMCL-0000: Prefab instance modification fixes

- com.unity.cinemachine/Editor/PostProcessing/CinemachineAutoFocusEditor.cs
- com.unity.cinemachine/Editor/Utility/InspectorUtility.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineExternalCamera.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineMixingCamera.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineTargetGroup.cs
- com.unity.cinemachine/Runtime/Behaviours/CmCamera.cs
- com.unity.cinemachine/Runtime/Core/CameraState.cs
- com.unity.cinemachine/Runtime/Core/CinemachineCameraManagerBase.cs
- com.unity.cinemachine/Runtime/Core/CinemachineVirtualCameraBase.cs
- com.unity.cinemachine/Runtime/Deprecated/CinemachineFreeLook.cs
- com.unity.cinemachine/Runtime/Deprecated/CinemachinePathBase.cs
- com.unity.cinemachine/Runtime/Deprecated/CinemachineVirtualCamera.cs
- com.unity.cinemachine/Runtime/Impulse/CinemachineCollisionImpulseSource.cs
Added docs based on this report: https://yamato-artifactviewer.prd.cds.internal.unity3d.com/759bf7a1-6c2a-454c-a8a8-556226f16069%2Fpvp%2Fupm-ci~%2Fpvp/com.unity.cinemachine.json.
In some places, I changed the access modifier of the function/property that was missing docs.
> CMCL-1182: missing docs

- com.unity.cinemachine/Runtime/Behaviours/CinemachineStoryboard.cs
Fixed #if for UGUI, because UnityEngine is needed for AddComponent and MonoBehaviour at the bottom.
> CMCL-0000: UGUI #if was at the wrong place

- .yamato/package-validation.yml
Add API docs validation test to Cinemachine CI.
[CMCL-1174](https://jira.unity3d.com/browse/CMCL-1174) CI: Add API docs validation test to Cinemachine
- The test job is [here](https://unity-ci.cds.internal.unity3d.com/job/16606034/logs) and this is [the test result](https://yamato-artifactviewer.prd.cds.internal.unity3d.com/759bf7a1-6c2a-454c-a8a8-556226f16069%2Fpvp%2Fupm-ci~%2Fpvp/com.unity.cinemachine.json) (see errors section).
- API docs validation test is similar to true isolation test. When I added the test, I met different script compilation errors. In order to workaround them, I need to add …
> CMCL-1174: Add api docs validation to Cinemachine

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Core/AxisState.cs
CMCL-837: AxisState needs to apply deltaTime for all input.  When using mouse delta input, client is responsible for scaling the input value by 1/deltaTime.  In new input system, this can be done with a binding processor.  In legacy input, this can be done with a custom delegate for CinemachineCore.GetInputAxis.  There is no way to just make this work out of the box for all input devices.
> CMCL-837: input speed is affected by FPS

- CHANGELOG.md
- Runtime/Components/CinemachinePOV.cs
CMCL-679: when a vcam with POV becomes live, it should start up in its centered state, if recentering is enabled.  It was starting always at 0 then recentering.
- [m] Manually tested 
low
> CMCL-679: pov centers at startup

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Behaviours/CinemachineBrain.cs
CMCL-936 Only affects recorder.  When recording with accumulation buffer, camera matrix gets overridden.  Fix is to reset the camera matrix before setting the camera's lens.
low
> CMCL-936: reset projection matrix

- com.unity.cinemachine/Editor/Menus/CinemachineMenu.cs
Users can create a third person aim camera using the targeted camera option.
They don't get controls over it though.
> CMCL-0000: Added 3rdPerson aim camera to targeted cameras

- com.unity.cinemachine/Editor/Menus/CinemachineMenu.cs
- com.unity.cinemachine/Editor/PropertyDrawers/CameraTargetPropertyDrawer.cs
Experiment: add Targeted Cameras menu group.
When you right-click on a GameObject and select one of the Targeted Camera options, it will create the camera as a sibling of the clicked-on thing and then automatically populate the Tracking Target with that thing.  So, right-click on Player, then select FreeLook camera and you have a FreeLook tracking the player, ready to go.
> CMCL-0000: add targeted cameras menu group

- com.unity.cinemachine/Runtime/Behaviours/CinemachineBrain.cs
- com.unity.cinemachine/Runtime/Core/LensSettings.cs
We could not change to physical camera, because of ResetProjectionMatrix.
Guillaume noted in the bug dojo:
The physical sensor size is set to 1 mm by default. Should we have a 35 mm default instead?
What should we do about it?
> CMCL-0000: Physical camera fix

- com.unity.cinemachine/Samples~/Sample Scenes/Shared/Cameron/Model/CameronSimpleController.controller
Fix stale text references in AnimationControlller.
There is still a Removing null node error when enterring playmode. I have asked devs-editor why this could happen, because the error is thrown there. This happens on master branch.
> CMCL-0000: Stale text based reference in AnimationController [CinemachineTestingDojo]

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Editor/Editors/CinemachinePositionComposerEditor.cs
- com.unity.cinemachine/Editor/Editors/CinemachineRotationComposerEditor.cs
- com.unity.cinemachine/Editor/Obsolete/CinemachineComposerEditor.cs
- com.unity.cinemachine/Editor/Obsolete/CinemachineFramingTransposerEditor.cs
- com.unity.cinemachine/Editor/Utility/CinemachineScreenComposerGuides.cs
- com.unity.cinemachine/Editor/Utility/CmCameraInspectorUtility.cs
- com.unity.cinemachine/Runtime/Components/CinemachinePositionComposer.cs
- com.unity.cinemachine/Runtime/Components/CinemachineRotationComposer.cs
- com.unity.cinemachine/Runtime/Core/ScreenComposerSettings.cs
- com.unity.cinemachine/Runtime/Deprecated/CinemachineComposer.cs
- com.unity.cinemachine/Runtime/Deprecated/CinemachineFramingTransposer.cs
Make the Game View Guides UX (inspector and on-screen) clearer.
New inspector:
This adds the functionality of having no hard limits, which used to be implemented separately in Position Composer, now it works natively for both.
Added "Draggable" toggle for game view guides to turn off interactivity (option already existed in preferences):
Added highlighting of "hot" draggable thing in the game view (the thing under the  mouse).
Note: user documentation needs to be updated, will do it in separate PR
low
> CMCL-0000: Dev/screen composition ux refactor

- com.unity.cinemachine/Runtime/Behaviours/CinemachineGroupFraming.cs
- com.unity.cinemachine/Runtime/Deprecated/CinemachineFramingTransposer.cs
Old FramingTransposer has a bug probably. It is not tracking the TargetGroup. It also modifies the Camera's Z value by -1. New one is tracking the TargetGroup position correctly. So I think the new one is correct, the old one has a bug.
What do you think? I send you a project where you can test it easily to see.
> CMCL-0000: GroupFraming is different in old and new  [CinemachineTestingDojo]

- .yamato/package-validation.yml
- pvp_api_doc_exemptions.json
Exempt some API doc missing errors for Cinematic's API doc validation CI job. 
Some of the errors are false alarm, for example PVP complains private and protected methods miss doc, This is incorrect.
This PR is to filter out these noises.
[CMCL-1174](https://jira.unity3d.com/browse/CMCL-1174) CI: Add API docs validation test to Cinemachine
> CMCL-1174: Exempt some API doc missing errors

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/package.json
The validation test suite was failing because we had an unreleased changelog entry. Let's take this opportunity to review the 3.0.0-pre.2 changelog in case we want to change something.
> CMCL-0000: Add the version to the last changelog entry

- .yamato/package-ci.yml
- .yamato/package-promotion.yml
- .yamato/package-publish.yml
The projects are unreliable at the moment. Until we fix them, I'm disabling them from the tests running on PR and from the publishing pipeline. 
Also, this PR runs the the doc validation job on PRs and at night.
> CMCL-0000: Remove project tests from the PR pipeline and the publishing pipeline

- com.unity.cinemachine/Editor/Editors/InputAxisControllerEditor.cs
- com.unity.cinemachine/Editor/PropertyDrawers/FoldoutWithEnabledButtonPropertyDrawer.cs
- com.unity.cinemachine/Runtime/Core/ScreenComposerSettings.cs
Remove some hacks, thanks to code from Damian Campeanu.
Also small bugfix: disabled hard guides were hot-highlighting at top/left screen edges.
Another small bugfix: bad indent in InputAxisController inspector if both input systems present
> CMCL-0000: Cleanup FoldoutWithEnabledButtonPropertyDrawer

- com.unity.cinemachine/Editor/Editors/CinemachineBlendListCameraEditor.cs
- com.unity.cinemachine/Editor/Editors/CinemachineClearShotEditor.cs
- com.unity.cinemachine/Editor/Editors/CinemachineExternalCameraEditor.cs
- com.unity.cinemachine/Editor/Editors/CinemachineMixingCameraEditor.cs
- com.unity.cinemachine/Editor/Editors/CinemachineStateDrivenCameraEditor.cs
- com.unity.cinemachine/Editor/Editors/CinemachineVirtualCameraBaseEditor.cs
- com.unity.cinemachine/Editor/Editors/CmCameraEditor.cs
- com.unity.cinemachine/Editor/PropertyDrawers/FoldoutWithEnabledButtonPropertyDrawer.cs
- com.unity.cinemachine/Editor/Utility/CmCameraInspectorUtility.cs
- com.unity.cinemachine/Editor/Utility/InspectorUtility.cs
- com.unity.cinemachine/Runtime/Behaviours/CmCamera.cs
- com.unity.cinemachine/Runtime/Core/CinemachinePropertyAttribute.cs
- com.unity.cinemachine/Runtime/Core/CinemachineVirtualCameraBase.cs
Added "(using default)" text next to Priority And Channel when disabled.
Made some inspectors more consistent (reordered fields).
Fixed up IMGUI inspectors to have dropdown for game view guides
Put global controls on one line (let's see how it feels).
> CMCL-0000: add "using default" text to priority inspector

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Editor/PropertyDrawers/SplineAutoDollyPropertyDrawer.cs
- com.unity.cinemachine/Runtime/Components/CinemachinePositionComposer.cs
- com.unity.cinemachine/Runtime/Components/CinemachineRotationComposer.cs
- com.unity.cinemachine/Runtime/Core/Predictor.cs
- com.unity.cinemachine/Runtime/Deprecated/CinemachineComposer.cs
- com.unity.cinemachine/Runtime/Deprecated/CinemachineFramingTransposer.cs
Rotation composer lookahead sometimes popped without apparent reason
Also a little cleanup here and there.
low
Was visible in simple car sample when you drive in a circle
> CMCL-0000: bugfix: rotation composer lookahead was wrong

- com.unity.cinemachine/Editor/Editors/CmCameraEditor.cs
- com.unity.cinemachine/Editor/PropertyDrawers/LensSettingsPropertyDrawer.cs
- com.unity.cinemachine/Editor/Utility/InspectorUtility.cs
- com.unity.cinemachine/Runtime/Core/CinemachineVirtualCameraBase.cs
- com.unity.cinemachine/Runtime/Core/LensSettings.cs
1. GC allocs every frame (editor only, but it was very distracting and alarming) when getting UnseHorizontalFOV setting.
2. GC allocs accessing vcam name when looking up blends.  Vcams now cache their names.
> CMCL-0000: Remove some GC allocs

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Editor/PropertyDrawers/LensSettingsPropertyDrawer.cs
- com.unity.cinemachine/Editor/Utility/GameViewComposerGuides.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineBrain.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineFreeLookModifier.cs
- com.unity.cinemachine/Runtime/Core/CinemachineVirtualCameraBase.cs
- com.unity.cinemachine/Runtime/Core/LensSettings.cs
CMCL-1244
- camera.focalLength was not being set
- gateFit, sensorSize, lensShift were not settable from inspector when mode override is none
- dragging focalLength setting in inspector has weird wraparound when dragged past 0
low
> CMCL-1244: physical lens settings not properly applied

- CHANGELOG.md
- Runtime/Behaviours/CinemachineBrain.cs
[CMCL-1240](https://jira.unity3d.com/browse/CMCL-1240): Focal length is not set by Cinemachine. We only set field of view, but that value is overwritten and we need to set focal length instead.
> CMCL-1242: Fix for 2.8.X: Focal Length is not set by CM

- com.unity.cinemachine/Editor/Editors/CmCameraEditor.cs
- com.unity.cinemachine/Editor/Editors/InputAxisControllerEditor.cs
- com.unity.cinemachine/Editor/Utility/CmCameraInspectorUtility.cs
Recentering defaulted to enabled(0, 0) in input axis controller.  Changed to something more reasonable.
Also separated Global Controls back into 2 lines.  Single-line version was weird.
> CMCL-0000: fix recentering defaults

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Behaviours/CinemachineBrain.cs
CMCL-1250: Could not set main camera to physical mode while a vcam with ModeOverride = None was active
low
> CMCL-1250: cannot set physical camera

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Behaviours/CinemachineBrain.cs
[CMCL-1240](https://jira.unity3d.com/browse/CMCL-1240): Focal length is not set by Cinemachine. We only set field of view, but that value is overwritten and we need to set focal length instead.
> CMCL-1241:  Fix for 2.9.X: Focal Length is not set by CM

- com.unity.cinemachine/Runtime/Behaviours/CinemachineDeoccluder.cs
- com.unity.cinemachine/Runtime/Components/CinemachineOrbitalFollow.cs
- com.unity.cinemachine/Runtime/Components/CinemachinePanTilt.cs
- com.unity.cinemachine/Runtime/Components/CinemachineRotationComposer.cs
- com.unity.cinemachine/Runtime/Core/CameraState.cs
- com.unity.cinemachine/Runtime/Core/UnityVectorExtensions.cs
- com.unity.cinemachine/Runtime/Deprecated/CinemachineComposer.cs
- com.unity.cinemachine/Runtime/Deprecated/CinemachineOrbitalTransposer.cs
- com.unity.cinemachine/Runtime/Deprecated/CinemachinePOV.cs
Damping bypass was reimplemented as a quaternion instead of euler.
Also, algorithm was improved to help reduce spurious rotation damping when a nonzero lookAt target offset was used.
> CMCL-0000: Damping bypass refactor

- com.unity.cinemachine/Editor/Upgrader/UpgradeObjectToCm3.cs
SmoothPath was not upgraded properly. It was upgraded to a linear spline, now it is upgraded to a smooth spline (not identical to SmoothPath, but close enough).
> CMCL-0000: SmoothPath upgrade fix

- com.unity.cinemachine/Editor/Upgrader/UpgradeObjectToCm3.Data.cs
- com.unity.cinemachine/Runtime/Components/CinemachineOrbitalFollow.cs
- com.unity.cinemachine/Runtime/Components/CinemachinePanTilt.cs
- com.unity.cinemachine/Runtime/Core/InputAxis.cs
- com.unity.cinemachine/Runtime/Helpers/InputAxisController.cs
- com.unity.cinemachine/Samples~/3D Samples/FreeLook deoccluder.unity
- com.unity.cinemachine/Samples~/Shared Assets/Scripts/SimpleCarController.cs
- com.unity.cinemachine/Samples~/Shared Assets/Scripts/SimplePlayerAimController.cs
- com.unity.cinemachine/Samples~/Shared Assets/Scripts/SimplePlayerController.cs
- com.unity.cinemachine/Samples~/Shared Assets/Scripts/SimplePlayerShoot.cs
- com.unity.cinemachine/Tests/Editor/InputAxisTests.cs
We were getting serialization problems because InputAxis was a class and required [SerializedReference] to work with animator.  Changing it to a struct solves that.
low
> CMCL-0000: InputAxis is now a struct

- com.unity.cinemachine/Editor/Editors/CinemachineBrainEditor.cs
- com.unity.cinemachine/Editor/PropertyDrawers/InputAxisPropertyDrawer.cs
- com.unity.cinemachine/Editor/PropertyDrawers/LensSettingsPropertyDrawer.cs
- com.unity.cinemachine/Editor/Utility/EmbeddedAssetHelpers.cs
- com.unity.cinemachine/Editor/Utility/InspectorUtility.cs
Input axis foldout collapsed when you unchecked the "wrap" property.  I thought this was a UITK bug, but it was our bug.  The issue was that we we not properly filtering the ValueChanged<bool> events in the foldout handlers.
> CMCL-0000: fix foldout collapse state bug

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/ValidationExceptions.json
- com.unity.cinemachine/package.json
Bump the version to 2.9.4. I accidentally burned the 2.9.3 version by publishing from the wrong branch and then doing a squash merge. I prefer to burn a patch version than to have the discrepancy. 
Ran a successful publishing dry-run.
> Prepare to publish 2.9.4 candidate

- com.unity.cinemachine/Editor/Upgrader/CinemachineUpgradeManager.cs
No hang on pop-up message. No need to initialize PrefabManager which is slow, because it sorts prefab based on nestedness.
> CMCL-0000: No need to initialize prefab manager just to check prefabs

- com.unity.cinemachine/Editor/Upgrader/CinemachineUpgradeManager.cs
- com.unity.cinemachine/Editor/Upgrader/UpgradeObjectToCm3.cs
- com.unity.cinemachine/Runtime/Core/CinemachineVirtualCameraBase.cs
When upgrading a scene with managers (e.g. ClearShot sample) the scene breaks after the upgrade because managers are still holding references to the deleted children.  Fix this.
Also: don't init prefab manager when upgrading scene.
> CMCL-0000: invalidate manager parents when upgrading vcams

- com.unity.cinemachine/Editor/Editors/CinemachineFreeLookModifierEditor.cs
- com.unity.cinemachine/Editor/Editors/CinemachineVirtualCameraBaseEditor.cs
- com.unity.cinemachine/Editor/Obsolete/VcamStageEditor.cs
- com.unity.cinemachine/Editor/PropertyDrawers/EmbeddedAssetPropertyDrawer.cs
- com.unity.cinemachine/Editor/PropertyDrawers/SplineAutoDollyPropertyDrawer.cs
- com.unity.cinemachine/Editor/Utility/CmCameraInspectorUtility.cs
- com.unity.cinemachine/Editor/Utility/InspectorUtility.cs
- com.unity.cinemachine/Runtime/Deprecated/CinemachineCollider.cs
Make sure obsolete classes don't appear in UX unless explicitly wanted
> CMCL-0000: don't show obsolete classes in UX helpers

- com.unity.cinemachine/CHANGELOG.md
We run the isolation tests at night, to make sure that the package could be promoted at any time. For example, it checks that the samples can be loaded, and that we follow semver rules. Right now, those tests fail because we cannot release a package with a changelog entry that says "Unreleased". Having that changelog entry makes sense because it's accurate, but there is more value in  having the tests fail if for example, we introduced an API change without bumping the minor version.
Isolation tests passed
> CMCL-0000: Change unreleased changelog with next version so that promotion tests pass

- com.unity.cinemachine/Samples~/3D Samples/ThirdPerson Shooter.unity
- com.unity.cinemachine/Samples~/Shared Assets/Scripts/SimplePlayerAimController.cs
- com.unity.cinemachine/Samples~/Shared Assets/Scripts/SimplePlayerController.cs
Fix weird rotation in third person sample when moving and rotating past +z axis.
Also: add LockCursor option to character controller, enable it in ThirdPersonShooter.
> CMCL-0000: fix sample player rotation

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Behaviours/CinemachineTargetGroup.cs
CMCL-1277: TargetGroup should ignore inactive members.
Inactive targets should be treated as though they have zero weight.
low
> CMCL-1277: TargetGroup pays attention to member active state

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Behaviours/CinemachineTargetGroup.cs
CMCL-1279: TargetGroup should ignore inactive group members
low
> CMCL-1279: target group inactive members 2.9

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Editor/Upgrader/UpgradeObjectToCm3.cs
[CMCL-1283](https://jira.unity3d.com/browse/CMCL-1283): SmoothPath should be upgraded correctly. 1 to 1 matching.
> CMCL-1283: Upgrade CinemachineSmoothPath to Splines with 1 to 1 matching

- README.md
Starting a ReadMe file to contain the branching strategy. With time, we can add more things to it like contribution rules. Note that having a readme file in a repo is technically required to ship a package at Unity, but Cinemachine had a grandfathered exception.
> CMCL-0000: Add readme with description and branching strategy

- com.unity.cinemachine/Editor/Samples/SampleDependencyImporter.cs
- com.unity.cinemachine/Samples~/samples.json
[CMCL-1294](https://jira.unity3d.com/browse/CMCL-1294)
Import dependency pop-up is only showed when a dependency is missing.
User has 3 options:
1. Import samples and its dependencies
Samples and **missing** dependencies are imported.
2. Import samples but not its dependencies
Samples are imported without dependencies.
---------------------------
**Removed option to abort samples**
Little hack: Samples cannot be stopped from importing, but we can delete it right away. Samples are not deleted if they were already in the user's project (e.g. they import without dependencies and click on reimport again and select Abort). Shared files are also not deleted if they were already there (e.g. user imported another sample that shared some files with the current import).
---------------------------
> CMCL-1294: Improve sample dependency importer pop-up window

- .yamato/project-pack.yml
- .yamato/project-test.yml
- Projects/HDRPInputSystem/Packages/manifest.json
- com.unity.cinemachine.hdrptests/Tests.meta
- com.unity.cinemachine.hdrptests/Tests/Editor.meta
- com.unity.cinemachine.hdrptests/Tests/Editor/IsHDRP.cs
- com.unity.cinemachine.hdrptests/Tests/Editor/IsHDRP.cs.meta
- com.unity.cinemachine.hdrptests/Tests/Editor/com.unity.cinemachine.hdrpeditor.tests.asmdef
- com.unity.cinemachine.hdrptests/Tests/Editor/com.unity.cinemachine.hdrpeditor.tests.asmdef.meta
- com.unity.cinemachine.hdrptests/Tests/Runtime.meta
- com.unity.cinemachine.hdrptests/Tests/Runtime/IsHDRP.cs
- com.unity.cinemachine.hdrptests/Tests/Runtime/IsHDRP.cs.meta
- com.unity.cinemachine.hdrptests/Tests/Runtime/com.unity.cinemachine.hdrp.tests.asmdef
- com.unity.cinemachine.hdrptests/Tests/Runtime/com.unity.cinemachine.hdrp.tests.asmdef.meta
- com.unity.cinemachine.hdrptests/Tests/com.unity.cinemachine.hdrp.tests.asmdef
- com.unity.cinemachine.hdrptests/Tests/com.unity.cinemachine.hdrp.tests.asmdef.meta
- com.unity.cinemachine.hdrptests/package.json
- com.unity.cinemachine.hdrptests/package.json.meta
- com.unity.cinemachine/.tests.json
- com.unity.cinemachine/Tests/.tests.json
- com.unity.cinemachine/Tests/Runtime/StateDrivenCameraTests.cs
Use the .tests.json method to extract the tests in a new package. This means that we won't deliver tests with the next version of cinemachine. 
We decided it's the least of the two evils, between creating an empty tests in the main package or using CI magic to do the split. 
Passed isolation tests. Package is still ready to release.
> CMCL-0000: Split tests in a separate package

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Deprecated/CinemachinePathBase.cs
[CMCL-1306](https://jira.unity3d.com/browse/CMCL-1306): CinemachinePathBase.FindClosestPoint doesn't search the last segment of its path when there are more than 2 segments.
The problem was that the search radius was clamped to half the radius, but when the path is not looped this may clamp the search radius too short.
For example:
Spline with n points. Not looped.
Search Radius: n. => search whole path even when starting from spline point 0.
However, search radius was clamped to n/2. So now we don't search whole spline just half when starting from 0.
> CMCL-1306: FindClosestPoint fix

- CHANGELOG.md
- Runtime/Core/CinemachinePathBase.cs
[CMCL-1321](https://jira.unity3d.com/browse/CMCL-1321), backport of [CMCL-1307](https://jira.unity3d.com/browse/CMCL-1307) - [PR](https://github.com/Unity-Technologies/com.unity.cinemachine/pull/708)
I saw we have a few unreleased fixes on 2.6, so I added this simple to backport fix, in case we want to release them.
> CMCL-1321: FindClosestPoint fix (#708)

- com.unity.cinemachine/Samples~/Shared Assets/Cameron/Model/CameronSimpleController.controller
- com.unity.cinemachine/Samples~/Shared Assets/Prefabs/Player.prefab
- com.unity.cinemachine/Samples~/Shared Assets/Scripts/SimplePlayerAnimator.cs
- com.unity.cinemachine/Samples~/Shared Assets/Scripts/SimplePlayerController.cs
Refactored Cameron animation controller:
- Animation now scales properly with speed, feet don't slide
- Clean transition from walk to run, depending on speed (no need to check IsSprinting in the controller)
- Works also without SimplePlayerController.  In this mode, transform position is monitored and velocity is calculated.  The appropriate animation is chosen, depending on speed and direction relative to local forward.  Jumping not supported in this mode.
Specify test plans. Rarely acceptable to have no testing.]
For the ClearShot racing scene, where player is on a cart, you can now leave the SimplePlayerAnimator script on the player, and remove the controller.  Player will animate automatically based on its speed.
> CMCL-0000: cameron animation scales properly with speed

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Components/CinemachinePanTilt.cs
- com.unity.cinemachine/Runtime/Deprecated/CinemachinePOV.cs
CMCL-1325: POV and PanTilt were not handling ReferenceUp correctly.
https://forum.unity.com/threads/regression-referenceup-no-longer-works-with-transpose.1378473/#post-8685612
Introduced in Jun/July 2022 by the fix for [CMCL-1005](https://jira.unity3d.com/browse/CMCL-1005)
> CMCL-1326: PanTilt/POV/ReferenceUp regression fix

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Components/CinemachinePOV.cs
CMCL-1325: POV was not handling ReferenceUp correctly.
https://forum.unity.com/threads/regression-referenceup-no-longer-works-with-transpose.1378473/#post-8685612
Introduced in Jun/July 2022 by the fix for [CMCL-1005](https://jira.unity3d.com/browse/CMCL-1005)
> CMCL-1328: pov referenceup regression fix for 2.9

- CHANGELOG.md
- Runtime/Components/CinemachinePOV.cs
CMCL-1325: POV was not handling ReferenceUp correctly.
https://forum.unity.com/threads/regression-referenceup-no-longer-works-with-transpose.1378473/#post-8685612
Introduced in Jun/July 2022 by the fix for [CMCL-1005](https://jira.unity3d.com/browse/CMCL-1005)
> CMCL-1329: pov referenceup regression fix for 2.6

- CHANGELOG.md
- Runtime/Components/CinemachinePOV.cs
CMCL-1325: POV was not handling ReferenceUp correctly.
https://forum.unity.com/threads/regression-referenceup-no-longer-works-with-transpose.1378473/#post-8685612
Introduced in Jun/July 2022 by the fix for [CMCL-1005](https://jira.unity3d.com/browse/CMCL-1005)
> CMCL-1327: pov referenceup regression fix for 2 8

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Core/CinemachineCore.cs
- com.unity.cinemachine/Tests/Runtime/PriorityTests.cs
- com.unity.cinemachine/Tests/Runtime/PriorityTests.cs.meta
[CMCL-1335](https://jira.unity3d.com/browse/CMCL-1335): Fix priority comparison bug
https://forum.unity.com/threads/bug-with-priority-in-update-loop.1379367/#post-8692113
Overflow was caused by the comparison functions subtraction. The overflow way is to use compare because it does extra checks to properly compare without overflow.
> CMCL-1335: Fix priority comparison overflow bug

- com.unity.cinemachine/Runtime/Behaviours/CinemachineBlendListCamera.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachinePath.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineSmoothPath.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineStateDrivenCamera.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineTargetGroup.cs
- com.unity.cinemachine/Runtime/Core/NoiseSettings.cs
Fixes some C# syntax that was invalid in unity editor 2019 and 2020
> CMCL-0000: C# syntax fixes in 2019 and 2020 - cm 2.9

- Projects/HDRP/Assets/Editor/InitializeTests.cs
- Projects/HDRP/Assets/Editor/UnitTestInitialization.asmdef
- Projects/HDRP/Assets/Editor/UnitTestInitialization.asmdef.meta
- com.unity.cinemachine/Editor/Editors/CinemachinePathEditor.cs
- com.unity.cinemachine/Editor/Menus/CinemachineMenu.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineBlendListCamera.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachinePath.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineSmoothPath.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineStateDrivenCamera.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineTargetGroup.cs
- com.unity.cinemachine/Runtime/Core/CinemachineVirtualCameraBase.cs
- com.unity.cinemachine/Runtime/Core/NoiseSettings.cs
- com.unity.cinemachine/Tests/Runtime/CamerasBlendingTests.cs
- com.unity.cinemachine/Tests/Runtime/Cinemachine.Runtime.Tests.asmdef
- com.unity.cinemachine/Tests/Runtime/ClearShotTests.cs
- com.unity.cinemachine/Tests/Runtime/CmColliderTests.cs
- com.unity.cinemachine/Tests/Runtime/CmColliderTests.cs.meta
- com.unity.cinemachine/Tests/Runtime/Confiner2DUnitTests.cs
- com.unity.cinemachine/Tests/Runtime/FreelookForcePositionTests.cs
- com.unity.cinemachine/Tests/Runtime/StateDrivenCameraTests.cs
[CMCL-1314](https://jira.unity3d.com/browse/CMCL-1314): Make Yamato 🟢 
1. Added missing import call.
2. Replaced deprecated API calls in Unity 2023+. (partially a backport of https://github.com/Unity-Technologies/com.unity.cinemachine/pull/727)
3. Replaced some C# sytax that was unsupported in Unity 2019 and 2020, with a sytax that is supported (new (); -> new List<int>();)
4. Fixed #if guard placement in unit tests - caused guards to not work correctly in yamato remote.
5. Disabled (#if !CINEMACHINE_HDRP) the following unit tests that are unstable on HDRP, because they are not using the TimeInvariant test framework developed on main (CM3): 
- FreelookForcePositionTests
- CmColliderTests
- CamerasBlendingTests
> CMCL-1314: Make Yamato green on Cinemachine 2.9

- com.unity.cinemachine/Editor/Editors/CinemachineBlendListCameraEditor.cs
- com.unity.cinemachine/Editor/Editors/CinemachineClearShotEditor.cs
- com.unity.cinemachine/Editor/Editors/CinemachineStateDrivenCameraEditor.cs
- com.unity.cinemachine/Editor/Editors/CinemachineVirtualCameraBaseEditor.cs
- com.unity.cinemachine/Editor/Utility/ChildListInspectorHelper.cs
- com.unity.cinemachine/Editor/Utility/ChildListInspectorHelper.cs.meta
CMCL-1311: changing child's priority in manager camera UX should enable PriorityAndChannel in child.
This applies to BlendList, ClearShot, and SateDriven.
> CMCL-1311: manager ux handles priority properly

- CHANGELOG.md
- Runtime/Core/CinemachineExtension.cs
CMCL-1324: Extensions were not respecting execution order on domain reload.
low
> CMCL-1324: Sort extensions on domain reload for 2.8

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Core/CinemachineExtension.cs
CMCL-1324: sort extensions by execution order on domain reload
low
> CMCL-1324: sort extensions on domain reload for 2.9

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Core/CinemachineExtension.cs
CMCL-1324: Extensions were not respecting execution order on domain reload.
low
> CMCL-1324: Sort extensions on domain reload.

- com.unity.cinemachine/Editor/Editors/CinemachineBlendListCameraEditor.cs
- com.unity.cinemachine/Editor/Editors/CinemachineStateDrivenCameraEditor.cs
[CMCL-1341](https://jira.unity3d.com/browse/CMCL-1341): Instruction lists were not reacting to interaction in the inspector (changing order, or modifying values).
The bug was not yet released. It was introduced by https://github.com/Unity-Technologies/com.unity.cinemachine/pull/716.
> CMCL-1341: Fix InstructionList - Blendlist and StateDriven

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Core/AxisState.cs
CMCL-1344
See description and repro scene there.
Bugfix: AxisState was not respecting timescale == 0
> CMCL-0000 axis state delta time pause bugfix

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Deprecated/AxisState.cs
> CMCL-1345: fix for 3.0 axis state respects timescale=0

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Core/Predictor.cs
- com.unity.cinemachine/Tests/Editor/DampingTests.cs
CMCL-1315: CM's damping is highly sensitive to uneven frame rates, and this can lead to jitter. CINEMACHINE_EXPERIMENTAL_DAMPING is there to address this, and it works, but at an unacceptable performance cost. 
- This PR significantly improves the performance of the stable damping algorithm (replaces a loop with a fixed calculation).  
- Also, the stable algorithm took longer to damp, so its behaviour was noticeably different from the standard algorithm.  Researched a solution for this and added some code to compensate for it, resulting in the same damping time for both algorithms.
- Added StableDampFloat test, to ensure that behaviour is consistent across both methods.
The code is still opt-in, based on the CINEMACHINE_EXPERIMENTAL_DAMPING define.  We might consider changing that. …
> CMCL-1315: damping stability for uneven framerates

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Documentation~/CinemachineConfiner2D.md
- com.unity.cinemachine/Editor/Editors/CinemachineConfiner2DEditor.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineConfiner2D.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineConfiner3D.cs
CMCL-1293: Smooth stop at edge for Confiner2D.
Ported slowing code from Confiner3D.
low
> CMCL-1293: Add confiner2D smooth stop

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Editor/Editors/CinemachineConfiner2DEditor.cs
- com.unity.cinemachine/Editor/Editors/CinemachineConfiner3DEditor.cs
- com.unity.cinemachine/Editor/Editors/CinemachineDeoccluderEditor.cs
- com.unity.cinemachine/Editor/Editors/CinemachineFreeLookModifierEditor.cs
- com.unity.cinemachine/Editor/Editors/CinemachineGroupFramingEditor.cs
- com.unity.cinemachine/Editor/Obsolete/CinemachineConfinerEditor.cs
- com.unity.cinemachine/Editor/Utility/CmPipelineComponentInspectorUtility.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineConfiner2D.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineConfiner3D.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineDeoccluder.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineFollowZoom.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineFreeLookModifier.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineGroupFraming.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineStoryboard.cs
- com.unity.cinemachine/Runtime/Components/CinemachineThirdPersonFollow.cs
- com.unity.cinemachine/Runtime/Core/CinemachineExtension.cs
- com.unity.cinemachine/Runtime/Core/CinemachineVirtualCameraBase.cs
- com.unity.cinemachine/Runtime/Deprecated/Cinemachine3rdPersonFollow.cs
- com.unity.cinemachine/Runtime/Deprecated/CinemachineCollider.cs
- com.unity.cinemachine/Runtime/Deprecated/CinemachineConfiner.cs
- com.unity.cinemachine/Runtime/PostProcessing/CinemachineAutoFocus.cs
- com.unity.cinemachine/Runtime/PostProcessing/CinemachinePostProcessing.cs
- com.unity.cinemachine/Runtime/PostProcessing/CinemachineVolumeSettings.cs
- com.unity.cinemachine/Samples~/2D Samples/CameraMagnets.unity
Refactored CinemachineExtension API a little:
- CinemachineExtension.OnTargetObjectWarped and CinemachineExtension.ForceCameraPosition were not defined in such a way that multi-vcam support was possible.  We did not notice this because until recently they were never used.
- Also fixed a number of places where extension.VirtualCamera was incorrectly being used (again, breaking multi-vcam support).
- Renamed CinemachineExtension.VirtualCamera to CinemachineExtension.ComponentOwner to help prevent this mistake from being made.
- CinemachineExtension.GetAllExtraStates refactored for improved performance.
- Refactored CinemachineConfiner2D a little in consequence of this change.
- Fixed HelpBox refresh issues in Confiner2DEditor
> CMCL-0000: extension refactor

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Editor/Editors/CinemachinePixelPerfectEditor.cs
- com.unity.cinemachine/Editor/Editors/CinemachineVirtualCameraBaseEditor.cs
- com.unity.cinemachine/Editor/PostProcessing/CinemachinePostProcessingEditor.cs
- com.unity.cinemachine/Editor/PostProcessing/CinemachineVolumeSettingsEditor.cs
- com.unity.cinemachine/Editor/PropertyDrawers/LensSettingsPropertyDrawer.cs
- com.unity.cinemachine/Editor/com.unity.cinemachine.editor.asmdef
- com.unity.cinemachine/Runtime/Behaviours/CinemachineBrain.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachinePixelPerfect.cs
- com.unity.cinemachine/Runtime/Core/LensSettings.cs
- com.unity.cinemachine/Runtime/PostProcessing/CinemachinePostProcessing.cs
- com.unity.cinemachine/Runtime/PostProcessing/CinemachineVolumeSettings.cs
- com.unity.cinemachine/Runtime/com.unity.cinemachine.asmdef
CMCL-1359: URP now does temporal reset on camera cuts.
Minimum URP version supported: 14.0.4 (Unity 2022.2.2f1)
> CMCL-1359: URP: add temporal reset on camera cut

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Editor/Editors/CinemachineVirtualCameraBaseEditor.cs
- com.unity.cinemachine/Editor/PostProcessing/CinemachineVolumeSettingsEditor.cs
- com.unity.cinemachine/Editor/Utility/CinemachineLensPresets.cs
- com.unity.cinemachine/Editor/com.unity.cinemachine.Editor.asmdef
- com.unity.cinemachine/Runtime/Behaviours/CinemachineBrain.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachinePixelPerfect.cs
- com.unity.cinemachine/Runtime/Core/LensSettings.cs
- com.unity.cinemachine/Runtime/PostProcessing/CinemachineVolumeSettings.cs
- com.unity.cinemachine/Runtime/com.unity.cinemachine.asmdef
CMCL-1359: URP now does temporal reset on camera cuts.
Minimum URP version supported for this feature: 14.0.4 (Unity 2022.2.2f1)
> CMCL-1359: URP reset on camera cut for 2.9

- com.unity.cinemachine/Editor/Editors/CinemachineVirtualCameraBaseEditor.cs
- com.unity.cinemachine/Editor/SaveDuringPlay/SaveDuringPlay.cs
- com.unity.cinemachine/Editor/Utility/CmCameraInspectorUtility.cs
- com.unity.cinemachine/Editor/Windows/CinemachineCorePrefs.cs
CMCL-1361: SaveDuringPlay was entering objects that were in saved fields, and incorrectly saving the fields within those objects.
One way to see that bug: in the ThirdPerson Shooter sample start the game, then change the value of LockCursor in Player Controller.  Stop the game.  The LockCursor state gets the SaveDuringPlay treatment, even though SimplePlayerController is not SaveDuringPlay.  It happens because CinemachineInpuutAxisController (which is SaveDuringPlay) holds a reference to the SimpleController and incorrectly goes into it to save its fields.
Also corrected the namespace of SaveDuringPlay.
> CMCL-1361: SaveDuringPlay should not follow UnityEngine.Object links

- com.unity.cinemachine/Samples~/3D Samples/ThirdPerson Shooter.unity
- com.unity.cinemachine/Samples~/Shared Assets/Scripts/SamplesHelpGUI.cs
- com.unity.cinemachine/Samples~/Shared Assets/Scripts/SimplePlayerController.cs
Add LockCursor to the shooter sample.  It gets turned on via an event when the help text is dismissed.
This PR depends on https://github.com/Unity-Technologies/com.unity.cinemachine/pull/767 (SaveDuringPlay bugfix)
> CMCL-0000: Add LockCursor to Shooter sample

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Behaviours/CinemachineGroupFraming.cs
CMCL-1362: GroupFraming must consider LookAt target if different from Tracking Target
> CMCL-1362: groupframing works on lookat target also

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Editor/Samples/SampleDependencyImporter.cs
- com.unity.cinemachine/Editor/Upgrader/CinemachineUpgradeManager.cs
- com.unity.cinemachine/Samples~/Old Samples from CM2/Scenes/2D/MouseScrollZoom2D.cs
[CMCL-1364](https://jira.unity3d.com/browse/CMCL-1364): Adds a progress bar to upgrader, so users don't think that their large project is frozen while upgrading.
Also fixed SaveDuringPlay api in one script in the old samples.
> CMCL-1364: Progress bar for Upgrader

- com.unity.cinemachine/Runtime/Core/TargetTracking.cs
CMCL-1356: Improved fix.  We can bypass rotation damping altogether in SimpleFollow because angular damping is always 0 in this mode.
> CMCL-1356: Improved fix for axis drift for CM3

- com.unity.cinemachine/Editor/Upgrader/CinemachineUpgradeManager.cs
- com.unity.cinemachine/Editor/Upgrader/UpgradeObjectToCm3.cs
Found a few missing null checks while testing gigaya.
The other errors are not related to us. They are triggered by us, because gigaya is full of corrupt prefabs. When we open them to check if need to upgrade them, they throw errors. 
The scene that we can't open is also a scene that's corrupted.
These other errors can be cleared in the console.
> CMCL-0000: Upgrader fixes - gigaya test

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Helpers/InputAxisController.cs
Enable more input types (Vector2 and float) by default.
The solution did not produce a measurable performance difference.
> CMCL-1373: Smarter default input handling

- com.unity.cinemachine/Editor/Timeline/CinemachineShotEditor.cs
- com.unity.cinemachine/Editor/Utility/InspectorUtility.cs
Subeditors in timeline clip editor were incorrectly implemented, causing subeditors to not work properly and assertions after domain is reloaded and editor was displayed.
> CMCL-0000: timeline uitk bugfix

- com.unity.cinemachine/Editor/PropertyDrawers/CameraTargetPropertyDrawer.cs
- com.unity.cinemachine/Editor/PropertyDrawers/EmbeddedAssetPropertyDrawer.cs
- com.unity.cinemachine/Editor/Utility/EmbeddedAssetEditorUtility.cs
- com.unity.cinemachine/Editor/Utility/ReflectionHelpers.cs
- com.unity.cinemachine/Runtime/Core/CinemachinePropertyAttribute.cs
UITK replacement for EmbeddedAssetPropertyDrawer, which can be deleted once impulse editor stops using it.
EmbeddedAssetEditorUtility.AddAssetSelectorWithPresets is not being used currently.
> CMCL-0000: Add EmbeddedAssetEditorUtility.AddAssetSelectorWithPresets

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Documentation~/CinemachineCamera.md
- com.unity.cinemachine/Documentation~/CinemachineExternalCamera.md
- com.unity.cinemachine/Editor/Utility/CinemachineEditorAnalytics.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineCamera.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineExternalCamera.cs
- com.unity.cinemachine/Runtime/Components/CinemachineOrbitalFollow.cs
- com.unity.cinemachine/Runtime/Components/CinemachinePanTilt.cs
- com.unity.cinemachine/Runtime/Components/CinemachinePositionComposer.cs
- com.unity.cinemachine/Runtime/Core/CameraState.cs
- com.unity.cinemachine/Runtime/Core/CinemachineComponentBase.cs
- com.unity.cinemachine/Runtime/Core/CinemachineVirtualCameraBase.cs
- com.unity.cinemachine/Runtime/Core/TransitionParams.cs
- com.unity.cinemachine/Runtime/Core/TransitionParams.cs.meta
- com.unity.cinemachine/Runtime/Deprecated/CinemachineFramingTransposer.cs
- com.unity.cinemachine/Runtime/Deprecated/CinemachineFreeLook.cs
- com.unity.cinemachine/Runtime/Deprecated/CinemachineOrbitalTransposer.cs
- com.unity.cinemachine/Runtime/Deprecated/CinemachinePOV.cs
- com.unity.cinemachine/Runtime/Deprecated/CinemachineVirtualCamera.cs
IgnoreTarget blend hint is necessary because sometimes you just want to slerp the angle.
It used to be added by default when there was no Aim component, but this is too pushy.  It needs to be on-demand only.
Refactored the TransitionParams, to make a hint translation function unnecessary - a cast is now sufficient.  API is simplified as a result.
> CMCL-0000: Refactor TransitionParams, add IgnoreTarget hint

- com.unity.cinemachine/Editor/PropertyDrawers/TagFieldPropertyDrawer.cs
Tag field PropertyDrawer in UITK.
Changed the UX a little, making it clearer.  Instead of this:
we have this:
> CMCL-1387: Tag field in PropertyDrawer in uitk

- com.unity.cinemachine/Editor/Editors/CinemachineBlenderSettingsEditor.cs
- com.unity.cinemachine/Editor/Menus/CinemachineMenu.cs
- com.unity.cinemachine/Editor/PropertyDrawers/BlendDefinitionPropertyDrawer.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineBrain.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineClearShot.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineStateDrivenCamera.cs
- com.unity.cinemachine/Runtime/Core/CinemachineBlend.cs
- com.unity.cinemachine/Runtime/Core/CinemachineCameraManagerBase.cs
- com.unity.cinemachine/Tests/Runtime/CamerasBlendingTests.cs
We forgot to remove the m_ from the members of CinemachineBlendDefinition.
> CMCL-1395: Remove m_ from BlendDefinition members

- com.unity.cinemachine/Runtime/Helpers/InputAxisController.cs
[CMCL-1373](https://jira.unity3d.com/browse/CMCL-1373): 
Unfortunately, there is no one API for checking what the input type to read is. I could not break the current solution, but it feels fragile nevertheless.
Maybe it is better to only support Vector2.
Slack discussion with input team: https://unity.slack.com/archives/C09Q7LYP9/p1676555716510299
Original PR: https://github.com/Unity-Technologies/com.unity.cinemachine/pull/790
> CMCL-1373: Handling input smarter (2)

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Editor/Editors/CinemachineClearShotEditor.cs
- com.unity.cinemachine/Editor/Editors/CinemachineExternalCameraEditor.cs
- com.unity.cinemachine/Editor/Editors/CinemachineMixingCameraEditor.cs
- com.unity.cinemachine/Editor/Editors/CinemachineSequencerCameraEditor.cs
- com.unity.cinemachine/Editor/Editors/CinemachineStateDrivenCameraEditor.cs
- com.unity.cinemachine/Editor/Editors/CmCameraEditor.cs
- com.unity.cinemachine/Editor/PropertyDrawers/FoldoutWithEnabledButtonPropertyDrawer.cs
- com.unity.cinemachine/Editor/Utility/CmCameraInspectorUtility.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineCamera.cs
- com.unity.cinemachine/Runtime/Core/CinemachineVirtualCameraBase.cs
- com.unity.cinemachine/Runtime/Core/OutputChannel.cs
Inspector simplification.  Created Transition Settings foldout to fold lesser-used items, reducing clutter.
> CMCL-0000: transition settings section in inspector

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Documentation~/CinemachinePositionComposer.md
- com.unity.cinemachine/Documentation~/CinemachineRotationComposer.md
- com.unity.cinemachine/Editor/Editors/CinemachinePositionComposerEditor.cs
- com.unity.cinemachine/Editor/Editors/CinemachineRotationComposerEditor.cs
- com.unity.cinemachine/Runtime/Components/CinemachinePositionComposer.cs
- com.unity.cinemachine/Runtime/Components/CinemachineRotationComposer.cs
- com.unity.cinemachine/Runtime/Deprecated/CinemachineComposer.cs
- com.unity.cinemachine/Runtime/Deprecated/CinemachineFramingTransposer.cs
In response to internal feedback, renamed TrackedObjectOffset to TargetOffset, and facelifted the inspectors for clarity:
> CMCL-0000: Composer inspector layout improvement

- com.unity.cinemachine/Editor/Editors/CmCameraEditor.cs
When the CmCamera's manager parent has a default target defined, show this in the inspector:
> CMCL-0000: Add default target indicator

- com.unity.cinemachine/Editor/Unity.Cinemachine.Editor.asmdef
LiveCapture team needs this (`CINEMACHINE_3_OR_NEWER`), so they can #if the public API that exposes our internal upgrader code. Similarly how I did it with HDRP, but HDRP luckily had a check that I could use.
> CMCL-0000: Check if installed Cinemachine is 3 or newer assembly definition

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Behaviours/CinemachineMixingCamera.cs
CMCL-1430: MixingCamera was not calling OnTransitionFromCamera for its disabled or 0-weight children.  It must call for all of them regardless of weight and enabled status.
low
> CMCL-1430: MixingCamera calls OnTransitionFromCamera correctly for all its children

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Behaviours/CinemachineMixingCamera.cs
CMCL-1431: MixingCamera was not calling OnTransitionFromCamera for its disabled or 0-weight children.  It must call for all of them regardless of weight and enabled status.
low
> CMCL-1431: MixingCamera calls OnTransitionFromCamera correctly 

- com.unity.cinemachine/Runtime/Behaviours/CinemachineCamera.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineClearShot.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineSequencerCamera.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineStateDrivenCamera.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineTargetGroup.cs
- com.unity.cinemachine/Runtime/Core/CinemachineVirtualCameraBase.cs
- com.unity.cinemachine/Runtime/Deprecated/CinemachineFreeLook.cs
- com.unity.cinemachine/Runtime/Deprecated/CinemachineInputProvider.cs
- com.unity.cinemachine/Runtime/Deprecated/CinemachineVirtualCamera.cs
Several bugfixes:
- The legacy upgrade mechanism (not to be confused with the upgrader) was broken.  Because it was not called synchronously, there was no guarantee that it got called after the relevant fields we properly initialized.  Moved it to where it's guaranteed to be called properly.
- ForceCameraPostion() was overflowing the stack - fix was to not call it for the parent (parent is calling it for the children - duh)
- vcam.GetInputAxisProvider() was re-added for use by deprecated classes
> CMCL-0000: fix legacy upgrade mechanism and more

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Documentation~/CinemachineInputAxisController.md
- com.unity.cinemachine/Editor/Editors/InputAxisControllerEditor.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineMixingCamera.cs
- com.unity.cinemachine/Runtime/Core/CinemachineVirtualCameraBase.cs
- com.unity.cinemachine/Runtime/Core/InputAxisControllerBase.cs
Raised by a user on the forum: https://forum.unity.com/threads/disabling-the-cinemachines-inputs-from-an-active-state-during-state-transitions.1412670/
The idea is to have an option to suppress user input (Orbital/PanTilt) when a camera is in a blend. 
Possible places to put the option:
- ~In the OrbitalFollow and PanTilt behaviours, as a checkbox~
- ~In the BlendHints, as a flag~
- In the InputAxisController (this was done)
low
> CMCL-1424: InputAxisController can suppress input while camera is blending

- com.unity.cinemachine/Editor/Editors/CinemachineBlenderSettingsEditor.cs
- com.unity.cinemachine/Editor/Utility/InspectorUtility.cs
- com.unity.cinemachine/Runtime/Core/CinemachineBlenderSettings.cs
It was unclear that camera specifications in blender settings are strings and do not necessarily have to match any cameras currently in the scene.  The old dropdown hid this.  Now it's more clear.  Also updated the tooltips.
Note: you have to undefine USE_IMGUI_INSTRUCTION_LIST in CinemachineBlenderSettingsEditor.cs in order to see the changes, because they're UITK-only.
> CMCL-1420 better BlenderSettings inspector

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Documentation~/CinemachineManagerCameras.md
- com.unity.cinemachine/Runtime/Behaviours/CinemachineClearShot.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineMixingCamera.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineSequencerCamera.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineStateDrivenCamera.cs
- com.unity.cinemachine/Runtime/Core/CinemachineCameraManagerBase.cs
Refactored CinemachineCameraManagerBase to be more useful for making custom managers.
CinemachineCameraManagerBase is now responsible for managing ChildCameras and blends.  Client only needs to implement ChooseCurrentCamera() method, which chooses the appropriate child for the current frame.  It can do this however it likes.
Very little boilerplate is needed.  
low
> CMCL-0000: Refactor CinemachineCameraManagerBase to be more useful for customizing

- com.unity.cinemachine/Documentation~/CinemachineBrainEvents.md
- com.unity.cinemachine/Editor/Editors/CinemachineBrainEventsEditor.cs
- com.unity.cinemachine/Editor/Editors/CinemachineCameraEventsEditor.cs
- com.unity.cinemachine/Editor/Utility/CmPipelineComponentInspectorUtility.cs
- com.unity.cinemachine/Runtime/Core/CinemachineCameraManagerBase.cs
- com.unity.cinemachine/Runtime/Core/CinemachineVirtualCameraBase.cs
- com.unity.cinemachine/Runtime/Deprecated/CinemachineFreeLook.cs
- com.unity.cinemachine/Runtime/Helpers/CinemachineBrainEvents.cs
- com.unity.cinemachine/Runtime/Helpers/CinemachineCameraEvents.cs
- CinemachineBrainEvents behaviour can now be added to manager cameras.  These will fire based on the activity of the child cameras.
- CinemachineCameraEvents can also be added to manager cameras.  These will fire based on the activity of the manager camera itself.
- Fixed: CinemachineVirtualCameraBase was erroneously implementing ICinemachineMixer.
> CMCL-0000: event behaviours support manager cameras

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Behaviours/CinemachineVirtualCamera.cs
Bugfix: Passive vcams with noise were not respecting transform's z rotation during blends.
See description here: https://forum.unity.com/threads/was-there-a-change-in-transitions-with-a-roll-of-z-axis-dutch.1417956/#post-8913316
low
This is not a problem for CM3 because it has IgnoreLooktTarget blend hint, which for back-compatibility reasons is difficult to add to 2.9
> CMCL-1459: only vcams with no aim will ignore look at target by default

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Editor/Samples/SampleDependencyImporter.cs
- com.unity.cinemachine/Samples~/HDRP~/Lighting.prefab.meta
- com.unity.cinemachine/Samples~/InputSystem~/HelpUI.prefab
[CMCL-1467](https://jira.unity3d.com/browse/CMCL-1467): Runtime UITK only works with built-in input system by default. For Input System, it needs to have an Event System + Input System UI Module. 
The fix is similar to how HDRP specific changes are made:
I added a new folder to our samples: InputSystem~. This has a HelpUI.prefab, which replaces the root contents with an Input System appropriate one when importing the samples.
The new prefab root has these extra components:
This way our runtime ui button can react to both built-in and input system one depending on which one is installed. When both are installed, we use input system.
> CMCL-1467: Runtime UITK should react to Input System

- com.unity.cinemachine/Samples~/3D Samples/RunningRace.unity
[CMCL-1363](https://jira.unity3d.com/browse/CMCL-1363): Added a group-framing camera to the runner scene showing the power of procedural cameras.
This scene has probably uncovered a bug. The blend from GroupFramingCamera to LeaderCamera jerks back or under the platform after the blend has seemingly finished.
Also noticed that there is no BlendHint on ManagerCameras. Why?
> CMCL-1363: Group-framed Runners

- com.unity.cinemachine/Samples~/2D Samples/2D Platformer/2D Platformer.unity
- com.unity.cinemachine/Samples~/2D Samples/2D Platformer/GameControl.cs
- com.unity.cinemachine/Samples~/2D Samples/2D Platformer/Platformer Camera 2D.cs
- com.unity.cinemachine/Samples~/Shared Assets/Prefabs/Player 2D.prefab
- com.unity.cinemachine/Samples~/Shared Assets/Prefabs/Player.prefab.meta
- com.unity.cinemachine/Samples~/Shared Assets/Scripts/SimplePlayerController.cs
A couple of minor fixes:
- Warning caused by overriding parent classes CameraOverride property. -> Fix: remove in child and use parent's.
- Removed duplicate capsule collider from Player 2D prefab.
Found bug: Left camera is never activated, because it depends on the Follow Target's rotation and not on the PlayerGeometry (Animated Cameron's rotation).
Possible fix is to add a `Transform PlayerGeometry` property to `PlatformerCamera2D` like `SimplePlayerController2D`, and using that to determine left/right orientation.
> CMCL-0000: 2D platformer fixes

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Core/BlendManager.cs
- com.unity.cinemachine/Runtime/Core/CameraBlendStack.cs
- com.unity.cinemachine/Runtime/Core/CinemachineBlend.cs
- com.unity.cinemachine/Tests/Runtime/CamerasBlendingTests.cs
CMCL-1473: Improve handling of nested blends.
1. Blends ((A -> B) -> A) -> B have incorrect timing (can zip fast at end).  This should not happen.  Instead, blends should take the appropriate remaining blend time.
2. Nested blends should continue evaluating, so that (A -> B) -> C will move the camera in an arc instead of taking a segmented path.
3. Blends should not nest indefinitely, so that ((A -> B) -> C) -> D should take a snapshot of A -> B
See the attached scene in the jira ticket for a good test case.  Cycle between the 3 cameras to test blend chaining.
low
This PR is included in https://github.com/Unity-Technologies/com.unity.cinemachine/pull/871, which is built off of this branch
> CMCL-1473: Improve handling of nested blends

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Behaviours/CinemachineSmoothPath.cs
- com.unity.cinemachine/Runtime/Core/CinemachinePathBase.cs
Fix of evaluate local orientation returning a global value instead of a local one. 
Reported by a user.
https://forum.unity.com/threads/dolly-track-evaluate-orientation-is-incorrect-if-track-is-rotated-cm-2-9-5.1432078/#post-8987869
> CMCL-0000: Fix evaluate local orientation returning global value

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Core/BlendManager.cs
- com.unity.cinemachine/Runtime/PostProcessing/CinemachineVolumeSettings.cs
CMCL-1498: 
There were 2 causes for this issue:
1. Camera Cut events were being generated sometimes when actually it was a blend.
2. CinemachineVolumeSettings was not checking evt.IsCut, and was always doing an HDRP temporal reset, causing text to flash.
low
> CMCL-1498: Spurious camera cut events were being issued, especially in HDRP

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Documentation~/CinemachineGroupFraming.md
- com.unity.cinemachine/Editor/Editors/CinemachineGroupFramingEditor.cs
- com.unity.cinemachine/Editor/Utility/CmPipelineComponentInspectorUtility.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineGroupFraming.cs
CMCL-1505: Group framing inspector was displaying incorrect warning when LookAt target was a group and not Tracking Target.
Also: added Size Framing setting to Grop Framing extension, to control the position of the group on-screen.
Aslo: corrected some errors in the doc
low
> CMCL-1505: Incorrect warning in Group Framing inspector, and no way to set screen position

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Documentation~/CinemachineGroupFraming.md
- com.unity.cinemachine/Editor/Editors/CinemachineGroupFramingEditor.cs
- com.unity.cinemachine/Editor/Editors/CinemachinePositionComposerEditor.cs
- com.unity.cinemachine/Editor/Editors/CinemachineRotationComposerEditor.cs
- com.unity.cinemachine/Editor/Obsolete/CinemachineComposerEditor.cs
- com.unity.cinemachine/Editor/Obsolete/CinemachineFramingTransposerEditor.cs
- com.unity.cinemachine/Editor/Obsolete/CinemachineGroupComposerEditor.cs
- com.unity.cinemachine/Editor/Upgrader/UpgradeObjectToCm3.cs
- com.unity.cinemachine/Editor/Utility/CmPipelineComponentInspectorUtility.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineGroupFraming.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineTargetGroup.cs
- com.unity.cinemachine/Runtime/Core/CinemachineVirtualCameraBase.cs
- com.unity.cinemachine/Runtime/Core/UnityVectorExtensions.cs
- com.unity.cinemachine/Runtime/Deprecated/CinemachineFramingTransposer.cs
- com.unity.cinemachine/Runtime/Deprecated/CinemachineGroupComposer.cs
CMCL-1506: 
- nullrefs in log when a referenced group is deleted
- nullrefs in group framing inspector when entering playmode
- group size gameview indicator was incorrect
- remove GroupFraming.FramingOffset setting - can use Recomposer for that.
low
> CMCL-1506: group framing fixes

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Behaviours/CinemachineCollider.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineFreeLook.cs
CMCL-1511: NaNs generated by CM Collider if no vcam targets
low
> CMCL-1511: nans in cinemachine collider 2.9

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Documentation~/CinemachineInputAxisController.md
- com.unity.cinemachine/Runtime/Helpers/CinemachineInputAxisController.cs
Addressing this issue: https://forum.unity.com/threads/why-is-cinemachinefreelook-camera-framerate-dependant.1419530/#post-9256107
I don't love the name of the new parameter, but am having a hard time thinking of something better.  Open to ideas.
I don't have a good generic solution for CM2.
low
> CMCL-0000: Added CancelDeltaTime option

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Editor/Editors/CinemachineBlenderSettingsEditor.cs
- com.unity.cinemachine/Editor/Editors/CinemachineSequencerCameraEditor.cs
- com.unity.cinemachine/Editor/Editors/InputAxisControllerEditor.cs
- com.unity.cinemachine/Editor/Utility/CmCameraInspectorUtility.cs
- com.unity.cinemachine/package.json
ListView inspectors are broken on Unity 2022.3.9f1:
1. ClearShot child cameras have invalid warning icons in the inspector
2. SequencerCamera does not populate the camera drop-down in the instruction list
3. InputAxisController editor is missing foldout arrows on the Driven Axes items
low
> CMCL-1517: Fix ListView inspectors

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Documentation~/CinemachineConfiner2D.md
Backport the efficiency doc on collider 2d
[forum](https://forum.unity.com/threads/unrelaible-results-using-cinemachine-confiner-with-group-framing-transposer.1490167/#post-9352016) 
[Justification for updating either …
> CMCL-0000: Backport efficiency note to CM2 for confiner 2d.

- .yamato/metadata.metafile
- .yamato/package-coverage.yml
- .yamato/package-pack.yml
- .yamato/package-promotion.yml
- .yamato/package-publish.yml
- .yamato/project-pack.yml
- .yamato/project-test.yml
See [package-ci/stable has been deprecated for all platforms. Updated images versions to fix the issue.](https://github.com/Unity-Technologies/com.unity.cinemachine/pull/916)
> CMCL-0000: 2.9 Back port of update image version to fix job failing on MacOS

- .yamato/metadata.metafile
- .yamato/package-coverage.yml
- .yamato/package-pack.yml
- .yamato/package-promotion.yml
- .yamato/package-publish.yml
- .yamato/package-validation.yml
- .yamato/project-pack.yml
- .yamato/project-test.yml
package-ci/stable has been deprecated for all platforms. Updated images versions to fix the issue.
> CMCL-0000: Update image version to fix job failing on MacOS

- com.unity.cinemachine/Runtime/Core/CinemachineVirtualCameraBase.cs
- com.unity.cinemachine/Runtime/Core/PrioritySettings.cs
- com.unity.cinemachine/Tests/Runtime/PriorityTestsImplicitCastingOperators.cs
- com.unity.cinemachine/Tests/Runtime/PriorityTestsImplicitCastingOperators.cs.meta
This PR addresses the issue I raised #922 regarding the `PrioritySettings` struct. 
The main purpose is to enhance the usability and clarity of the API, particularly in the context of the recent 3.X.X API changes. This PR introduces custom operators for casting to/from `int` for the `PrioritySettings` struct, and updates the XML documentation to better guide developers through the API changes.
I've made a modified copy of `PriorityTests.cs`, (`PriorityTestsImplicitCastingOperators.cs`) this is identical except it uses the custom operator instead. Let me know if more tests are required because this *doesn't* …
> CMCL-0000: PrioritySettings Casting/Type Conversion Operators

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Core/CameraBlendStack.cs
CMCL-1551: index out of range exceptions when running a CM track on a disabled camera
none at all
> CMCL-1551: add missing empty check when overriding a blend stack

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Components/Cinemachine3rdPersonFollow.cs
CMCL-1555: errors in console when 3rdPersonFollow.DampingFromCollision is nonzero
low
Fix was just to add an early out if direction length is zero.  Extremely low risk intervention.
> CMCL-1555: add missing 3rdPersonFollow length check

- com.unity.cinemachine/Editor/Utility/CmCameraInspectorUtility.cs
- com.unity.cinemachine/Runtime/Components/CinemachineHardLookAt.cs
- com.unity.cinemachine/Runtime/Components/CinemachineRotationComposer.cs
- com.unity.cinemachine/Runtime/Core/CinemachineComponentBase.cs
With this vcam setup, there should not be a "camera is looking at itself" warning, because the camera doesn't try to look at the LookAt target:
This PR adds an internal API so the inspector can ask a component if it's trying to look at the LookAt target, and display the warning only if it is.
> CMCL-0000: Better filtering for vcam Navel Gazing warning

- com.unity.cinemachine/Editor/EditorResources/CMWaveform.compute
CMCL-1557 HLSL 2021 is incompatible with ternary operators in some cases.
Same fix as here: https://github.com/Unity-Technologies/Graphics/pull/8007
> CMCL-1557: HLSL errors for HLSL 2021

- com.unity.cinemachine/Documentation~/index.md
There is a typo in the mention of Editor minimum required version in the documentation landing page.
It's a 1-digit PR, but 3 different people already reported the issue, I'd like to get rid of the corresponding sticky tickets [DOCATT-4982](https://jira.unity3d.com/browse/DOCATT-4982), [DOCATT-5185](https://jira.unity3d.com/browse/DOCATT-5185), and [DOCATT-4699](https://jira.unity3d.com/browse/DOCATT-4699), and be able to do so with any potential subsequent ones by the time we release the next patch.
Please confirm that the mentioned version is accurate as of today. Thanks!
> CMCL-0000: Fix typo in Editor min req version

- com.unity.cinemachine/Editor/Menus/CinemachineMenu.cs
- com.unity.cinemachine/Editor/Utility/CmCameraInspectorUtility.cs
If there is no Brain in the scene, add a help box with a "fix it" button.
> CMCL-0000: add missing brain warning to vcam inspector

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Core/SplineContainerExtensions.cs
**This fix should be backported to 3.0 branch.**
https://forum.unity.com/threads/3-0-1-spline-cart-rotates-wrongly-if-the-splinecontainer-is-rotated.1559951/
A spline cart that's following a rotated spline container winds up with an incorrect rotation
rotation = rotation * spline.transform.rotation;
This applies the spline container's rotation after the evaluated rotation, which is backwards. This results in weird orientations that wobble around as you rotate the spline container.
It should go like this:
rotation = spline.transform.rotation * rotation;
After the fix, the cart behaves as expected. This code is in SplineContainerExtension.cs in version 3.0.1.
[Explanation of what’s tested, how tested and existing or new automation tests. Can include manual testing by self and/or QA. Specify …
> CMCL-1576:  Spline roll calculated incorrectly when spline rotated

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Components/CinemachineOrbitalFollow.cs
- com.unity.cinemachine/Runtime/Components/CinemachinePanTilt.cs
Axis recentering happens independently **on axes with differing recentering tmes**, so that input on one axis does not impact the recentering state of the others.
**note:** This should be backported to 3.0 branch
> CMCL-0000: sync recentering with matching times

- com.unity.cinemachine/Runtime/Core/CameraBlendStack.cs
Fixes #963 
When using the Blend Hint "Freeze When Blending Out" the blend snapshot was not properly reset causing issues when blending to the same camera again (using an empty snapshot, causing the camera to jump to 0,0,0).
- [X ] Manually tested
> Properly reset Snapshots when blending.

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Behaviours/CinemachineTargetGroup.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineTargetGroup.cs.meta
- com.unity.cinemachine/package.json
CMCL-1574: 
When all members of a target group are disabled, target group should retain its most recent valid position and dimensions, to avoid camera pops.
This fixes a regression reported in CMCL-1574
low
> CMCL-1574: zero member targetgroup behaves better

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Documentation~/CinemachineInputAxisController.md
- com.unity.cinemachine/Runtime/Core/InputAxisControllerBase.cs
https://forum.unity.com/threads/how-to-make-cinemachine-still-follow-player-when-time-timescale-0.723806/#post-9749095
Adds an option to InpuAxisController to continue processing input even when timescle is 0. 
low
> CMCL-0000: Add IgnoreTimeScale option to InputAxisControllerBase

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Behaviours/CinemachineBrain.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineCamera.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineSplineCart.cs
- com.unity.cinemachine/Runtime/Core/UnityVectorExtensions.cs
This is the CM3 version of PR #967
CMCL-1580: Cinemachine dirties scenes for nothing. This is a long-standing issue.
Fix is to set the vcam and main camera transform's position and rotation only if significantly different from what it is. There is one gotcha: because transform rotation is stored in local space, setting it in global space will introduce imprecisions when conversion is made. So we do the delta check in local space, and set the values in local spacee also.
Because all that takes processing power, we do it only if in editor and not playing.
low
> CMCL-1580: save rotations so as to not dirty the scene unnecessarily

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Editor/SaveDuringPlay/SaveDuringPlay.cs
CMCL-1579: Add confirmation when exiting play mode is SaveDuringPlay is enabled and changes have been made.
> CMCL-1579: add SaveDuringPlay confirmation dialog

- com.unity.cinemachine/Editor/SaveDuringPlay/SaveDuringPlay.cs
Fields with NonSerialized attribute should be ignored by SaveDuringPlay.
> CMCL-0000: Fields with NonSerialized attribute should be ignored by SaveDuringPlay

- com.unity.cinemachine/Editor/PropertyDrawers/InputAxisPropertyDrawer.cs
- com.unity.cinemachine/Editor/PropertyDrawers/LensSettingsPropertyDrawer.cs
- com.unity.cinemachine/Editor/PropertyDrawers/Vector2AsRangePropertyDrawer.cs
A recent PR had added isDelayed to some float fields (e.g. FOV, axis value) because when typing values OnValidate() got called and interfered with the typing.  However, the side-effect of this was that when dragging the label to change the value, no dynamic refresh happened until dragging stopped.
We think that the cure is worse than the disease, so we are reverting the isDelayed while we look for a better solution.
> CMCL-0000: remove some isdelayed attributes because it interferes with dynamic refresh

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Behaviours/CinemachineGroupFraming.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineGroupFraming.cs.meta
- com.unity.cinemachine/package.json
GroupFraming and Confiner2D did not play well together.  
Slack thread: https://unity.slack.com/archives/C4P4KJR9A/p1713367131830879
This PR introduces a special compatibility mode to handle this common use-case.  GroupFraming checks for the presence of Confiner2D and if it finds one, it runs in the Body stage (with an early execution order) so that it happens before Confiner2D.  Also, in this mode it monitors the ortho size and invalidates the confiner lens cache when the ortho size changes.
low
> CMCL-0000: Group Framing works with Confiner 2D

- com.unity.cinemachine/Editor/PropertyDrawers/DelayedVectorPropertyDrawer.cs
- com.unity.cinemachine/Editor/PropertyDrawers/FoldoutWithEnabledButtonPropertyDrawer.cs
- com.unity.cinemachine/Editor/PropertyDrawers/InputAxisPropertyDrawer.cs
- com.unity.cinemachine/Editor/PropertyDrawers/LensSettingsPropertyDrawer.cs
- com.unity.cinemachine/Editor/PropertyDrawers/Vector2AsRangePropertyDrawer.cs
- com.unity.cinemachine/Editor/Utility/CmCameraInspectorUtility.cs
- com.unity.cinemachine/Editor/Utility/DelayedFriendlyFieldDragger.cs
- com.unity.cinemachine/Editor/Utility/DelayedFriendlyFieldDragger.cs.meta
- com.unity.cinemachine/Editor/Utility/InspectorUtility.cs
- com.unity.cinemachine/Runtime/Core/ScreenComposerSettings.cs
The IsDelayed function on float fields delays processing of the text input until enter is pressed.  This is useful because otherwise OnValidate() kicks in and interferes with your typing when it does its clamping.
However, isDelayed also prevents processing when you drag on the label, until you stop dragging.  This kills the visual feedback that is crucial for some fields.
This PR re-introduces dragging for isDelayed fields by installing a custom dragger that temporarily disables isDelayed while the property is being dragged.
This custom dragger has been added to the following fields:
- FOV/Ortho size (collapsed and expanded versions)
- Axis Value (collapsed and expanded versions)
- Composition settings in PositionComposer and RotationComposer.
> CMCL-0000: Add isDelayed to some fields in a drag-tolerant way

- com.unity.cinemachine/Editor/Editors/CinemachineFreeLookModifierEditor.cs
- com.unity.cinemachine/Editor/Obsolete/CinemachineVirtualCameraBaseEditor.cs
- com.unity.cinemachine/Editor/Obsolete/VcamStageEditor.cs
- com.unity.cinemachine/Editor/PropertyDrawers/EmbeddedAssetPropertyDrawer.cs
- com.unity.cinemachine/Editor/PropertyDrawers/SplineAutoDollyPropertyDrawer.cs
- com.unity.cinemachine/Editor/Utility/CmCameraInspectorUtility.cs
- com.unity.cinemachine/Editor/Utility/CmPipelineComponentInspectorUtility.cs
- com.unity.cinemachine/Editor/Utility/EmbeddedAssetEditorUtility.cs
- com.unity.cinemachine/Editor/Utility/InspectorUtility.cs
- com.unity.cinemachine/Editor/Utility/ReflectionHelpers.cs
- com.unity.cinemachine/Tests/CmCameraProceduralBehaviourCacheTests.cs
- com.unity.cinemachine/Tests/Editor/UpgradeCm2ToCm3Tests.cs
TypeCache is an optimization when iterating type using reflection.  Using TypeCache to search for types speeds up domain reload time.
> CMCL-1397: Use TypeCache where appropriate

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Documentation~/CinemachinePanTilt.md
- com.unity.cinemachine/Runtime/Components/CinemachinePanTilt.cs
- com.unity.cinemachine/Runtime/Core/InputAxis.cs
- com.unity.cinemachine/Runtime/Deprecated/CinemachinePOV.cs
Added "Recenter Target" feature to PanTilt, because it was available in CM2 POV and missing in CM3.
Reported on forums:  https://forum.unity.com/threads/cm3-pan-tilt-w-tracking-target-reference-frame-causes-spinning-camera.1583394/#post-9792165
low
> CMCL-1581: Add Recenter Target option to PanTilt

- com.unity.cinemachine/Editor/SaveDuringPlay/SaveDuringPlay.cs
As a small assistance so you know what you're saving.
> CMCL-0000: Add list of modified objects to SaveDuringPlay dialog

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Samples~/Shared Assets/Scripts/SimplePlayerController.cs
SimplePlayerController no longer uses PlayerController.isGrounded because it's not reliable outside of FixedUpdate.
Reported via salck: https://unity.slack.com/archives/C4P4KJR9A/p1714691648512799
Just sample code.
> CMCL-0000: SimplePlayerController no longer uses PlayerController.isGrounded

- com.unity.cinemachine/Runtime/Behaviours/CinemachineExternalCamera.cs
- com.unity.cinemachine/Runtime/Core/CameraState.cs
- com.unity.cinemachine/Runtime/Core/CinemachineCore.cs
- Fix BlendHint descriptions as per user feedback [DOCATT-4983](https://jira.unity3d.com/browse/DOCATT-4983).
- Uniformize at best the descriptions of other BlendHint items (found during investigation).
**Note:** I did the minimum at least to point out the affected lines in this PR:
- The descriptions for `CinemachineExternalCamera.cs` and `CinemachineCore.cs` come from `CinemachineCameras.cs` (also used in 2 other places), please tell me if it applies as is to these cases.
- I tried to fix at best the user's concern in the `CameraState.cs` descriptions but I think we can do better by giving a little bit more context similarly to the other descriptions mentioned above, if possible.
**Note 2:** Once it's fixed, I'd like to backport the same in latest 2.x version as the user gave the …
> CMCL-0000: Fix and uniformize BlendHint descriptions (user feedback)

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Behaviours/CinemachineTargetGroup.cs
CMCL-1585.  CM3 version of #983 
Use same test scene (upgrade it to CM3)
low
> CMCL-1585: GroupAverage Rotation Mode not calculated correctly CM3

- com.unity.cinemachine/Editor/SaveDuringPlay/SaveDuringPlay.cs
CMCL-1586: When there is an unloaded scene in the hierarchy, an error is thrown when exiting play mode.
details here: https://unity.slack.com/archives/C4P4KJR9A/p1715060122618279
Issue is present in CM2 and CM3.
This is CM3 version of #987
> CMCL-1586: SaveDuringPlay check for unloaded scenes CM3

- com.unity.cinemachine/Editor/Utility/SaveDuringPlay.cs
CMCL-1586: When there is an unloaded scene in the hierarchy, an error is thrown when exiting play mode.
details here: https://unity.slack.com/archives/C4P4KJR9A/p1715060122618279
Issue is present in CM2 and CM3.
This is CM2 version of #986
> CMCL-1586: SaveDuringPlay check for unloaded scenes CM2

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Behaviours/CinemachineDeoccluder.cs
CMCL-1594: missing null check generated console exceptions.
none whatsoever
> CMCL-1594: missing null check in deoccluder

- com.unity.cinemachine/Tests/Editor/IsHDRP.cs
- com.unity.cinemachine/Tests/Runtime/IsHDRP.cs
> CMCL-1588: upgrade HDRP API in tests

- com.unity.cinemachine/Runtime/Behaviours/CinemachineBrain.cs
SaveDuringPlay is meant for camera tweaking, not Brain tweaking.  Some users change things like Default Blend at runtime.,  There is no reason to save such changes, and doing so can mess people up.
> CMCL-1589: No SaveDuringPlay for CMBrain

- com.unity.cinemachine/Samples~/3D Samples/ThirdPersonWithRoadieRun.unity
- com.unity.cinemachine/Samples~/Shared Assets/Cameron/Model/CameronSimpleController.controller
Improved Cameron controller for jump state.
ThirdPersonWithRoadieRun updated to reflect new state machine structure
> CMCL-0000: Improved character controller for jump state

- com.unity.cinemachine/Documentation~/CinemachineCamera.md
- com.unity.cinemachine/Documentation~/CinemachineClearShot.md
- com.unity.cinemachine/Documentation~/CinemachineMixingCamera.md
- com.unity.cinemachine/Documentation~/CinemachineSequencerCamera.md
- com.unity.cinemachine/Documentation~/CinemachineStateDrivenCamera.md
[DOCATT-4965](https://jira.unity3d.com/browse/DOCATT-4965) - Standby Update property is not fully documented in the user manual while more info is provided in the tooltip and API docs
Completed the description in 5 affected component reference pages (Cinemachine Camera and the 4 Manager Cameras), using info from the tooltip and descriptions from API docs.
> CMCL-0000: Complete the Standby Update property description

- com.unity.cinemachine/Runtime/Impulse/CinemachineCollisionImpulseSource.cs
[DOCATT-4964](https://jira.unity3d.com/browse/DOCATT-4964) - Provide a hint to define impulse characteristics from the Class CinemachineCollisionImpulseSource page of API docs.
Fixed missing word in the existing description and added a sentence mentioning CinemachineImpulseSource.ImpulseDefinition.
> CMCL-0000: Add hint for impulse characteristics

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Behaviours/CinemachineCamera.cs
CMCL-1548: In the past, the CinemachineCamera's position and rotation were only pushed back to the transform if a tracking target was present.  This was to protect statically-positioned cameras from having their transforms changed by procedural extensions.
This limitation has been removed, as the relevant extensions will affect the corrected position/rotation in the state, not the raw position/rotation, and only the raw position/rotation is pushed back to the transform.
> CMCL-1548: always update vcam transform, even if no tracking target

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Core/TargetPositionCache.cs
Custom Cinemachine classes were prevented from supporting CInemachine's Timeline cached scrubbing feature because the necessary API was internal.
Solution was to make public the following two static methods:
`TargetPositionCache.GetTargetPosition()` and `TargetPositionCache.GetTargetRotation()`
0
Just made 2 static methods public.  There is a repro project in the bug report that can be used to test.
> CMCL-1606: TargetPositionCache needs to be public

- com.unity.cinemachine/Documentation~/CinemachineAlternativeInput.md
[DOCATT-6508](https://jira.unity3d.com/browse/DOCATT-6508) - Clarify the mention of Input System package
Updated UnityEngine.Input to UnityEngine.InputSystem and added a link to the package docs.
> CMCL-0000: DOCATT-6508 - Update Input System package mention

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Editor/PropertyDrawers/LensSettingsPropertyDrawer.cs
CMCL-1621: Added missing delayed processing on near and far clip plane fields of CM camera lens
low
> CMCL-1621: add isdelayed to near and far clip plane fields

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Components/CinemachinePositionComposer.cs
- com.unity.cinemachine/Runtime/Deprecated/CinemachineFramingTransposer.cs
CMCL-1361: FramingTransposer camera drift when nonzero dead zone.
Fix was to improve precision of calculation.
low
> CMCL-1631: FramingTransposer with a dead zone would sometimes drift

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Components/CinemachineFramingTransposer.cs
CMCL-1630: FramingTransposer camera drift when nonzero dead zone.
Fix was to improve precision of calculation.
low
> CMCL-1360: framingtransposer dead zone drift cm2

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Components/CinemachinePanTilt.cs
CMCL-1629: PanTilt recentering was ignoring axis center setting.  Was using hardcoded (0, 0).
low
> CMCL-1629: pantilt recentering was ignoring axis center setting

- com.unity.cinemachine/Documentation~/CinemachineEvents.md
- com.unity.cinemachine/Documentation~/InputSystemComponents.md
- com.unity.cinemachine/Documentation~/concept-camera-control-transitions.md
Fixing small documentation issues reported by users:
> CMCL-0000: Fix documentation typos reported by users

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Editor/Timeline/CinemachineShotClipEditor.cs
- com.unity.cinemachine/Editor/Timeline/CinemachineShotEditor.cs
CMCL-1637: UX on the CinemachineShot inside Timeline was exposing a button to create a vcam.  This operation is only valid in Scene mode, not in Prefab mode.  
UX was removed for prefab mode, and a clarifying helpbox was added.
low
> CMCL-1637: Don't auto-create vcams in scene when editing CinemachineShot in prefab mode

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Editor/PropertyDrawers/HideIfNoComponentPropertyDrawer.cs
- com.unity.cinemachine/Editor/Timeline/CinemachineShotClipEditor.cs
- com.unity.cinemachine/Editor/Timeline/CinemachineShotEditor.cs
CMCL-1636: UX on the CinemachineShot inside Timeline was exposing a button to create a vcam.  This operation is only valid in Scene mode, not in Prefab mode.  
UX was removed for prefab mode, and a clarifying helpbox was added.
low
> CMCL-1636: better clarity for cinemachine shot ux when inside a prefab

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Editor/Editors/CinemachineCameraEditor.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineDeoccluder.cs
CMCL-1644: camera glitches sometimes:
- when there is a deoccluder with nonzero smoothing and the camera is newly enabled, there are times when it's smoothing out of a ghost position (see repro project in discussion thread)
- when there is a deoccluder with nonzero smoothing and damping, sometimes the camera will ignore the damping and pop when the occlusion is resolved
low
> CMCL-1644: Fix deoccluder state and damping issues

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Documentation~/CinemachineFreeLookModifier.md
- com.unity.cinemachine/Editor/Editors/CinemachineFreeLookModifierEditor.cs
- com.unity.cinemachine/Editor/Editors/CinemachinePositionComposerEditor.cs
- com.unity.cinemachine/Editor/Editors/CinemachineRotationComposerEditor.cs
- com.unity.cinemachine/Editor/SaveDuringPlay/SaveDuringPlay.cs
- com.unity.cinemachine/Editor/Utility/GameViewComposerGuides.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineFreeLookModifier.cs
- com.unity.cinemachine/Runtime/Components/CinemachinePositionComposer.cs
- com.unity.cinemachine/Runtime/Components/CinemachineRotationComposer.cs
- com.unity.cinemachine/Runtime/Core/UnityVectorExtensions.cs
CMCL-1654: When the FreeLookModifier modifies the screen composition, the RotationComposer applies damping to the change, producing a sluggish effect:
The desired behaviour is to bypass damping for this change, giving an undamped direct response.  The current behaviour is a regression compared to CM 2.X, which behaved as desired.
This PR addresses this problem, and others:
- RotationComposer damping is bypassed for changes to the ScreenPosition parameter, whether via inspector or FreeLookModifier
- RotationComposer code was optimized for performance.  The UpdateCache method was improved so that it does less work.
- When a FreeLookModifier is actively modifying the composition, the GameView composer guides now show the modified composition instead of misleadingly showing the center value. …
> CMCL-1654: freelook improvements

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Behaviours/CinemachineDecollider.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachineDeoccluder.cs
CMCL-1657:
This fixes an artifact introduced by a recent change to the Deoccluder damping algorithm.
Open the FreeLook Deoccluder sample scene.
Put a large Damping value on the deoccluder (e.g.3)
Make the top orbit very high, so that the camera is far away compared to the other orbits
Play the scene.
Move the character cloase enough to a wall while looking horizontally to make the camera deocclude.
Rotate on X axis to eliminate the occlusion (camera begins to damp back to position)
Now, go to top orbit.  We expect to get there quickly (because it's a user-triggered action) but damping makes it happen slowly.
> CMCL-1657: CinemachineDeoccluder damping interferes with FreeLook

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Editor/Utility/InspectorUtility.cs
CMCL-1668: Mac only (works on windows): dropdowns and popups in Cinemachine inspectors were flaky.  This is the same issue as a previous fix for the CinemachineExtensions dropdown, but in another area of the code.
Repro steps in the ticket.
none whatsoever
> CMCL-1668: mac dropdowns and popups not behaving consistently

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Documentation~/CinemachinePostProcessing.md
- com.unity.cinemachine/Documentation~/CinemachineVolumeSettings.md
- com.unity.cinemachine/Runtime/PostProcessing/CinemachinePostProcessing.cs
- com.unity.cinemachine/Runtime/PostProcessing/CinemachineVolumeSettings.cs
This is the CM2 backport.
[CMCL-1670](https://jira.unity3d.com/browse/CMCL-1670): add ability for user to control the post-processing volume blend algorithm.
See discussions thread for repro project: https://discussions.unity.com/t/cinemachine-2-10-1-is-now-available/951450/8
low
> CMCL-1670: post process blend control for cm2

- com.unity.cinemachine/Editor/Editors/CinemachineBrainEditor.cs
Sometimes people improperly set the Brain's BlendUpdateMethod to FixedUpdate, because they don't know whet they're doing.  This warning should help.  It's visible only when the BlendUpdateMethod is set to FixedUpdate and the UpdateMethod is set to something other than FixedUpdate.
> CMCL-0000: Add inspector warning for brain update mode

- com.unity.cinemachine/Editor/Editors/CinemachineCameraEditor.cs
CMCL-1699: CinemachineCamera editor was updating the camera state too aggressively: don't do it when the target is disabled
low
> CMCL-1699: Don't force-update camera state from editor if target is not enabled

- com.unity.cinemachine/CHANGELOG.md
- com.unity.cinemachine/Runtime/Behaviours/CinemachineCamera.cs
- com.unity.cinemachine/Runtime/Core/CinemachineVirtualCameraBase.cs
CMCL-1704: InheritPosition was working for the commonly-used cases (i.e. setting orbital axes, lazy follow), but has been broken for some time for the less commonly-used cases (e.g. as in the sample scene).
The fix is simple: don't invalidate the previous state after setting it in ForceCameraPosition.  Validate it instead.  Dumb bug.
low
> CMCL-1704: InheritPosition was not inheriting the camera position in all cases

- .github/codecov.yml
- .yamato/code-coverage.yml
- .yamato/wrench/api-validation-jobs.yml
- .yamato/wrench/package-pack-jobs.yml
- .yamato/wrench/preview-a-p-v.yml
- .yamato/wrench/promotion-jobs.yml
- .yamato/wrench/recipe-regeneration.yml
- .yamato/wrench/validation-jobs.yml
- .yamato/wrench/wrench_config.json
- Tools/Cinemachine-Recipes/Cinemachine.Cookbook.csproj
- Tools/Cinemachine-Recipes/Recipes/CodeCoverage.cs
- Tools/Cinemachine-Recipes/Settings/CinemachineSettings.cs
Jira Ticket: [WBTR-1290](https://jira.unity3d.com/browse/WBTR-1290)
Since it is now compatible for repositories in github.com, this PR updates the code coverage jobs to use Unity's CodeCov reporting. This includes updating and regenerating Wrench jobs with version `0.12.2` in order to enable CodeCov and exclude tests in the report.
See [CodeCov dashboard](https://codecov.unity3d.com/gh/Unity-Technologies/com.unity.cinemachine/tree/ci%2Fcodecov-setup)
Technical Risk: None
Halo Effect: None
None.
> CMCL-0000: Update CodeCov Reporting and Integration

- com.unity.cinemachine/Editor/Editors/CinemachinePixelPerfectEditor.cs
- com.unity.cinemachine/Runtime/Behaviours/CinemachinePixelPerfect.cs
CMCL-1712: The main PixelPerfect Component is required for the extension to work correctly, so showing a warning when there is no such component detected is crucial for user experience.
0
> CMCL-1712: add helpboxes to PixelPerfect inspector

- com.unity.cinemachine/Runtime/Components/CinemachineOrbitalFollow.cs
- com.unity.cinemachine/Runtime/Components/CinemachinePositionComposer.cs
- com.unity.cinemachine/Runtime/Components/CinemachineRotationComposer.cs
CINE-984: RotationComposer damping fails when OrbitalFollow + LazyFollow.
This is a second PR to fix the issue, the first  (#1079) having been faulty.
low
> Fix rotation damping cancellation in orbital follow
