Unity-Technologies/com.unity.cinemachine

Runtime/Core/CameraState.cs, Runtime/PostProcessing/CinemachineVolumeSettings.cs
Fixed by removing Epsilon check for blend weight
(m_Weight > UnityVectorExtensions.Epsilon)
=> Fixed by adding all positive weights

Editor/Editors/CinemachineBlendListCameraEditor.cs, Editor/Editors/CinemachineBlenderSettingsEditor.cs, Editor/Editors/CinemachineBrainEditor.cs, Editor/Editors/CinemachineColliderEditor.cs, Editor/Editors/CinemachineConfinerEditor.cs, Editor/Editors/CinemachineExternalCameraEditor.cs, Editor/Editors/CinemachineFramingTransposerEditor.cs, Editor/Editors/CinemachineFreeLookEditor.cs, Editor/Editors/CinemachineGroupComposerEditor.cs, Editor/Editors/CinemachineMixingCameraEditor.cs, Editor/Editors/CinemachineNoiseSettingsEditor.cs, Editor/Editors/CinemachineOrbitalTransposerEditor.cs, Editor/Editors/CinemachinePathEditor.cs, Editor/Editors/CinemachineSmoothPathEditor.cs, Editor/Editors/CinemachineStateDrivenCameraEditor.cs, Editor/Editors/CinemachineTargetGroupEditor.cs, Editor/Editors/CinemachineTrackedDollyEditor.cs, Editor/Editors/CinemachineTransposerEditor.cs, Editor/Editors/CinemachineVirtualCameraBaseEditor.cs, Editor/EventHelpers/CinemachineTriggerActionEditor.cs, Editor/Experimental/CinemachineNewFreeLookEditor.cs, Editor/Timeline/CinemachineShotEditor.cs, Editor/Utility/BaseEditor.cs
Perfromance optimization: API change.
See BaseEditor.cs for the API change, all the rest is just refactoring for that.
=> cache excluded properties list, call once per inspector frame

Runtime/Behaviours/CinemachineStateDrivenCamera.cs
Fixed a couple spelling errors in CinemachineStateDrivenCamera.cs
Just coding away a custom version of State Driven Camera and saw some spelling errors. Being bored and with to much time on my hands I decided to make a pull request.
=> Function Summery fixes in StateDrivenCamera.cs

CHANGELOG.md, Extras~/ReleaseNotes.txt, Runtime/Behaviours/CinemachineConfiner.cs
Tested and seems like in both 2D and 3D modes, the jerk bug is there if we allow stages before Finalize.
What do you think?
=> Confiner jerk bug

CHANGELOG.md, Extras~/ReleaseNotes.txt, Runtime/Behaviours/CinemachineBlendListCamera.cs, Runtime/Behaviours/CinemachineClearShot.cs, Runtime/Behaviours/CinemachineFreeLook.cs, Runtime/Behaviours/CinemachineMixingCamera.cs, Runtime/Behaviours/CinemachineStateDrivenCamera.cs, Runtime/Behaviours/CinemachineVirtualCamera.cs, Runtime/Components/CinemachineComposer.cs, Runtime/Components/CinemachineFramingTransposer.cs, Runtime/Components/CinemachineOrbitalTransposer.cs, Runtime/Components/CinemachinePOV.cs, Runtime/Components/CinemachineTransposer.cs, Runtime/Core/CinemachineComponentBase.cs, Runtime/Core/CinemachineExtension.cs, Runtime/Core/CinemachineVirtualCameraBase.cs, Runtime/Experimental/CinemachineNewFreeLook.cs, Runtime/Experimental/CinemachineNewVirtualCamera.cs
This is an API to allow clients to manually initialize vcam position and orientation.  This has been requested multiple times on the forums.
=> Add ForceCameraPosition method to vcams

Runtime/Core/TargetPositionCache.cs
replace with custom implementation optimized for fixed step size
=> Remove AnimationCurves, 

CHANGELOG.md, Extras~/ReleaseNotes.txt, Runtime/Behaviours/CinemachineBrain.cs
https://fogbugz.unity3d.com/f/cases/1252431/
To fix this, I replaced the call to AnimationCurve.Linear every frame to a static variable.
=> Replaced direct call to AnimationCurve.Linear

CHANGELOG.md, Extras~/ReleaseNotes.txt, Runtime/Behaviours/CinemachineFreeLook.cs, Runtime/Behaviours/CinemachineVirtualCamera.cs, Runtime/Core/RuntimeUtility.cs
Fix for https://fogbugz.unity3d.com/f/cases/1260385/
=> bugfix (1260385): check for prefab instancess correctly

CHANGELOG.md, Extras~/ReleaseNotes.txt, Runtime/Behaviours/CinemachineConfiner.cs, Runtime/Behaviours/CinemachineVirtualCamera.cs, Runtime/Experimental/CinemachineNewVirtualCamera.cs
Fix for CMCL-107, reported here:
https://forum.unity.com/threads/confiner-impulse-listener-dont-play-nice-together.940029/#post-6159074
=> Regression fix: Confiner no longer confines noise and impulse

CHANGELOG.md, Extras~/ReleaseNotes.txt, Runtime/Components/CinemachineFramingTransposer.cs, Samples~/Cinemachine Example Scenes/Scenes/3rdPersonWithAimMode/3rdPersonWithAimMode.unity
Target Offset field requested by Adam.  Similar to Composer's target offset: focus on offset point instead of the target's root.  Updated 3rdPersonWithAimMode sample to make use of it.
=> Added Target Offset to Framing Transposer, updated sample

Editor/Editors/CinemachineVirtualCameraEditor.cs
Bug reported: https://fogbugz.unity3d.com/f/cases/1272146/
=> pipeline can be null, in that case we get an error in console

CHANGELOG.md, Extras~/ReleaseNotes.txt, Runtime/Behaviours/CinemachineBrain.cs
=> bugfix to handle edge case of deleted vcam

Runtime/Behaviours/CinemachineConfiner2D.cs, Runtime/Core/ConfinerOven.cs, Runtime/Core/ShrinkablePolygon.cs
Caching and preallocating a few more things.
Also minor cleanup.
Biggest change: ShrinkablePolygon.ComputeNormals()
=> Caching and preallocating a few more things

Editor/Timeline/CinemachineShotClipEditor.cs, Editor/com.unity.cinemachine.Editor.asmdef, Samples~/Nested Timeline Scrub Bubble/.sample.json
for timeline 1.5.0-preview.5 and up
=> Native timeline support for scrub bubble

Runtime/Behaviours/CinemachineConfiner2D.cs, Runtime/Core/ConfinerOven.cs, Runtime/Core/ShrinkablePolygon.cs
Pulled these out of ShrinkablePolygon, to save time and space. They are constant during a bake.
float m_AspectRatio;
float m_AspectRatioBasedDiagonal;
Vector2[] m_NormalDirections;
=> pulled m_NormalDirections etc out of ShrinkablePolygon, to save space

CHANGELOG.md, Runtime/Impulse/CinemachineImpulseManager.cs
Fix for https://fogbugz.unity3d.com/f/cases/1290171/
=> Bugfix (1290171) - Impulse manager was not cleared at playmode start

CHANGELOG.md, README.md
Synced changlog with Jira release for 2.7.2: https://jira.unity3d.com/projects/CMCL/versions/23420
Fixed typos in readme.
=> Updated changelog & readme for 2.7.2

Samples~/Cinemachine Example Scenes/Scenes/FadeOutNearbyObjects/CinemachineFadeOutNearbyObjects.cs
OnValidate added for shader script.
=> Shader example small fix

.yamato/package-promotion.yml, .yamato/package-publish.yml
use same versions, otherwise publish fails with a validation error
=> match unity versions and platforms used in packages-test.yml

CHANGELOG.md, package.json
* updated changelog to add missing bugfix and remove duplicate
* updated package.json version and description
=> 2.7.2-pre.2 updates

.yamato/package-test.yml
Fix CI by splitting editors & platforms into all/test/validate
=> fixed platforms for publish

.github/pull_request_template.md
Added checkbox for re-pack sample
=> [skip ci] add samples status section to PR template

CHANGELOG.md, QAReport.md, package.json
Update changelog, QAReport, package version for 2.7.2
=> [skip ci] updated changelog, QAReport, package version for 2.7.2

.gitignore
=> [skip ci] add .DS_Store to .gitignore

CHANGELOG.md
=> [skip ci] [2.6] Update CHANGELOG.md

CHANGELOG.md
=> [skip ci] [2.7] Update CHANGELOG.md

QAReport.md
=> [skip ci] updated QA report

package.json
=> [skip-ci] drop -pre from version

Documentation~/CinemachineStateDrivenCamera.md
CMCL-264
Added in some missing fields to the State Driven camera topic.
- [X ] Updated user documentation
=> DOC added missing fields to State Driven topic

appcollector.yaml
Adds Cinemachine to AppCollector for security evaluation. Required for package lifecycle v2.
=> added appcollector.yaml

.gitignore, .yamato/package-publish.yml, CHANGELOG.md, Documentation~/cinemachine.md, QAReport.md, Runtime/Core/CinemachineCore.cs, package.json
* stripped -pre and updated embedded versions to 2.7.3
* updated QA report
* match CI from master
* added .idea to .gitignore
=> 2.7.3 release prep

QAReport.md
Added QAReport.md for 2.8.0-exp.1
=> added QAReport.md for 2.8.0-exp.1

.github/CODEOWNERS
Adds CODEOWNERS:
* all .md files - Bryan
* QAReport.md - Patrick & Bryan
* all .cs files - Gregory and Krisztian
=> [skip ci] added CODEOWNERS

QAReport.md
=> Update QAReport for 2.8.0-pre.1

CHANGELOG.md
Forgot to add changelog to PR236.
=> PR236 changelog

.yamato/package-promotion.yml, .yamato/package-publish.yml, .yamato/package-test.yml, CHANGELOG.md, Runtime/Core/CinemachineCore.cs, package.json
Release prep for 2.7.4
Bug fixes only.
=> 2.7.4 release prep

CHANGELOG.md, Editor/Editors/CinemachineBrainEditor.cs, Runtime/Core/LensSettings.cs, Runtime/PostProcessing/CinemachinePostProcessing.cs, Runtime/PostProcessing/CinemachineVolumeSettings.cs
Backports CMCL-238 and CMCL-145.
=> 2.7/more backports

CHANGELOG.md, Editor/Editors/CinemachineBrainEditor.cs, Runtime/Core/LensSettings.cs, Runtime/PostProcessing/CinemachinePostProcessing.cs, Runtime/PostProcessing/CinemachineVolumeSettings.cs
Backports CMCL-238 and CMCL-145.
=> 2.6/more backports

.yamato/package-test.yml
added missing editor versions to yamato-test.yml
=> added missing editor versions

.npmignore, .yamato/package-test.yml, ValidationExceptions.json, ValidationExceptions.json.meta
Disabled API changed error in upm-ci validation (known packman bug)
=> disable API validation error until packman tooling is fixed

Runtime/Behaviours/CinemachineCollider.cs
Cleaned up cinemachine collider a bit.
- naming
- if to switch
- redundant privates
- unused parameters
- redundant default values
- static functions
Related to PR: https://github.com/Unity-Technologies/com.unity.cinemachine/pull/260
=> Cinemachine Collider Cleanups

CHANGELOG.md, Runtime/Behaviours/CinemachineBrain.cs, Tests/Runtime/CamerasBlendingTests.cs, Tests/Runtime/CamerasBlendingTests.cs.meta
Fix https://jira.unity3d.com/browse/CMCL-329
Blend Condition check was wrong, see my comment.
=> Blend condition bug

CHANGELOG.md, Samples~/Cinemachine Example Scenes/Scenes/AimingRig/AimReticle.cs, Samples~/Cinemachine Example Scenes/Scenes/AimingRig/AimReticle.cs.meta, Samples~/Cinemachine Example Scenes/Scenes/AimingRig/AimingRig.unity
https://jira.unity3d.com/secure/RapidBoard.jspa?rapidView=2427&projectKey=CMCL&selectedIssue=CMCL-331
Added a nicer reticle to the AimingRig example scene based on @yifei's project.
=> Nicer AimingRig scene

CHANGELOG.md, Runtime/Behaviours/CinemachineClearShot.cs, Runtime/Behaviours/CinemachineStateDrivenCamera.cs
To add Public API for clearshot blend progress. Requested by user
https://jira.unity3d.com/browse/CMCL-334
Low
=> Public API for clearshot blend progress

Runtime/Core/CinemachineDebug.cs, Runtime/Core/CinemachineVirtualCameraBase.cs
=> small extra cleanup

Documentation~/CinemachineVirtualCamera.md, Editor/Editors/CinemachineVirtualCameraBaseEditor.cs, Runtime/Core/LensSettings.cs
Help text, documentation, and tooltip update for vcam's Mode Override
=> Fix up Mode Override help text and doc

Editor/Editors/CinemachineBrainEditor.cs, Editor/Editors/CinemachineOrbitalTransposerEditor.cs, Editor/Editors/CinemachineTransposerEditor.cs, Editor/Editors/CinemachineVirtualCameraEditor.cs, Runtime/Behaviours/CinemachineBlendListCamera.cs, Runtime/Behaviours/CinemachineBrain.cs, Runtime/Behaviours/CinemachineClearShot.cs, Runtime/Behaviours/CinemachineFreeLook.cs, Runtime/Behaviours/CinemachineMixingCamera.cs, Runtime/Behaviours/CinemachineStateDrivenCamera.cs, Runtime/Behaviours/CinemachineVirtualCamera.cs, Runtime/Components/CinemachineFramingTransposer.cs, Runtime/Components/CinemachineOrbitalTransposer.cs, Runtime/Components/CinemachineTransposer.cs, Runtime/Core/CameraState.cs, Runtime/Core/CinemachineBlend.cs, Runtime/Core/CinemachineCore.cs, Runtime/Core/CinemachineDebug.cs, Runtime/Core/CinemachineVirtualCameraBase.cs, Runtime/Core/Predictor.cs, Runtime/Core/TargetPositionCache.cs, Runtime/Experimental/CinemachineNewFreeLook.cs, Runtime/Experimental/CinemachineNewVirtualCamera.cs, Runtime/Impulse/CinemachineImpulseManager.cs, Tests/Runtime/CamerasBlendingTests.cs
CMCL-330 - performance optimization
low
It's a benign API change only.  It should have no effect on client code.
=> convert a bunch of get/set to plain fields

CHANGELOG.md, Editor/Editors/CinemachineConfiner2DEditor.cs
=> add missing confiner2D warning

.yamato/package-test.yml
=> include release branches in CI

.yamato/package-coverage.yml, .yamato/package-test.yml
Enables code coverage on every PR
=> added code coverage on every PR

.gitignore
added .idea (JetBrains) to .gitignore
=> added .idea to .gitignore

Tests/Runtime/CameraPositionTests.cs, Tests/Runtime/CamerasBlendingTests.cs, Tests/Runtime/Confiner2DUnitTests.cs
Fix unstable tests by using explicit deltaTime.
=> use uniform delta to avoid indeterminism

Tests/Editor/AxisStateTests.cs, Tests/Editor/AxisStateTests.cs.meta
CMCL-344
Wrote some tests for AxisState (picked at random).
none
=> added some tests for AxisState

Tests/Runtime/StateDrivenCameraTests.cs, Tests/Runtime/StateDrivenCameraTests.cs.meta, Tests/Runtime/TestController.controller, Tests/Runtime/TestController.controller.meta
CMCL-345 
Creates a test for state-driven cameras.
Low
=> added basic test for StateDrivenCamera

.github/CODEOWNERS, .yamato/package-promotion.yml, .yamato/package-publish.yml, .yamato/package-test.yml, CHANGELOG.md, Documentation~/CinemachineVirtualCamera.md, Editor/Editors/CinemachineConfiner2DEditor.cs, Editor/Editors/CinemachineVirtualCameraBaseEditor.cs, Editor/PostProcessing/CinemachineVolumeSettingsEditor.cs, Runtime/Behaviours/Cinemachine3rdPersonAim.cs, Runtime/Behaviours/CinemachineBrain.cs, Runtime/Behaviours/CinemachineFreeLook.cs, Runtime/Components/Cinemachine3rdPersonFollow.cs, Runtime/Components/CinemachinePOV.cs, Runtime/Core/CameraState.cs, Runtime/Core/CinemachineCore.cs, Runtime/Core/CinemachinePathBase.cs, Runtime/Core/LensSettings.cs, Samples~/Cinemachine Example Scenes/Scenes/AimingRig/AimReticle.cs, Samples~/Cinemachine Example Scenes/Scenes/AimingRig/AimReticle.cs.meta, Samples~/Cinemachine Example Scenes/Scenes/AimingRig/AimingRig.unity, Tests/Runtime/CamerasBlendingTests.cs, Tests/Runtime/CamerasBlendingTests.cs.meta, package.json
Backports these commits:
- da920d2 include release branches in CI (#274)
- f1431cf Bugfix: Virtual Cameras were not updating in Edit mode when Brain's BlendUpdateMode was FixedUpdate. (#272)
- 4b72442 increased wait time to fix failing test on Linux (#273)
- 04e3ed9 changed docs owner to Seb
- 1e9d03c add missing confiner2D warning (#270)
- 24829af XML doc typos
- 826c67b Fix up Mode Override help text and doc (#268)
- 4f2bab7 Add info icon to lens override mode help box
- 3f42a29 CMCL-332-VCam control of physical camera properties (#266)
- ef82874 Nicer AimingRig scene (#264)
- 8d2501c Blend condition bug (#263)
- f8fd517 Bugfix: CinemachineVolumeSettings inspector was making the game view flicker, and warning msg (#261)
- 7b3ec4d ReferenceUp is not correct in CameraState Lerp (#256)
- …
=> Backports for 2.7.5

CHANGELOG.md, QAReport.md, package.json
Prep for 2.8.0 release
* updated QA report
* removed -pre.1 from 
=> added QA report, removed -pre.2 from versions

Tests/Runtime/CameraPositionTests.cs, Tests/Runtime/CamerasBlendingTests.cs, Tests/Runtime/CinemachineFixtureBase.cs, Tests/Runtime/ClearShotTests.cs, Tests/Runtime/ClearShotTests.cs.meta, Tests/Runtime/Confiner2DUnitTests.cs, Tests/Runtime/FreeLookTests.cs, Tests/Runtime/StateDrivenCameraTests.cs
CMCL-351
Added basic tests for ClearShot.
=> added tests for ClearShot

CHANGELOG.md, QAReport.md
added qa report
updated changelog date
=> 2.7.5 release prep

.yamato/package-promotion.yml, .yamato/package-publish.yml, .yamato/package-test.yml
Adds Unity 2021.2 to Yamato CI for all tests.
=> added 2021.2 editor to tests

Tests/Runtime/ClearShotTests.cs
=> Fix failing clearshot tests

Runtime/Impulse/CinemachineImpulseDefinition.cs, Runtime/Impulse/CinemachineImpulseListener.cs, Runtime/Impulse/CinemachineIndependentImpulseListener.cs
CMCL-368 - missing API doc for impulse
No code change
=> added missing XML doc

CHANGELOG.md, Runtime/Core/CinemachineVirtualCameraBase.cs
CMCL-371: GC allocs in UpdateTargetCache (performance regression)
low
=> CMCL-371: GC allocs in UpdateTargetCache

CHANGELOG.md, Runtime/Core/CinemachineCore.cs, Tests/Runtime/CamerasBlendingTests.cs, package.json
Bumps package version to 2.7.6
=> 2.7.6/update package version

CHANGELOG.md, Runtime/Core/CinemachineCore.cs, package.json
updates package version to 2.7.7
=> bumped package version to 2.7.7

Runtime/Components/Cinemachine3rdPersonFollow.cs
No issue, just a minor optimization in the code
=> minor optimization

.gitattributes, CHANGELOG.md, Documentation~/cinemachine.md, Editor/Editors/CinemachineTargetGroupEditor.cs, Runtime/Behaviours/CinemachineBrain.cs, Runtime/Behaviours/CinemachineTargetGroup.cs, Runtime/Components/Cinemachine3rdPersonFollow.cs, Runtime/Components/CinemachineFramingTransposer.cs, Runtime/Components/CinemachineGroupComposer.cs, Runtime/Components/CinemachinePOV.cs, Runtime/Core/AxisState.cs, Runtime/Core/CameraState.cs, Runtime/Core/CinemachineCore.cs, Runtime/Core/CinemachineVirtualCameraBase.cs, Runtime/Core/UnityVectorExtensions.cs, Runtime/Impulse/CinemachineImpulseDefinition.cs, Runtime/Impulse/CinemachineImpulseListener.cs, Runtime/Impulse/CinemachineIndependentImpulseListener.cs, package.json
Backports:
* CMCL-456
* CMCL-464
* CMCL-368
* CMCL-414
* CMCL-432
* CMCL-460
* low
Please check:
* no new APIs
* merge didn't transpose any preprocessor directives
* everything looks kosher
=> CMCL-479: [2.8.1] backports

Editor/Editors/CinemachineOrbitalTransposerEditor.cs, Editor/Editors/CinemachineTransposerEditor.cs, Runtime/Components/CinemachineTransposer.cs, Runtime/Experimental/CinemachineNewFreeLook.cs
Fix regression CMCL-495 "Hide Offset In Inspector"
low
Need to check unity versions published since Jun 8 2021
=> CMCL-495: "Hide Offset In Inspector" regression

.yamato/package-publish.yml
As part of the package signing initiative, we'd like bundled packages to be prepared for upcoming constraints regarding the need to have packages with a valid signature during APV testing.
Because of this, we are going through all bundled packages' repositories creating a PR that would enable package signing on your packages.
With signing enabled, upm-ci will perform an extra step where it will send each package to a signing service and then generate the final signed artifacts.
Internally, in an attempt to ensure that everything works, we are running yamato tests where all bundled packages (including yours) are signed and validated, proving that the packages in this repository should yield no errors. The validation step is also performed in all platforms.
In the case that any error does …
=> CMCL-522: Package Signature on CI

.gitattributes, CHANGELOG.md, Editor/Editors/CinemachineTargetGroupEditor.cs, Runtime/Behaviours/CinemachineBrain.cs, Runtime/Behaviours/CinemachineTargetGroup.cs, Runtime/Components/Cinemachine3rdPersonFollow.cs, Runtime/Components/CinemachineFramingTransposer.cs, Runtime/Components/CinemachineGroupComposer.cs, Runtime/Components/CinemachinePOV.cs, Runtime/Core/AxisState.cs, Runtime/Core/CameraState.cs, Runtime/Core/CinemachineCore.cs, Runtime/Core/UnityVectorExtensions.cs, package.json
CMCL-456
CMCL-464
CMCL-414
CMCL-432
CMCL-460
Low
Please check for anything suspicious: changed public API, bad merges, etc.
=> CMCL-503: Backports for 2.7.9

Documentation~/handles.md
=> CMCL-436: Handles Doc- Minor formatting change

Editor/Editors/Cinemachine3rdPersonFollowEditor.cs, Editor/Editors/CinemachineBrainEditor.cs, Editor/Editors/CinemachineFramingTransposerEditor.cs, Editor/Experimental/CinemachineNewFreeLookEditor.cs, Editor/Utility/CinemachineSceneTools.cs, Editor/Windows/CinemachineSettings.cs
https://jira.unity3d.com/browse/CMCL-618
Design update for handles
=> CMCL-618: Implement new design requirements

Editor/Utility/VcamStageEditor.cs, Runtime/Behaviours/CinemachineVirtualCamera.cs
CMCL-661: remove illegal destructor.  Replaced with explicit call to Shutdown() where it was needed.
low
Create a vcam, change various parts of the pipeline (Body, Aim, Noise) to different items in the dropdowns.  Be sure to test Do Nothing also.  Test undo/redo.  Try lots of combinations.  Try to break it.  Keep an eye on the console for exceptions.
=> CMCL-661: remove illegal destructor

Runtime/Behaviours/CinemachineCollider.cs, Tests/Runtime/CinemachineFixtureBase.cs
Backport for https://jira.unity3d.com/browse/CMCL-646 -> https://jira.unity3d.com/browse/CMCL-648
Tested in editor version 2022.1.
=> CMCL-648: backport

CHANGELOG.md
Added missing changelog entry for CMCL-646.
=> CMCL-646: Missing changelog entry

CHANGELOG.md
Added missing changelog for https://jira.unity3d.com/browse/CMCL-667
=> CMCL-664: missing changelog

CHANGELOG.md, Editor/Utility/VcamStageEditor.cs, Runtime/Behaviours/CinemachineCollider.cs, Runtime/Behaviours/CinemachineConfiner2D.cs, Runtime/Behaviours/CinemachineVirtualCamera.cs, Runtime/Components/Cinemachine3rdPersonFollow.cs, Runtime/Core/CinemachineCore.cs, Runtime/Core/CinemachineVirtualCameraBase.cs, Runtime/Helpers/CinemachineInputProvider.cs, Tests/Runtime/CinemachineFixtureBase.cs, ValidationExceptions.json, package.json
backports for CMCL-664, CMCL-661, CMCL-686, CMCL-646, CMCL-706, CMCL-710
=> CMCL-690: 2.8.4 backports

CHANGELOG.md
=> CMCL-722: release prep for 2.9.0-pre.2

CHANGELOG.md, Editor/Windows/CinemachineSettings.cs
Fix for https://jira.unity3d.com/browse/CMCL-757.
Standalone profiler can freeze.
=> CMCL-757: Standalone profiler freezes

.gitignore, .npmignore, .yamato/metadata.metafile, .yamato/package-ci.yml, .yamato/package-coverage.yml, .yamato/package-test.yml, codecov.yml, codecov.yml.meta
CMCL-767 
Add codecov.io upload as described in this document: https://docs.google.com/document/d/1ndxNv7_XS-EokCgi4kFyw3-irsPb7SAb68FGjz1IF44/edit# (but using public instance instead of self-hosted test instance).
=> CMCL-767: added codecov.io upload

Editor/Editors/CinemachineSplineDollyEditor.cs, Runtime/Components/CinemachineSplineDolly.cs
Add railroad-track visualization to CM SplineDolly.
It's a crude first stab - colors and sizes need to be not hardcoded.
I think it helps with the roll visualization.
It also helps with testing.
=> add visualization - wip needs to be configurable

CHANGELOG.md, Editor/Utility/SaveDuringPlay.cs
Fix for https://jira.unity3d.com/browse/CMCL-822. SaveDuringPlay works for lists.
0
=> CMCL-822: SaveDuringPlay for ILists

Runtime/Core/CinemachineCore.cs
https://jira.unity3d.com/browse/CMCL-820
=> CMCL-820: Remove unused kVersionString

Editor/Editors/CinemachineSplineDollyEditor.cs, Runtime/Components/CinemachineSplineDolly.cs, Tests/Runtime/SplineDollyCameraTest.cs
Simplifies spline dolly inspector script - https://jira.unity3d.com/browse/CMCL-743.
Some other changes:
-  before damping we check if damping is enabled. 
- fixed minor bug - if no spline was attached RollCache threw an error
- fixed dolly tests (which caught the bug above, so they deserve a kind pat 🐶 )
Design doc:
https://www.figma.com/file/SjDhnBdCiaHIIeEMSNLPfw/UX-Improvements?node-id=201%3A2
=> CMCL-743: Simplify SplineDolly editor

CHANGELOG.md, Runtime/PostProcessing/CinemachinePostProcessing.cs
https://jira.unity3d.com/browse/CMCL-842
I can add this in 2.6.12, because I need to add https://github.com/Unity-Technologies/com.unity.cinemachine/pull/416 too anyway.
- [] Updated package version
=> Backports for 2.6

Documentation~/Cinemachine3rdPersonAim.md, Documentation~/CinemachineAimComposer.md, Documentation~/CinemachineBodyOrbitalTransposer.md, Documentation~/CinemachineVirtualCamera.md, Documentation~/TableOfContents.md, Documentation~/cinemachine.md, Documentation~/handles.md
=> CMCL-867: General Language improvements and Handles doc updates

com.unity.cinemachine/CHANGELOG.md, com.unity.cinemachine/Runtime/Helpers/CinemachineInputProvider.cs
=> CMCL-870: add auto-enable option to input handler

com.unity.cinemachine/Editor/Editors/CinemachineVirtualCameraBaseEditor.cs, com.unity.cinemachine/Editor/PropertyDrawers/LensSettingsPropertyDrawer.cs, com.unity.cinemachine/Editor/Utility/CinemachineLensPresets.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachineBrain.cs, com.unity.cinemachine/Runtime/Core/LensSettings.cs, com.unity.cinemachine/package.json
Upgrade obsolete camera API for HDRP.
Minimum Unity version is now 2022.2
=> CMCL-0000: Min Unity version is 2022.2, upgrade HDRP camera API

com.unity.cinemachine/Editor/Utility/VcamStageEditor.cs
Initialize editor using class attributes instead of creating a temp gameobject adding all components to check stage.
=> CMCL-0000: class attributes for editor init

CHANGELOG.md, Runtime/Behaviours/CinemachineFreeLook.cs, Runtime/Core/CinemachineCore.cs, Runtime/Helpers/CinemachineInputProvider.cs, package.json
Backports for:
https://jira.unity3d.com/browse/CMCL-960
https://jira.unity3d.com/browse/CMCL-923
=> CMCL-962: Release 2.6.15

com.unity.cinemachine/CHANGELOG.md, com.unity.cinemachine/Runtime/Components/CinemachineComposer.cs, com.unity.cinemachine/Runtime/Components/CinemachineFramingTransposer.cs
[CMCL-976](https://jira.unity3d.com/browse/CMCL-976)
=> CMCL-976: FT and Composer rounding error

CHANGELOG.md, Runtime/Core/CameraState.cs
=> CMCL-982: spurious z rotations

com.unity.cinemachine/CHANGELOG.md, com.unity.cinemachine/Runtime/Behaviours/CinemachineFreeLook.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachineVirtualCamera.cs, com.unity.cinemachine/Runtime/Core/CinemachineVirtualCameraBase.cs, com.unity.cinemachine/Runtime/Experimental/CinemachineNewFreeLook.cs, com.unity.cinemachine/Runtime/Experimental/CinemachineNewVirtualCamera.cs
Backport of https://jira.unity3d.com/browse/CMCL-1003 from master branch.
=> CMCL-930: backport of CMCL-1003 - aspect ratio affects source control

com.unity.cinemachine/Runtime/PostProcessing/CinemachineVolumeSettings.cs
=> CMCL-0000: minor fix for yamato fail

com.unity.cinemachine/Editor/Impulse/CinemachineImpulseDefinitionPropertyDrawer.cs, com.unity.cinemachine/Editor/Impulse/CinemachineImpulseEnvelopePropertyDrawer.cs, com.unity.cinemachine/Runtime/Impulse/CinemachineCollisionImpulseSource.cs, com.unity.cinemachine/Runtime/Impulse/CinemachineFixedSignal.cs, com.unity.cinemachine/Runtime/Impulse/CinemachineImpulseDefinition.cs, com.unity.cinemachine/Runtime/Impulse/CinemachineImpulseListener.cs, com.unity.cinemachine/Runtime/Impulse/CinemachineImpulseManager.cs, com.unity.cinemachine/Runtime/Impulse/CinemachineImpulseSource.cs, com.unity.cinemachine/Runtime/Impulse/CinemachineIndependentImpulseListener.cs
CMCL-1067: impulse API cleanup
Remove m_ from public members
=> CMCL-1067: impulse API cleanup

com.unity.cinemachine/Editor/Editors/CinemachineBlenderSettingsEditor.cs, com.unity.cinemachine/Editor/Editors/CinemachineBrainEditor.cs, com.unity.cinemachine/Editor/Editors/CinemachineColliderEditor.cs, com.unity.cinemachine/Editor/Editors/CinemachinePositionComposerEditor.cs, com.unity.cinemachine/Editor/Helpers/CinemachineTriggerActionEditor.cs, com.unity.cinemachine/Runtime/Behaviours/Cinemachine3rdPersonAim.cs, com.unity.cinemachine/Runtime/PostProcessing/CinemachineVolumeSettings.cs
Couple of small changes (variable naming, removed redundant modifiers...)
=> CMCL-1066: 2

com.unity.cinemachine/Editor/Editors/CinemachineClearShotEditor.cs, com.unity.cinemachine/Editor/Editors/CinemachineColliderEditor.cs, com.unity.cinemachine/Editor/Editors/CinemachineConfiner2DEditor.cs, com.unity.cinemachine/Editor/Editors/CinemachineConfinerEditor.cs, com.unity.cinemachine/Editor/Editors/CinemachineStoryboardEditor.cs, com.unity.cinemachine/Editor/Menus/CinemachineMenu.cs, com.unity.cinemachine/Runtime/Behaviours/Cinemachine3rdPersonAim.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachineBlendListCamera.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachineCameraOffset.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachineCollider.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachineConfiner.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachineConfiner2D.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachineFollowZoom.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachineRecomposer.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachineSplineRoll.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachineStoryboard.cs, com.unity.cinemachine/Tests/Runtime/ClearShotTests.cs, com.unity.cinemachine/Tests/Runtime/CmColliderTests.cs, com.unity.cinemachine/Tests/Runtime/Confiner2DUnitTests.cs
CMCL-1074: Cleanup API for extensions
- Remove m_ from members in remaining CM extensions
- coding style
- Focus was on public members, there may be some leftover things that we can look at in another pass
=> CMCL-1074: API upgrade for extensions

com.unity.cinemachine/Editor/Editors/Cinemachine3rdPersonFollowEditor.cs, com.unity.cinemachine/Editor/Editors/CinemachineBlendListCameraEditor.cs, com.unity.cinemachine/Editor/Editors/CinemachineStateDrivenCameraEditor.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachineBlendListCamera.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachineClearShot.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachineMixingCamera.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachineStateDrivenCamera.cs, com.unity.cinemachine/Runtime/Core/CinemachineCameraManagerBase.cs
Related to PR: https://github.com/Unity-Technologies/com.unity.cinemachine/pull/509/files#diff-b4fad7af055b5617dabcd9f88a4ee7ad8218ba2ecb061a8b0fb803114edd718aR227-R242
- Simplified ThirdPersonFollowEditor handle code
- Fixed a couple of typos (it's simpler/faster to fix them right away than to note them in PR review)
- Changed a couple of types to vars
- Array.Empty instead of [0]
=> CMCL-0000: couple of cleanups

.yamato/metadata.metafile
=> Remove unsupported Editor versions from the automated tests configuration 

com.unity.cinemachine/Editor/Editors/InputAxisControllerEditor.cs, com.unity.cinemachine/Runtime/Core/InputAxis.cs, com.unity.cinemachine/Runtime/Helpers/InputAxisController.cs, com.unity.cinemachine/Samples~/Cinemachine Example Scenes/Scenes/Anywhere Door/Anywhere Door.unity, com.unity.cinemachine/Samples~/Cinemachine Example Scenes/Scenes/BossCamera/BossCam.unity, com.unity.cinemachine/Samples~/Cinemachine Example Scenes/Scenes/BossCamera/BossLookAt.cs
Some cosmetic fixes:
- BossCam scene - simplified BossLookAt script. Boss looks at player. Removed colliders from boss.
- Some vars instead of types
- naming typos
- Anywhere Door scene portals where not working correctly, because the worlds got rotated.
=> CMCL-733: Some cosmetic fixes

com.unity.cinemachine/CHANGELOG.md, com.unity.cinemachine/Runtime/Components/CinemachineTransposer.cs
=> CMCL-1163: transposer damping bug when moving in loop

CHANGELOG.md, Runtime/Components/CinemachineTransposer.cs
=> CMCL-1162: transposer tamping bug when moving in loop

com.unity.cinemachine/Editor/Editors/CinemachineVirtualCameraBaseEditor.cs, com.unity.cinemachine/Editor/Obsolete/CinemachineDollyCartEditor.cs, com.unity.cinemachine/Editor/Obsolete/CinemachineDollyCartEditor.cs.meta, com.unity.cinemachine/Editor/Obsolete/CinemachineFreeLookEditor.cs, com.unity.cinemachine/Editor/Obsolete/CinemachinePathEditor.cs, com.unity.cinemachine/Editor/Obsolete/CinemachineSmoothPathEditor.cs, com.unity.cinemachine/Editor/Obsolete/CinemachineVirtualCameraEditor.cs, com.unity.cinemachine/Editor/Upgrader/CinemachineUpgradeManager.cs, com.unity.cinemachine/Editor/Upgrader/UpgradeManagerInspectorHelpers.cs, com.unity.cinemachine/Editor/Upgrader/UpgradeManagerInspectorHelpers.cs.meta
So we can upgrade paths and dollycarts easily.
Also added "Upgrade all objects in scene" function
=> CMCL-0000: add upgrade buttons to all relevant inspectors

com.unity.cinemachine/CHANGELOG.md, com.unity.cinemachine/Runtime/Behaviours/CinemachineCollider.cs, com.unity.cinemachine/Runtime/Components/CinemachinePOV.cs
- [CMCL-1057](https://jira.unity3d.com/browse/CMCL-1057) (has repro project) - https://github.com/Unity-Technologies/com.unity.cinemachine/pull/535
=> CMCL-0000: 2.9.1 release

CHANGELOG.md, Runtime/Behaviours/CinemachineCollider.cs, Runtime/Components/CinemachinePOV.cs, Runtime/Core/CinemachineCore.cs, ValidationExceptions.json, package.json
- [CMCL-1057](https://jira.unity3d.com/browse/CMCL-1057) (has repro project) - [749544e](https://github.com/Unity-Technologies/com.unity.cinemachine/pull/537/commits/749544e6122253ccfaaa86bbb8888c3d5ac6b429)
=> CMCL-0000: 2.8.9 release

com.unity.cinemachine/Tests/Runtime/CmColliderTests.cs
Backport of unit test fix from https://github.com/Unity-Technologies/com.unity.cinemachine/pull/538
=> CMCL-0000: fix collider unit test

com.unity.cinemachine/Editor/Upgrader/CinemachineUpgradeManager.cs, com.unity.cinemachine/Editor/Upgrader/UpgradeObjectToCm3.Data.cs, com.unity.cinemachine/Editor/Upgrader/UpgradeObjectToCm3.cs, com.unity.cinemachine/Editor/Utility/ReflectionHelpers.cs
Use reflection to fix up references of upgraded MonoBehaviours
=> CMCL-0000: Ugrader upgrades references using reflection

com.unity.cinemachine/Editor/Editors/CinemachineVirtualCameraBaseEditor.cs, com.unity.cinemachine/Editor/PostProcessing/CinemachineVolumeSettingsEditor.cs, com.unity.cinemachine/Editor/PropertyDrawers/LensSettingsPropertyDrawer.cs, com.unity.cinemachine/Editor/Utility/CinemachineLensPresets.cs, com.unity.cinemachine/Editor/com.unity.cinemachine.Editor.asmdef, com.unity.cinemachine/Runtime/Behaviours/CinemachineBrain.cs, com.unity.cinemachine/Runtime/Core/LensSettings.cs, com.unity.cinemachine/Runtime/PostProcessing/CinemachineVolumeSettings.cs, com.unity.cinemachine/Runtime/com.unity.cinemachine.asmdef
Minimum HDRP version is now 14.0.  Simpler code.
=> CMCL-0000: minimum HDRP version is 14.0.0

com.unity.cinemachine/Editor/Editors/CinemachineBrainEditor.cs, com.unity.cinemachine/Editor/Overlays/CinemachineToolbarOverlay.cs, com.unity.cinemachine/Editor/PostProcessing/CinemachineAutoFocusEditor.cs, com.unity.cinemachine/Editor/PostProcessing/CinemachinePostProcessingEditor.cs, com.unity.cinemachine/Editor/Utility/CinemachineSceneTools.cs, com.unity.cinemachine/Editor/Utility/InspectorUtility.cs, com.unity.cinemachine/Editor/Utility/ScriptableObjectUtility.cs, com.unity.cinemachine/Editor/Windows/CinemachineSettings.cs, com.unity.cinemachine/Editor/Windows/WaveformWindow.cs, com.unity.cinemachine/Tests/Editor/ScriptableObjectUtilityTests.cs
Remove obsolete stuff from when CM was on the asset store
=> CMCL-0000: cleanup ScriptableObjectUtility API

com.unity.cinemachine/Editor/Overlays/SplineRollTool.cs
[CMCL-1145](https://jira.unity3d.com/browse/CMCL-1145)
Change color of spline tools to be consistent with other cm tools.
=> CMCL-1145: spline tool color

com.unity.cinemachine/CHANGELOG.md, com.unity.cinemachine/Editor/Windows/CinemachineColliderPrefs.cs, com.unity.cinemachine/Editor/Windows/CinemachineComposerPrefs.cs, com.unity.cinemachine/Editor/Windows/CinemachineCorePrefs.cs, com.unity.cinemachine/Editor/Windows/CinemachineSettings.cs, com.unity.cinemachine/Editor/Windows/CinemachineSplineDollyPrefs.cs
=> CMCL-0000: cleanups

com.unity.cinemachine/package.json
[CMCL-1114](https://jira.unity3d.com/browse/CMCL-1114)
Splines min version set to pre4
=> CMCL-1114: Splines min version

com.unity.cinemachine/Editor/Editors/CinemachineBlendListCameraEditor.cs, com.unity.cinemachine/Editor/Editors/CinemachineClearShotEditor.cs, com.unity.cinemachine/Editor/Editors/CinemachineStateDrivenCameraEditor.cs, com.unity.cinemachine/Editor/Menus/CinemachineMenu.cs, com.unity.cinemachine/Editor/Timeline/CinemachineShotClipEditor.cs, com.unity.cinemachine/Editor/Timeline/CinemachineShotEditor.cs, com.unity.cinemachine/Editor/Windows/CinemachineTimelinePrefs.cs, com.unity.cinemachine/Editor/Windows/CinemachineTimelinePrefs.cs.meta
Move timeline settings to a panel in preferences
Also some renaming Virtual Camera -> CmCamera
=> CMCL-0000: Add timeline prefs panel, move relevant settings there

com.unity.cinemachine/Runtime/Components/CinemachineOrbitalFollow.cs, com.unity.cinemachine/Tests/Runtime/FreelookForcePositionTests.cs
Cleanup and optimization.
Easier to just do it than to write comments.
In tests, step==5 was still taking too long.  Bumped it up to 29.
=> CMCL-0000: Dev/freelook forceposition cleanup opt

com.unity.cinemachine/package.json
Min version is 2022.2.0b8 to be compatible with splines.pre4.
=> CMCL-0000: min version 2022.2.0b8

com.unity.cinemachine/Editor/Editors/CinemachineClearShotEditor.cs, com.unity.cinemachine/Editor/Editors/CinemachineOrbitalFollowEditor.cs, com.unity.cinemachine/Editor/Editors/CinemachinePanTiltEditor.cs, com.unity.cinemachine/Editor/Editors/CinemachineVirtualCameraBaseEditor.cs, com.unity.cinemachine/Editor/Editors/CmCameraEditor.cs, com.unity.cinemachine/Editor/Helpers/CinemachineTriggerActionEditor.cs, com.unity.cinemachine/Editor/Impulse/CinemachineCollisionImpulseSourceEditor.cs, com.unity.cinemachine/Editor/Overlays/CinemachineToolbarOverlay.cs, com.unity.cinemachine/Editor/PropertyDrawers/CameraTargetPropertyDrawer.cs, com.unity.cinemachine/Editor/PropertyDrawers/VcamTargetPropertyDrawer.cs, com.unity.cinemachine/Editor/Timeline/CinemachineShotClipEditor.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachineSplineCart.cs, com.unity.cinemachine/Runtime/Behaviours/CmCamera.cs, com.unity.cinemachine/Runtime/Core/CinemachineBlend.cs, com.unity.cinemachine/Runtime/Core/CinemachineComponentBase.cs, com.unity.cinemachine/Runtime/Helpers/CinemachineTriggerAction.cs, com.unity.cinemachine/Runtime/Helpers/GroupWeightManipulator.cs, com.unity.cinemachine/Runtime/Impulse/CinemachineCollisionImpulseSource.cs, com.unity.cinemachine/Runtime/PostProcessing/CinemachineVolumeSettings.cs
Performance: Use TryGetComponent instead of GetComponent to avoid GC allocs
=> CMCL-0000: Use TryGetComponent where appropriate

com.unity.cinemachine/Documentation~/CmCamera.md, com.unity.cinemachine/Editor/Editors/CinemachineExternalCameraEditor.cs, com.unity.cinemachine/Editor/Upgrader/UpgradeObjectToCm3.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachineBlendListCamera.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachineClearShot.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachineExternalCamera.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachineStateDrivenCamera.cs, com.unity.cinemachine/Runtime/Behaviours/CmCamera.cs, com.unity.cinemachine/Runtime/Core/CinemachineCore.cs, com.unity.cinemachine/Runtime/Core/CinemachineVirtualCameraBase.cs, com.unity.cinemachine/Runtime/Deprecated/CinemachineFreeLook.cs, com.unity.cinemachine/Runtime/Deprecated/CinemachineVirtualCamera.cs
Transitions API improvements:
- BlendHint is now multi-select flags
- InheritPosition is one of the flags instead of being separate bool
- Added Events foldout to hide the camera activation event
=> CMCL-0000: new Transitions API

com.unity.cinemachine/Samples~/Sample Scenes/Shared/Materials/BulletMaterial.mat, com.unity.cinemachine/Samples~/Sample Scenes/Shared/Materials/BulletMaterial.mat.meta, com.unity.cinemachine/Samples~/Sample Scenes/Shared/Prefabs/Bullet.prefab, com.unity.cinemachine/Samples~/Sample Scenes/Shared/Scripts/SimpleBullet.cs, com.unity.cinemachine/Samples~/Sample Scenes/Shared/Scripts/SimplePlayerAimController.cs, com.unity.cinemachine/Samples~/Sample Scenes/Shared/Scripts/SimplePlayerShoot.cs, com.unity.cinemachine/Samples~/Sample Scenes/ThirdPerson Shooter.unity
Rotate player when firing to face the shooting direction
=> CMCL-0000: shooter sample player faces shoot direction

com.unity.cinemachine/Runtime/Core/CameraState.cs, com.unity.cinemachine/Runtime/Core/TargetTracking.cs, com.unity.cinemachine/Runtime/Core/UnityVectorExtensions.cs
Extension methods for structs that wrote to the struct were writing copies of the struct.
PostProcessing had stopped working because of this.
=> CMCL-0000: extension methods on structs were wrong

com.unity.cinemachine/Runtime/ThirdParty/Clipper.Core.cs, com.unity.cinemachine/Runtime/ThirdParty/Clipper.Engine.cs, com.unity.cinemachine/Runtime/ThirdParty/Clipper.Minkowski.cs, com.unity.cinemachine/Runtime/ThirdParty/Clipper.Offset.cs, com.unity.cinemachine/Runtime/ThirdParty/clipper.cs
https://jira.unity3d.com/browse/CMCL-1222
I accidentally exposed a lot of clipper2 API again. This PR fixes that.
=> CMCL-1222: Make Clipper 2 internal again

com.unity.cinemachine/Editor/Overlays/SplineRollTool.cs
https://jira.unity3d.com/browse/CMCL-1223
Fix taken from splines team fix - https://github.cds.internal.unity3d.com/unity/com.unity.splines/pull/234.
=> CMCL-1223: Fix roll tool flicker

com.unity.cinemachine/Editor/Editors/CinemachineGroupFramingEditor.cs, com.unity.cinemachine/Editor/Editors/CinemachinePositionComposerEditor.cs, com.unity.cinemachine/Editor/Editors/CinemachineRotationComposerEditor.cs, com.unity.cinemachine/Editor/Obsolete/CinemachineComposerEditor.cs, com.unity.cinemachine/Editor/Obsolete/CinemachineFramingTransposerEditor.cs, com.unity.cinemachine/Editor/Upgrader/UpgradeObjectToCm3.cs, com.unity.cinemachine/Editor/Utility/CinemachineScreenComposerGuides.cs, com.unity.cinemachine/Editor/Utility/CmCameraInspectorUtility.cs, com.unity.cinemachine/Editor/Utility/CmPipelineComponentInspectorUtility.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachineBrain.cs, com.unity.cinemachine/Runtime/Core/ScreenComposerSettings.cs, com.unity.cinemachine/Runtime/Deprecated/CinemachineComposer.cs, com.unity.cinemachine/Runtime/Deprecated/CinemachineFramingTransposer.cs
Requested by Adam: show the group size in the game view.
Stole the code from CM.DOTS.
=> CMCL-0000: Draw group size indicator in game view

com.unity.cinemachine/Editor/Timeline/CinemachineTrackEditor.cs
=> CMCL-0000: timeline guards for cm track

com.unity.cinemachine/Documentation~/CinemachineDeoccluder.md, com.unity.cinemachine/Documentation~/CinemachineUpgradeFrom2.md
**-** Quick Language and grammar pass for Upgrade text
=> CMCL-994 - Upgrade doc check.

com.unity.cinemachine/Runtime/Core/CameraState.cs, com.unity.cinemachine/Runtime/Core/CinemachineVirtualCameraBase.cs, com.unity.cinemachine/Runtime/Core/OutputChannel.cs
[CMCL-1226](https://jira.unity3d.com/browse/CMCL-1226): Missing docs
=> CMCL-1226: Missing docs

com.unity.cinemachine/Runtime/Core/ScreenComposerSettings.cs, com.unity.cinemachine/Runtime/Core/SplineAutoDolly.cs, com.unity.cinemachine/Runtime/Deprecated/AxisState.cs, com.unity.cinemachine/Runtime/Deprecated/CinemachineVirtualCamera.cs
[CMCL-1229](https://jira.unity3d.com/browse/CMCL-1229): Some more missing docs
Not all docs marked as missing are valid. I marked them in the Jira ticket's description
=> CMCL-1229: More docs

com.unity.cinemachine/Editor/Editors/CinemachineGroupFramingEditor.cs, com.unity.cinemachine/Editor/Editors/CinemachinePositionComposerEditor.cs, com.unity.cinemachine/Editor/Editors/CinemachineRotationComposerEditor.cs, com.unity.cinemachine/Editor/Obsolete/CinemachineComposerEditor.cs, com.unity.cinemachine/Editor/Obsolete/CinemachineFramingTransposerEditor.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachineBrain.cs, com.unity.cinemachine/Runtime/Core/CinemachineCameraManagerBase.cs, com.unity.cinemachine/Runtime/Core/CinemachineDebug.cs
Debug text appears in the relevant screen area
=> CMCL-0000: cleanup CinemachineDebug so it works for splitscreen

com.unity.cinemachine/Editor/PropertyDrawers/SplineAutoDollyPropertyDrawer.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachineSplineCart.cs, com.unity.cinemachine/Runtime/Components/CinemachineSplineDolly.cs, com.unity.cinemachine/Runtime/Core/CinemachinePropertyAttribute.cs, com.unity.cinemachine/Runtime/Core/SplineAutoDolly.cs, com.unity.cinemachine/Runtime/Deprecated/CinemachineDollyCart.cs, com.unity.cinemachine/Runtime/Deprecated/CinemachineTrackedDolly.cs
SplineAutoDollyPropertyDrawer now in UITK .
~It behaves a little better than IMGUI implementation in 2022.2.0a8, and a little bit worse in 2023.1.0a13~ 
~UITK bug logged: [UUM-17582](https://jira.unity3d.com/browse/UUM-17582)~
works properly
=> CMCL-0000: UITK implementation of AutoDolly PropertyDrawer

com.unity.cinemachine/Samples~/Old Samples from CM2/.sample.json, com.unity.cinemachine/Samples~/Sample Scenes/.sample.json
The promotion tests are not passing because we are missing a sample.json. 
Promotion tests are passing when passing variable PROMOTION = 0.
=> Fix promotion tests with new sample.json

com.unity.cinemachine/Samples~/Sample Scenes/Brain Update Modes.unity, com.unity.cinemachine/Samples~/Sample Scenes/Brain Update Modes.unity.meta, com.unity.cinemachine/Samples~/Sample Scenes/FreeLook on Spherical Surface.unity, com.unity.cinemachine/Samples~/Sample Scenes/FreeLook.unity, com.unity.cinemachine/Samples~/Sample Scenes/Shared/Scripts/CameraPrioritizerGUI.cs, com.unity.cinemachine/Samples~/Sample Scenes/Shared/Scripts/CameraPrioritizerGUI.cs.meta, com.unity.cinemachine/Samples~/Sample Scenes/Shared/Scripts/SamplesHelpText.cs, com.unity.cinemachine/Samples~/Sample Scenes/Shared/Scripts/WrapAround.cs, com.unity.cinemachine/Samples~/Sample Scenes/Shared/Scripts/WrapAround.cs.meta
Attempt to address the frequent questions about brain update mode.  What is it for?  What does it do?  How do you get rid of the jitter?
=> CMCL-0000: Added Brain Update Modes sample scene

com.unity.cinemachine/CHANGELOG.md, com.unity.cinemachine/Runtime/Core/LensSettings.cs
Fix incredibly stupid lens blending bug.
Also: add missing FocusDistance to lends blending, initialization, and validation (HDRP only)
=> CMCL-0000: lens blending bugfix

com.unity.cinemachine/Runtime/Core/UnityVectorExtensions.cs
Couple of small/minor fixes I encountered.
=> CMCL-0000: Small fixes

com.unity.cinemachine/CHANGELOG.md, com.unity.cinemachine/Documentation~/CinemachineDeoccluder.md, com.unity.cinemachine/Editor/Editors/CinemachineDeoccluderEditor.cs, com.unity.cinemachine/Editor/Editors/CinemachineThirdPersonFollowEditor.cs, com.unity.cinemachine/Editor/Menus/CinemachineMenu.cs, com.unity.cinemachine/Editor/Upgrader/UpgradeObjectToCm3.Data.cs, com.unity.cinemachine/Editor/Upgrader/UpgradeObjectToCm3.cs, com.unity.cinemachine/Runtime/Components/CinemachineThirdPersonFollow.cs, com.unity.cinemachine/Runtime/Deprecated/Cinemachine3rdPersonFollow.cs, com.unity.cinemachine/Runtime/Deprecated/CinemachineCollider.cs, com.unity.cinemachine/Runtime/Deprecated/CinemachineCollider.cs.meta, com.unity.cinemachine/Samples~/Sample Scenes/ThirdPerson Shooter.unity, com.unity.cinemachine/Tests/Runtime/CmColliderTests.cs
- CMCL-1233: Expose settings for optimal target distance algorithm
- Use FoldoutWithEnabledButton for AvoidObstacles and ShotQuality sections of Deoccluder.
- This implies a large enough API change that old CinemachineCollider had to be resurrected, and proper support given in upgrader.
- Also: Deoccludr editor now in UITK
- Also: ThirdPersonFollow.Obstacles renamed to ThirdPersonFollow.AvoidObstacles for consistency with deoccluder.
- Also: fixed ThirdPersonFollow editor compile error if no physics
=> CMCL-1233: expose settings for optimal target distance algorithm

com.unity.cinemachine/CHANGELOG.md, com.unity.cinemachine/ValidationExceptions.json, com.unity.cinemachine/package.json
=> Release prep/2.9.3

com.unity.cinemachine/Editor/PropertyDrawers/InputAxisNamePropertyDrawer.cs
Added ENABLE_LEGACY_INPUT_MANAGER guard to InputAxisNamePropertyDrawer
=> CMCL-0000: InputAxisNamePropertyDrawer is not guarded

com.unity.cinemachine/Runtime/Core/OutputChannel.cs
=> CMCL-0000: add missing XML doc for channels

com.unity.cinemachine/Documentation~/KnownIssues.md, com.unity.cinemachine/Documentation~/TableOfContents.md
CMCL-937: Add a known issues section to document... ... ... (wait for it) ... known issues.
=> CMCL-937: added known issues section to doc

com.unity.cinemachine/Editor/Editors/CinemachineSplineCartEditor.cs, com.unity.cinemachine/Editor/Editors/CinemachineSplineCartEditor.cs.meta, com.unity.cinemachine/Editor/Editors/CinemachineSplineDollyEditor.cs, com.unity.cinemachine/Editor/Menus/CinemachineMenu.cs, com.unity.cinemachine/Editor/PropertyDrawers/SplineAutoDollyPropertyDrawer.cs, com.unity.cinemachine/Runtime/Core/SplineAutoDolly.cs
CMCL-1276: AutoDolly property drawer now supports multi-select
=> CMCL-1276: Add multiselect support for auto dolly

com.unity.cinemachine/CHANGELOG.md, com.unity.cinemachine/Editor/Editors/CinemachinePathEditor.cs, com.unity.cinemachine/Editor/Editors/CinemachineSmoothPathEditor.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachinePath.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachineSmoothPath.cs, com.unity.cinemachine/Runtime/Core/CinemachinePathBase.cs, com.unity.cinemachine/Runtime/Core/SplineHelpers.cs
Backport of #674: optimize path gizmo drawing
=> CMCL-1270: optimize path gizmos for 2.9

com.unity.cinemachine/Editor/Editors/CinemachineConfiner2DEditor.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachineConfiner2D.cs, com.unity.cinemachine/Tests/Runtime/Confiner2DUnitTests.cs
Confiner2D inspector in UITK.
API change for confiner2D: OversizeWindow is foldout with enabled flag
=> CMCL-0000: Confiner2D inspector in uitk

com.unity.cinemachine/Runtime/Behaviours/CinemachineTargetGroup.cs
Recent TargetGroup commit introduced a cache problem.  Fix it here.
=> CMCL-0000: target group: auto-update if needed

com.unity.cinemachine/Runtime/Behaviours/CinemachineTargetGroup.cs
=> CMCL-0000: auto-update targetgroup if needed for 2.9

CHANGELOG.md, Runtime/Core/CinemachinePathBase.cs
[CMCL-1320](https://jira.unity3d.com/browse/CMCL-1320), backport of [CMCL-1307](https://jira.unity3d.com/browse/CMCL-1307) - [PR](https://github.com/Unity-Technologies/com.unity.cinemachine/pull/708)
=> CMCL-1320: FindClosestPoint fix (#708)

com.unity.cinemachine/Runtime/Behaviours/CinemachineThirdPersonAim.cs, com.unity.cinemachine/Runtime/Components/CinemachineThirdPersonFollow.cs
~3rdPersonFollow sets LookAt target, just to have something.  Not sure 100% if this is a good idea. 
Also some cosmetic.~
Just cosmetic, no code change
=> CMCL-0000: cosmetic

com.unity.cinemachine/CHANGELOG.md, com.unity.cinemachine/Editor/Editors/CinemachinePathEditor.cs, com.unity.cinemachine/Editor/Menus/CinemachineMenu.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachineBlendListCamera.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachinePath.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachineSmoothPath.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachineStateDrivenCamera.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachineTargetGroup.cs, com.unity.cinemachine/Runtime/Components/CinemachinePOV.cs, com.unity.cinemachine/Runtime/Core/CinemachineCore.cs, com.unity.cinemachine/Runtime/Core/CinemachineVirtualCameraBase.cs, com.unity.cinemachine/Runtime/Core/NoiseSettings.cs, com.unity.cinemachine/Tests/Runtime/Confiner2DUnitTests.cs
Backport of https://github.com/Unity-Technologies/com.unity.cinemachine/pull/727.
And additional deprecated API calls fixed.
C# syntax fixed in unity 2019 and 2020
=> CMCL-0000:  Fix deprecated calls in 2023, and invalid C# calls in 2019,2020 - cm 2.9

com.unity.cinemachine/Editor/Menus/CinemachineMenu.cs, com.unity.cinemachine/Runtime/Core/CinemachineVirtualCameraBase.cs
Replaced some deprecated calls with their new version in 2023+.
=> CMCL-0000: Fix deprecated calls in 2023

com.unity.cinemachine/Editor/Menus/CinemachineMenu.cs, com.unity.cinemachine/Runtime/Core/CinemachineVirtualCameraBase.cs
Backport of consistent calls from https://github.com/Unity-Technologies/com.unity.cinemachine/pull/727.
=> CMCL-0000: Backport consistent calls from cm3

com.unity.cinemachine/Editor/Overlays/CinemachineToolbarOverlay.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachineBlendListCamera.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachineClearShot.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachineMixingCamera.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachineStoryboard.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachineTargetGroup.cs, com.unity.cinemachine/Runtime/Components/CinemachineSplineDolly.cs, com.unity.cinemachine/Runtime/Core/CinemachineCameraManagerBase.cs, com.unity.cinemachine/Runtime/Core/SplineAutoDolly.cs, com.unity.cinemachine/Runtime/Deprecated/AxisState.cs, com.unity.cinemachine/Runtime/Deprecated/CinemachineFreeLook.cs, com.unity.cinemachine/Runtime/Deprecated/CinemachineOrbitalTransposer.cs, com.unity.cinemachine/Runtime/Deprecated/CinemachinePOV.cs
Add missing XML doc, as reported by package validation
=> CMCL-0000: Add missing XML doc, as reported by package validation

com.unity.cinemachine/Samples~/3D Samples/ThirdPersonShooter/ThirdPerson Shooter.unity
Added missing input in ThirdPerson Shooter.
=> CMCL-0000: Added missing input in ThirdPerson Shooter. 

com.unity.cinemachine/Tests/Editor/DampingTests.cs
=> CMCL-0000: unit test refactor

com.unity.cinemachine/Runtime/Core/Predictor.cs
CMCL-1315:  Performance improvement for experimental damping, tested in CM 3.  This address only the poor performance, not the behaviour discrepancy with standard damping.  There should be no behaviour difference from the previous implementation.
###
=> CMCL-1315: experimental damping performance 2.9

com.unity.cinemachine/Editor/PropertyDrawers/LensSettingsPropertyDrawer.cs, com.unity.cinemachine/Runtime/Core/LensSettings.cs
CMCL-1350:
Add some missing null checks.
Also a little cleanup.
=> CMCL-1350: fix fov drag exception

com.unity.cinemachine/CHANGELOG.md, com.unity.cinemachine/Runtime/Components/CinemachineTransposer.cs, com.unity.cinemachine/Runtime/Core/AxisState.cs
CMCL-1358: Very difficult to reproduce, but real.  See detailed description in Jira issue.
low
This is difficult to test because the problem is extremely hard to reproduce in the first place.  It's an edge-case condition.  I've given the fix to the original poster on the forum, who is more easily able to repro.  They will confirm the fix.  I think the testing here should just be a manual reading of the code, and a checking that nothing was broken by the change.
=> CMCL-1358: very rare axis drift

com.unity.cinemachine/Runtime/Behaviours/CinemachineConfiner2D.cs
Fix aspect ratio in confiner2D. It relates to bounding cache, not lens cache.
Also renamed `m_extraStateCache` -> `m_ExtraStateCache`
=> CMCL-0000: Fix aspect ratio in confiner2D

com.unity.cinemachine/Samples~/2D Samples.meta, com.unity.cinemachine/Samples~/2D Samples/CameraMagnets.unity, com.unity.cinemachine/Samples~/3D Samples.meta, com.unity.cinemachine/Samples~/3D Samples/Clearshot/RunningRace.unity, com.unity.cinemachine/Samples~/3D Samples/Impulse/Impulse Wave.unity, com.unity.cinemachine/Samples~/Shared Assets.meta, com.unity.cinemachine/Samples~/Shared Assets/Scripts/SamplesButtonGUI.cs, com.unity.cinemachine/Samples~/Shared Assets/Scripts/SamplesButtonGUI.cs.meta, com.unity.cinemachine/Samples~/Shared Assets/Scripts/SamplesToggleGUI.cs, com.unity.cinemachine/Samples~/Shared Assets/Scripts/SamplesToggleGUI.cs.meta
Added two shared scripts (SamplesToggleGUI and SamplesButtonGUI). 
Updated samples scenes to use these instead of canvases and non-generic input modules.
=> CMCL-1355: OnGUI for toggles and buttons

com.unity.cinemachine/Editor/Utility/SaveDuringPlay.cs
=> CMCL-1361: saveduringplay bugfix for 2.9

com.unity.cinemachine/Editor/Overlays/CinemachineToolbarOverlay.cs, com.unity.cinemachine/Editor/Utility/BaseEditor.cs, com.unity.cinemachine/Editor/Utility/CinemachineLensPresets.cs, com.unity.cinemachine/Editor/Utility/CmPipelineComponentInspectorUtility.cs, com.unity.cinemachine/Editor/Utility/GameViewComposerGuides.cs, com.unity.cinemachine/Editor/Utility/SerializedPropertyHelper.cs
Last batch for the public stuff. Might still be some left but should cover at least the most commonly viewed docs
=> CMCL-0000: Fix typos in Editor and utility folders

com.unity.cinemachine/Editor/Upgrader/UpgradeObjectToCm3.cs
=> CMCL-0000: gigaya upgrader fix 2

com.unity.cinemachine/Editor/Editors/CinemachineFreeLookModifierEditor.cs, com.unity.cinemachine/Editor/Utility/InspectorUtility.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachineFreeLookModifier.cs
=> CMCL-0000: FreeLookModifier inspector in UITK

com.unity.cinemachine/CHANGELOG.md
Update changelog to fit convensions.
Added some missing items.
=> CMCL-0000: Update CHANGELOG.md

com.unity.cinemachine/CHANGELOG.md
Add missing items.
Update conventions
=> CMCL-0000: Backport changelog to release branch

.yamato/package-ci.yml
=> CMCL-0000 CI add run all test job

com.unity.cinemachine/Editor/Editors/CinemachineFreeLookModifierEditor.cs, com.unity.cinemachine/Editor/Utility/ReflectionHelpers.cs, com.unity.cinemachine/Editor/Utility/SerializedPropertyHelper.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachineFreeLookModifier.cs
Noticed errors when adding and removing FreeLookModifier elements
=> CMCL-0000: Added some missing null and range checks

com.unity.cinemachine/package.json
Bump minimal version of unity for URP support
=> CMCL-0000: Update minimal supported version of unity

com.unity.cinemachine/Runtime/Helpers/InputAxisController.cs
"I'm making a PR with a temporary fix for this - basically removing the smart read logic.  Also it addresses an error in the CreateDefaultControlForAxis API"
=> CMCL-0000: InputAxisController bugfixes

com.unity.cinemachine/Editor/Editors/CinemachineBlendListCameraEditor.cs, com.unity.cinemachine/Editor/Editors/CinemachineOrbitalFollowEditor.cs, com.unity.cinemachine/Editor/PropertyDrawers/BlendDefinitionPropertyDrawer.cs, com.unity.cinemachine/Editor/Utility/CmCameraInspectorUtility.cs, com.unity.cinemachine/Editor/Utility/EmbeddedAssetEditorUtility.cs
Small cosmetic fixes for #796.
- vars
- small code reductions
- consts
- local function params don't hide outer params
=> CMCL-0000: fixes for #796

com.unity.cinemachine/Samples~/3D Samples/Brain Update Modes.unity
[CMCL-1399](https://jira.unity3d.com/browse/CMCL-1399):
SmartUpdate screen now automatically switches between targets, using a BlendList camera.,
=> CMCL-1399: improve BrainUpdateModes sample - blendlist camera

com.unity.cinemachine/Editor/Menus/CinemachineMenu.cs
auto-select the new object only if requested
=> CMCL-0000: auto-select the new object only if requested

com.unity.cinemachine/Editor/Editors/CinemachineBrainEditor.cs, com.unity.cinemachine/Editor/Editors/CinemachineOrbitalFollowEditor.cs, com.unity.cinemachine/Editor/Editors/CinemachinePanTiltEditor.cs, com.unity.cinemachine/Editor/Editors/CinemachineSplineDollyEditor.cs, com.unity.cinemachine/Editor/PostProcessing/CinemachineAutoFocusEditor.cs, com.unity.cinemachine/Editor/PropertyDrawers/BlendDefinitionPropertyDrawer.cs, com.unity.cinemachine/Editor/PropertyDrawers/MinMaxRangeSliderPropertyDrawer.cs, com.unity.cinemachine/Editor/PropertyDrawers/TagFieldPropertyDrawer.cs, com.unity.cinemachine/Editor/PropertyDrawers/ThreeOrbitRigPropertyDrawer.cs, com.unity.cinemachine/Editor/PropertyDrawers/Vector2AsRangePropertyDrawer.cs, com.unity.cinemachine/Editor/Timeline/CinemachineShotEditor.cs, com.unity.cinemachine/Editor/Utility/CmCameraInspectorUtility.cs, com.unity.cinemachine/Editor/Utility/CmPipelineComponentInspectorUtility.cs, com.unity.cinemachine/Editor/Utility/EmbeddedAssetEditorUtility.cs, com.unity.cinemachine/Editor/Utility/InspectorUtility.cs, com.unity.cinemachine/Runtime/Core/TargetPositionCache.cs, com.unity.cinemachine/Runtime/Core/UpdateTracker.cs, com.unity.cinemachine/Runtime/PostProcessing/CinemachinePostProcessing.cs
Renames, file reordering.  Also removed a small layout hack.
=> CMCL-0000: InspectorUtility API cleanup, mostly cosmetic

com.unity.cinemachine/Editor/Editors/CinemachineBlenderSettingsEditor.cs, com.unity.cinemachine/Editor/Editors/CinemachineBrainEditor.cs, com.unity.cinemachine/Editor/Editors/CinemachineClearShotEditor.cs, com.unity.cinemachine/Editor/Editors/CinemachineFreeLookModifierEditor.cs, com.unity.cinemachine/Editor/Editors/CinemachineSequencerCameraEditor.cs, com.unity.cinemachine/Editor/Editors/CinemachineStateDrivenCameraEditor.cs, com.unity.cinemachine/Editor/Obsolete/VcamTargetPropertyDrawer.cs, com.unity.cinemachine/Editor/PropertyDrawers/CameraTargetPropertyDrawer.cs, com.unity.cinemachine/Editor/PropertyDrawers/EmbeddedAssetPropertyDrawer.cs, com.unity.cinemachine/Editor/PropertyDrawers/InputAxisNamePropertyDrawer.cs, com.unity.cinemachine/Editor/Utility/CmCameraInspectorUtility.cs, com.unity.cinemachine/Editor/Utility/EmbeddedAssetEditorUtility.cs, com.unity.cinemachine/Editor/Utility/InspectorUtility.cs
UITK implementation of CinemachineBlenderSettingsEditor.
Note: code is commented out until UITK ListView bugs are fixed (UUM-27687 and UUM-27688)
Also:
- Added InspectorUtility.MiniHelpIcon
- Added InspectorUtility.MiniPopupButton
- Refactored EmbeddedAssetEditorUtility a little
=> CMCL-1389: CinemachineBlenderSettingsEditor in uitk

com.unity.cinemachine/Editor/Utility/CmCameraInspectorUtility.cs
Add message in inspector when CinemachineCamera is parented to CMBrain or another CmCamera
=> CMCL-0000: Add parenting warning message

com.unity.cinemachine/Editor/Utility/CmCameraInspectorUtility.cs
Procedural popups were not being correctly updated after undo/redo of component removal.
=> CMCL-1400: CmCamera inspector refresh bug

com.unity.cinemachine/Editor/Editors/CinemachineTriggerActionEditor.cs, com.unity.cinemachine/Editor/Utility/CmPipelineComponentInspectorUtility.cs, com.unity.cinemachine/Runtime/Helpers/CinemachineTriggerAction.cs
=> CMCL-1392: CinemachineTriggerActionEditor in uitk

com.unity.cinemachine/Editor/Editors/CinemachineSequencerCameraEditor.cs, com.unity.cinemachine/Editor/Editors/CinemachineStateDrivenCameraEditor.cs, com.unity.cinemachine/Editor/PropertyDrawers/LensSettingsPropertyDrawer.cs
Th code was overly-complex.  This PR simplifies it and makes it more maintainable.
=> CMCL-0000: lens property drawer refactor

com.unity.cinemachine/Editor/Editors/CinemachineBasicMultiChannelPerlinEditor.cs, com.unity.cinemachine/Editor/PropertyDrawers/NoiseSettingsPropertyDrawer.cs, com.unity.cinemachine/Editor/Utility/EmbeddedAssetEditorUtility.cs
NoiseSettingsPropertyDrawer and CinemachineBasicMultiChannelPerlinEditor in uitk
=> CMCL-1386: CinemachineBasicMultiChannelPerlinEditor in uitk

com.unity.cinemachine/Editor/Upgrader/UpgradeManagerInspectorHelpers.cs
=> CMCL-1418: Add upgrader note to look at console

com.unity.cinemachine/Editor/PropertyDrawers/FoldoutWithEnabledButtonPropertyDrawer.cs, com.unity.cinemachine/Editor/Utility/InspectorUtility.cs, com.unity.cinemachine/Runtime/Core/OutputChannel.cs
Fix broken Priority dragger
Also fixed up a couple of tooltips that were wrong
=> CMCL-0000: fix Priority dragger

com.unity.cinemachine/Editor/Utility/CmCameraInspectorUtility.cs
Sequencer was not playing when in Solo mode
=> CMCL-1443: Solo mode should play the sequencer

com.unity.cinemachine/Runtime/Deprecated/CinemachinePathBase.cs, com.unity.cinemachine/Runtime/Deprecated/CinemachineSmoothPath.cs
Port the smooth path incorrect orientation to legacy code.
=> CMCL-0000: Port fix smooth path orientation fix

com.unity.cinemachine/CHANGELOG.md, com.unity.cinemachine/Runtime/Behaviours/CinemachineCollider.cs
=> CMCL-1496: Dev/collider implements on target object warped

com.unity.cinemachine/CHANGELOG.md, com.unity.cinemachine/Runtime/Components/CinemachineFramingTransposer.cs, com.unity.cinemachine/package.json
=> CMCL-1497: framing transposer sets fov first

com.unity.cinemachine/Samples~/Input System Samples/Split Screen Multiplayer/PlayerWithCameraRig.prefab, com.unity.cinemachine/Samples~/Input System Samples/Split Screen Multiplayer/Split Screen Multiplayer.unity
CMCL-1501: restore missing action references
=> CMCL-1501: multiplayer sample missing input action assets

com.unity.cinemachine/Editor/Utility/CinemachineEditorAnalytics.cs
Old analytics API is deprecated in 2023.2, and generates console warnings.
Use the new API.
Don't know how to test if the new analytics calls are actually doing what we think they are.
=> CMCL-1514: Use new analytics API for 2023.2

com.unity.cinemachine/CHANGELOG.md
Make change-log match conventions
=> CMCL-0000: Updated change-log to match conventions

ValidationExceptions.json
=> CMCL-0000: Add validation exception for version bump

com.unity.cinemachine/CHANGELOG.md, com.unity.cinemachine/Editor/SaveDuringPlay/SaveDuringPlay.cs, com.unity.cinemachine/Tests/.tests.json, com.unity.cinemachine/Tests/CmCameraProceduralBehaviourCacheTests.cs
CMCL-1531: SaveDuringPlay should work with multiple scenes opened using Open Scene Additive.
low
=> CMCL-1531: SaveDuringPlay supports multi-scene editing

com.unity.cinemachine/CHANGELOG.md
Add changes added by Thomas to the camera overlay.
=> Missing items in changelog.

com.unity.cinemachine/CHANGELOG.md, com.unity.cinemachine/ValidationExceptions.json
=> CMCL-0000: Update changelog version to 2.9.8

.yamato/package-documentation.yml
CI: Add a doc generation job for Cinemachine
Sebastien needs a CI job which can generate documentation for Cinemachine's main branch so that he can check whether the doc he put is right or not. Without this CI job, he needs to generate documentation manually which is time consuming and boring.
Please have a look at [the artifacts of Generate documentation job](https://unity-ci.cds.internal.unity3d.com/job/32369509/artifacts), `documentation/Package_Doc->index.html`.
[CMCL-1540](https://jira.unity3d.com/browse/CMCL-1540) CI: Add a documentation …
=> CMCL-1540: Add doc generation job for Cinemachine

com.unity.cinemachine/Editor/EditorResources/CMWaveform.compute
CMCl-1557.  Add support for HLSL 2021
Compute shader was not compiling in HLSL 2021
[Justification for updating either the patch, minor, or major version according to the [semantic …
=> CMCL-1557: support HLSL 2021

com.unity.cinemachine/Tests/.tests.json
Make tests as a separate package again.
[Info per person for what to focus on, or historical info to understand …
=> CMCL-0000: Make tests as a separate package

com.unity.cinemachine/Editor/PostProcessing/CinemachinePostProcessingEditor.cs, com.unity.cinemachine/Editor/PostProcessing/CinemachineVolumeSettingsEditor.cs
Part of the ongoing purge of IMGUI
=> CMCL-1396: PostProcessing and VolumeSettings editors in UITK

com.unity.cinemachine/ValidationExceptions.json
Ignore error caused by switching from a field to a property.
=> CMCL-0000: Update validation exceptions

com.unity.cinemachine/Editor/Obsolete/CinemachineDollyCartEditor.cs, com.unity.cinemachine/Editor/Obsolete/CinemachineFreeLookEditor.cs, com.unity.cinemachine/Editor/Obsolete/CinemachinePathEditor.cs, com.unity.cinemachine/Editor/Obsolete/CinemachineSmoothPathEditor.cs, com.unity.cinemachine/Editor/Obsolete/CinemachineVirtualCameraEditor.cs, com.unity.cinemachine/Editor/Upgrader/UpgradeManagerInspectorHelpers.cs, com.unity.cinemachine/Editor/Utility/CmPipelineComponentInspectorUtility.cs, com.unity.cinemachine/Editor/Utility/InspectorUtility.cs
The UX design team has decided how helpbox with buttons should look.  See https://jira.unity3d.com/browse/UXQA-469.
This PR moves our implementation closer to the style guidelines (for IMGUI it's not exact because the infrastructure is not there, but we got it as close as we can).
IMGUI:
UITK:
InspectorUtility.cs has some code moved around, but otherwise unchanged.  The relevant diffs are in the two HelpBoxWithButton() methods.
low
=> CMCL-0000: Retool the helpbox with button UX according to guidelines

com.unity.cinemachine/ValidationExceptions.json
=> CMCL-0000: Minor bump on validation exception

com.unity.cinemachine/ValidationExceptions.json
=> CMCL-0000: Fix validation exceptions version

com.unity.cinemachine/Runtime/Behaviours/CinemachineBrain.cs
[DOCATT-5020](https://jira.unity3d.com/browse/DOCATT-5020) - Correct typos in the API
**Note:** The initial goal of this ticket was to fix possible typos in the CM 3.0 API docs, with a main focus on the CinemachineBrain API doc page. As we don't have the bandwidth to do the whole as of today, I'm focusing only on this one file about the Brain. We'll try to make other ad-hoc reviews as we go for the rest in subsequent tickets/PRs.
Here, I didn't find actual typos but I mostly fixed things like:
- Future to present tense
- Passive to active voice (lazily, as it's sometimes not a big deal)
- object to GameObject
- vcam, Virtual Camera, CM Camera to CinemachineCamera
=> CMCL-0000: DOCATT-5020 - Soft review of targeted API docs

Projects/HDRP/Packages/manifest.json, Projects/HDRP2019.4/Packages/manifest.json, Projects/Standalone/Packages/manifest.json, Projects/URP/Packages/manifest.json
=> Add disable project update in test projects

com.unity.cinemachine/Editor/Editors/CinemachineFreeLookModifierEditor.cs, com.unity.cinemachine/Editor/Editors/CinemachineMixingCameraEditor.cs, com.unity.cinemachine/Editor/Editors/CinemachineSplineDollyLookAtTargetsEditor.cs, com.unity.cinemachine/Editor/Editors/CinemachineSplineRollEditor.cs, com.unity.cinemachine/Editor/PropertyDrawers/EmbeddedAssetPropertyDrawer.cs, com.unity.cinemachine/Editor/Utility/CinemachineSceneToolHelpers.cs, com.unity.cinemachine/Editor/Utility/CmCameraInspectorUtility.cs
CMCL-1640: minor UX misalignments
zero
=> CMCL-1640: Fix UX issues raised by design team

com.unity.cinemachine/CHANGELOG.md, com.unity.cinemachine/Editor/Editors/CinemachineConfiner2DEditor.cs, com.unity.cinemachine/Runtime/Behaviours/CinemachineConfiner2D.cs
Bugfix for https://unity3d.atlassian.net/servicedesk/customer/portal/2/IN-96211
Bug was introduced in CM 3.1.3
low
=> CMCL-1652: confiner2d regression fix

com.unity.cinemachine/Documentation~/samples-tutorials.md
[DOCATT-8058](https://jira.unity3d.com/browse/DOCATT-8058) - User feedback: videos are old (but we know it)
- Moved up the existing note (which mentions the YouTube videos are old but still show interesting concepts) to make it more visible and bring more awareness of that state to the reader.
- Slightly changed the first words to make the note more introductive.
=> CMCL-0000: Docs - Moved up the note about videos

com.unity.cinemachine/CHANGELOG.md, com.unity.cinemachine/Editor/Samples/SampleDependencyImporter.cs, com.unity.cinemachine/Samples~/3D Samples/Cutscene.unity, com.unity.cinemachine/Samples~/3D Samples/FreeLook Deoccluder.unity, com.unity.cinemachine/Samples~/3D Samples/MixingCamera.unity, com.unity.cinemachine/Samples~/3D Samples/SplitScreenCar.unity, com.unity.cinemachine/Samples~/3D Samples/ThirdPersonWithAimMode.unity, com.unity.cinemachine/Samples~/3D Samples/ThirdPersonWithRoadieRun.unity, com.unity.cinemachine/Samples~/Input System Samples/Split Screen Multiplayer/PlayerWithCameraRig.prefab, com.unity.cinemachine/Samples~/Input System Samples/Split Screen Multiplayer/Split Screen Multiplayer.unity
CMCL-1660: A number of issues with the samples
- Typos in help texts
- Bad control mappings
- Broken material transparency (URP)
- Extra unused components on some GameObjects (confusing)
- Input and Lighting assets not working in all the modes 
- builtin/HDRP/URP
- LegacyInput/NewInput/Both
low
=> CMCL-1660: Problems with samples

com.unity.cinemachine/Documentation~/concept-essential-elements.md
teeny weeny doc tweak, inspired by someone's minor confusion on Discord
=> CMCL-0000: Update concept-essential-elements.md

com.unity.cinemachine/package.json
Help people understand that upgrading a project from CM2 to CM3 is not a trivial affair.
=> CMCL-0000: add upgrade note to package manager display

com.unity.cinemachine/Editor/PropertyDrawers/LensSettingsPropertyDrawer.cs
[[Delete any line or section that does not apply]](https://jira.unity3d.com/browse/CMCL-1719)
[CMCL-1719](https://jira.unity3d.com/browse/CMCL-1719)
0
=> don't draw palette menu separator unless needed

Projects/HDRPInputSystem/Packages/manifest.json, Projects/StandaloneInputSystem/Packages/manifest.json, Projects/URPInputSystem/Packages/manifest.json, com.unity.cinemachine/CHANGELOG.md, com.unity.cinemachine/Editor/PropertyDrawers/InputAxisPropertyDrawer.cs, com.unity.cinemachine/Editor/Utility/InspectorUtility.cs, com.unity.cinemachine/Runtime/Helpers/CinemachineInputAxisController.cs
https://jira.unity3d.com/browse/CINE-992
low
=> Input Axis Controller was not always reading composite actions correctly
